export enum AccountStatuses {
  ACTIVE = 'ACTIVE',
  APPROVED = 'APPROVED',
  ARCHIVED = 'ARCHIVED',
  CLOSED = 'CLOSED',
  DELINQUENT = 'DELINQUENT',
  FROZEN = 'FROZEN',
  INACTIVE = 'INACTIVE',
  LOSS_ASSET = 'LOSS_ASSET',
  PENDING = 'PENDING',
  REJECTED = 'REJECTED',
  WRITTEN_OFF = 'WRITTEN_OFF',
  UNKNOWN = 'UNKNOWN',
}

export enum AccountTypes {
  EQUIPMENT_LOAN = 'EQUIPMENT_LOAN',
  INPUT_LOAN = 'INPUT_LOAN',
  LAND_LOAN = 'LAND_LOAN',
  MASTERLINE = 'MASTERLINE',
  MORTGAGE = 'MORTGAGE',
  NLOC = 'NLOC',
  OPERATION_LOAN = 'OPERATION_LOAN',
  RLOC = 'RLOC',
  UNKNOWN = 'UNKNOWN',
}

export enum AccrualMethods {
  ACTUAL_ACTUAL = 'ACTUAL_ACTUAL',
  ACTUAL_360 = 'ACTUAL_360',
  ACTUAL_365 = 'ACTUAL_365',
  ACTUAL_366 = 'ACTUAL_366',
  ACTUAL_365L = 'ACTUAL_365L',
  THIRTY_360 = 'THIRTY_360',
  THIRTY_360_EU = 'THIRTY_360_EU',
  THIRTY_360_ISDA = 'THIRTY_360_ISDA',
  BUSINESS_252 = 'BUSINESS_252',
  UNKNOWN = 'UNKNOWN',
}

export enum BillingMethods {
  ELECTRONIC = 'ELECTRONIC',
  PAPER = 'PAPER',
  UNKNOWN = 'UNKNOWN',
}

export enum CollateralTypes {
  OTHER = 'OTHER',
  BUILDING = 'BUILDING',
  GRAIN_CROP = 'GRAIN_CROP',
  LAND = 'LAND',
  LIVESTOCK = 'LIVESTOCK',
  MACHINERY = 'MACHINERY',
  PERSONAL = 'PERSONAL',
  WATER_RIGHT = 'WATER_RIGHT',
  UNKNOWN = 'UNKNOWN',
}

export enum DbOperationTypes {
  CREATE = 'CREATE',
  READ = 'READ',
  PATCH = 'PATCH',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  UNKNOWN = 'UNKNOWN',
}

export enum DrawRequestStatuses {
  APPROVED = 'APPROVED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
  PENDING = 'PENDING',
  REJECTED = 'REJECTED',
  UNKNOWN = 'UNKNOWN',
}

export enum EndingOnUnits {
  UNKNOWN = 'UNKNOWN',
  DAYS = 'DAYS',
  MONTHS = 'MONTHS',
  SPECIFIC_DATE = 'SPECIFIC_DATE',
  WEEKS = 'WEEKS',
  YEARS = 'YEARS',
}

export enum FeeAmountApplicationRules {
  ADD = 'ADD',
  DIVIDE = 'DIVIDE',
  MULTIPLY = 'MULTIPLY',
  SUBTRACT = 'SUBTRACT',
  TAKE_BIGGEST = 'TAKE_BIGGEST',
  TAKE_SMALLEST = 'TAKE_SMALLEST',
  UNKNOWN = 'UNKNOWN',
}

export enum FeeAmountTypes {
  AMOUNT_CENTS = 'AMOUNT_CENTS',
  BASIS_POINTS = 'BASIS_POINTS',
  PER_MILLE = 'PER_MILLE',
  UNKNOWN = 'UNKNOWN',
}

export enum FeeCategories {
  ANNUAL = 'ANNUAL',
  BALANCE_TRANSFER = 'BALANCE_TRANSFER',
  CASH_ADVANCE = 'CASH_ADVANCE',
  CLOSURE = 'CLOSURE',
  DRAW = 'DRAW',
  LATE = 'LATE',
  LEGAL = 'LEGAL',
  MAINTENANCE = 'MAINTENANCE',
  ORIGINATION = 'ORIGINATION',
  OTHER = 'OTHER',
  OVERDRAFT = 'OVERDRAFT',
  PENALTY = 'PENALTY',
  PREPAYMENT = 'PREPAYMENT',
  UNDERWRITING = 'UNDERWRITING',
  UNKNOWN = 'UNKNOWN',
}

export enum FeeComputeSources {
  CREDIT_LIMIT = 'CREDIT_LIMIT',
  EXTERNAL = 'EXTERNAL',
  INTEREST_DUE = 'INTEREST_DUE',
  NONE = 'NONE',
  ORIGINAL_AMOUNT = 'ORIGINAL_AMOUNT',
  OUSTANDING_PRINCIPAL = 'OUSTANDING_PRINCIPAL',
  PAST_DUE_AMOUNT = 'PAST_DUE_AMOUNT',
  PAYMENT_DUE = 'PAYMENT_DUE',
  PRINCIPAL_DUE = 'PRINCIPAL_DUE',
  UNUSED_COMMITMENT = 'UNUSED_COMMITMENT',
  UNKNOWN = 'UNKNOWN',
}

export enum FeeEarningMethods {
  OTHER = 'OTHER',
  AT_MATURITY = 'AT_MATURITY',
  EFFECTIVE_INTEREST = 'EFFECTIVE_INTEREST',
  IMMEDIATE = 'IMMEDIATE',
  STRAIGHT_LINE = 'STRAIGHT_LINE',
  UNKNOWN = 'UNKNOWN',
}

export enum FrequencyUnits {
  ONCE = 'ONCE',
  YEARS = 'YEARS',
  MONTHS = 'MONTHS',
  DAYS = 'DAYS',
  UNKNOWN = 'UNKNOWN',
}

export enum LendBalances {
  CURRENT_BALANCE = 'CURRENT_BALANCE',
  INTEREST_DUE = 'INTEREST_DUE',
  LIMIT_AMOUNT = 'LIMIT_AMOUNT',
  ORIGINAL_BALANCE = 'ORIGINAL_BALANCE',
  PRINCIPAL_AND_INTEREST = 'PRINCIPAL_AND_INTEREST',
  PRINCIPAL_BALANCE = 'PRINCIPAL_BALANCE',
  PRINCIPAL_DUE = 'PRINCIPAL_DUE',
  UNKNOWN = 'UNKNOWN',
}

export enum OriginationChannels {
  BRANCH = 'BRANCH',
  CALL_CENTER = 'CALL_CENTER',
  CORRESPONDENT = 'CORRESPONDENT',
  DEALER = 'DEALER',
  DIRECT_MAIL = 'DIRECT_MAIL',
  MOBILE_APP = 'MOBILE_APP',
  PARTNER = 'PARTNER',
  REFERRAL = 'REFERRAL',
  RETAIL = 'RETAIL',
  UNDERWRITER = 'UNDERWRITER',
  WEB_APP = 'WEB_APP',
  UNKNOWN = 'UNKNOWN',
}

export enum PaymentAmountComputeMethods {
  AMORTIZED = 'AMORTIZED',
  FIXED_AMOUNT = 'FIXED_AMOUNT',
  INTEREST_ONLY = 'INTEREST_ONLY',
  MINIMUM_PAYMENT = 'MINIMUM_PAYMENT',
  PERCENT_OF_BALANCE = 'PERCENT_OF_BALANCE',
  PRINCIPAL_AND_INTEREST = 'PRINCIPAL_AND_INTEREST',
  PRINCIPAL_ONLY = 'PRINCIPAL_ONLY',
  RULE_BASED = 'RULE_BASED',
  UNKNOWN = 'UNKNOWN',
}

export enum PromissoryNotes {
  AMORTIZING_NOTE = 'AMORTIZING_NOTE',
  BALLOON_NOTE = 'BALLOON_NOTE',
  CONSTRUCTION_NOTE = 'CONSTRUCTION_NOTE',
  DEMAND_NOTE = 'DEMAND_NOTE',
  INSTALLMENT_NOTE = 'INSTALLMENT_NOTE',
  INTEREST_ONLY_NOTE = 'INTEREST_ONLY_NOTE',
  LINE_OF_CREDIT_NOTE = 'LINE_OF_CREDIT_NOTE',
  MORTGAGE_NOTE = 'MORTGAGE_NOTE',
  TIME_NOTE = 'TIME_NOTE',
  UNKNOWN = 'UNKNOWN',
}

export enum RateTypes {
  FIXED = 'FIXED',
  VARIABLE = 'VARIABLE',
  TIERED_BY_BALANCE = 'TIERED-BY-BALANCE',
  UNKNOWN = 'UNKNOWN',
}

export enum ReportingTypes {
  ACCOUNTING_CLASS = 'ACCOUNTING_CLASS',
  CALL_REPORT = 'CALL_REPORT',
  CAPITAL_REPORTING = 'CAPITAL_REPORTING',
  CREDIT_BUREAU = 'CREDIT_BUREAU',
  CREDIT_POLICY_SEGMENT = 'CREDIT_POLICY_SEGMENT',
  CRA = 'CRA',
  HMDA = 'HMDA',
  INTERNAL_PORTFOLIO_CODE = 'INTERNAL_PORTFOLIO_CODE',
  INTERNAL_PRODUCT_CODE = 'INTERNAL_PRODUCT_CODE',
  INTERNAL_RISK_BUCKET = 'INTERNAL_RISK_BUCKET',
  LOAN_PURPOSE_CODE = 'LOAN_PURPOSE_CODE',
  LOAN_PROGRAM_CODE = 'LOAN_PROGRAM_CODE',
  REGULATORY = 'REGULATORY',
  RISK_GRADE_SCHEME = 'RISK_GRADE_SCHEME',
  SEC_REPORTING = 'SEC_REPORTING',
  STRESS_TESTING = 'STRESS_TESTING',
  TAX_REPORTING = 'TAX_REPORTING',
  UNKNOWN = 'UNKNOWN',
}

export enum RetailerEarningMethods {
  EFFECTIVE_INTEREST = 'EFFECTIVE_INTEREST',
  IMMEDIATE = 'IMMEDIATE',
  PERFORMANCE_BASED = 'PERFORMANCE_BASED',
  PRO_RATA = 'PRO_RATA',
  STRAIGHT_LINE = 'STRAIGHT_LINE',
  UNKNOWN = 'UNKNOWN',
}

export enum RetailerRateCalculationMethods {
  FLAT_AMOUNT = 'FLAT_AMOUNT',
  PERCENT_OF_AMOUNT_FINANCED = 'PERCENT_OF_AMOUNT_FINANCED',
  PERCENT_OF_INTEREST = 'PERCENT_OF_INTEREST',
  PERCENT_OF_PAYMENT = 'PERCENT_OF_PAYMENT',
  RATE_SPREAD = 'RATE_SPREAD',
  STEPDOWN = 'STEPDOWN',
  TABLE_BASED = 'TABLE_BASED',
  TIERED = 'TIERED',
  YIELD_BASE = 'YIELD_BASE',
  UNKNOWN = 'UNKNOWN',
}

export enum RetailerRecourseType {
  FULL = 'FULL',
  LIMITED = 'LIMITED',
  NONE = 'NONE',
  PARTIAL = 'PARTIAL',
  REPURCHASE = 'REPURCHASE',
  UNKNOWN = 'UNKNOWN',
}

export enum RetailerReserveMethods {
  CHARGE_BACK_ELIGIBLE = 'CHARGE_BACK_ELIGIBLE',
  DEFERRED = 'DEFERRED',
  IMMEDIATE = 'IMMEDIATE',
  MONTHLY = 'MONTHLY',
  NETTED_AT_FUNDING = 'NETTED_AT_FUNDING',
  QUARTERLY = 'QUARTERLY',
  RETAINED_BY_LENDER = 'RETAINED_BY_LENDER',
  SETTLEMENT = 'SETTLEMENT',
  UPFRONT = 'UPFRONT',
  UNKNOWN = 'UNKNOWN',
}

export enum RiskCategories {
  OTHER = 'OTHER',
  AGRICULTURE = 'AGRICULTURE',
  AUTO = 'AUTO',
  BEHAVIORAL = 'BEHAVIORAL',
  BUSINESS = 'BUSINESS',
  COMMERCIAL = 'COMMERCIAL',
  CONSUMER = 'CONSUMER',
  CREDIT = 'CREDIT',
  ENVIRONMENTAL = 'ENVIRONMENTAL',
  FINANCIAL = 'FINANCIAL',
  FRAUD = 'FRAUD',
  HEALTH = 'HEALTH',
  INSURANCE = 'INSURANCE',
  LEGAL = 'LEGAL',
  MARKET = 'MARKET',
  MORTGAGE = 'MORTGAGE',
  OPERATIONAL = 'OPERATIONAL',
  PROPERTY = 'PROPERTY',
  REPUTATIONAL = 'REPUTATIONAL',
  STRATEGIC = 'STRATEGIC',
  UNDERWRITING = 'UNDERWRITING',
  UNKNOWN = 'UNKNOWN',
}

export enum RiskMeasureTypes {
  BEHAVIORAL_SCORE = 'BEHAVIORAL_SCORE',
  CREDIT_SCORE = 'CREDIT_SCORE',
  EXPOSURE = 'EXPOSURE',
  FREQUENCY = 'FREQUENCY',
  HAZARD = 'HAZARD',
  LOSS_COST = 'LOSS_COST',
  PD = 'PD',
  PML = 'PML',
  PURE_PREMIUM = 'PURE_PREMIUM',
  SEVERITY = 'SEVERITY',
  STRESS_SCORE = 'STRESS_SCORE',
  TVAR = 'TVAR',
  UNDERWRITING_SCORE = 'UNDERWRITING_SCORE',
  UNKNOWN = 'UNKNOWN',
  VAR = 'VAR',
}

export enum RiskPassingStatuses {
  APPROVED = 'APPROVED',
  DECLINED = 'DECLINED',
  INCOMPLETE = 'INCOMPLETE',
  MANUAL_REVIEW = 'MANUAL_REVIEW',
  PASSED = 'PASSED',
  PENDING = 'PENDING',
  UNKNOWN = 'UNKNOWN',
}

export enum RiskRatingGrades {
  AAA = 'AAA',
  AA = 'AA',
  A = 'A',
  BBB = 'BBB',
  BB = 'BB',
  B = 'B',
  CCC = 'CCC',
  CC = 'CC',
  C = 'C',
  D = 'D',
  E = 'E',
  F = 'F',
  H = 'H',
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  PASS = 'PASS',
  SPECIAL_MENTION = 'SPECIAL_MENTION',
  SUBSTANDARD = 'SUBSTANDARD',
  WATCH = 'WATCH',
  UNKNOWN = 'UNKNOWN',
}

export enum RiskReportStatuses {
  COMPLETED = 'COMPLETED',
  ERROR = 'ERROR',
  EXPIRED = 'EXPIRED',
  FAILED = 'FAILED',
  IN_PROGRESS = 'IN_PROGRESS',
  INVALID = 'INVALID',
  NOT_AVAILABLE = 'NOT_AVAILABLE',
  PENDING = 'PENDING',
  RECEIVED = 'RECEIVED',
  REJECTED = 'REJECTED',
  SUCCESS = 'SUCCESS',
  UNKNOWN = 'UNKNOWN',
}

export enum RiskReportTypes {
  OTHER = 'OTHER',
  ACCOUNT_REVIEW = 'ACCOUNT_REVIEW',
  APPLICATION = 'APPLICATION',
  AUTO = 'AUTO',
  BANKRUPTCY = 'BANKRUPTCY',
  CREDIT = 'CREDIT',
  FINANCIAL = 'FINANCIAL',
  FRAUD = 'FRAUD',
  IDENTITY = 'IDENTITY',
  INSURANCE = 'INSURANCE',
  LEGAL = 'LEGAL',
  MORTGAGE = 'MORTGAGE',
  PROPERTY = 'PROPERTY',
  RISK_ASSESSMENT = 'RISK_ASSESSMENT',
  UNDERWRITING = 'UNDERWRITING',
  UNKNOWN = 'UNKNOWN',
}

export enum RiskScoreTypes {
  APPLICATION = 'APPLICATION',
  BEHAVIORAL = 'BEHAVIORAL',
  BUREAU = 'BUREAU',
  COLLATERAL = 'COLLATERAL',
  CREDIT = 'CREDIT',
  FRAUD = 'FRAUD',
  INSURANCE = 'INSURANCE',
  OPERATIONAL = 'OPERATIONAL',
  OVERALL_RATING = 'OVERALL_RATING',
  RISK_MODEL = 'RISK_MODEL',
  UNDERWRITING = 'UNDERWRITING',
  UNKNOWN = 'UNKNOWN',
}

export enum RiskSourceSystem {
  OTHER = 'OTHER',
  AMEX = 'AMEX',
  CREDIT_KARMA = 'CREDIT_KARMA',
  CUSTOM = 'CUSTOM',
  EQUIFAX = 'EQUIFAX',
  EXPERIAN = 'EXPERIAN',
  FICO = 'FICO',
  FIS = 'FIS',
  FISERV = 'FISERV',
  INTERNAL_MODEL = 'INTERNAL_MODEL',
  INTERNAL_RIE = 'INTERNAL_RIE',
  JACK_HENRY = 'JACK_HENRY',
  KROLL = 'KROLL',
  MOODY_ANALYTICS = 'MOODY_ANALYTICS',
  MORNINGSTAR = 'MORNINGSTAR',
  ONESPAN = 'ONESPAN',
  PAYNET = 'PAYNET',
  S_AND_P = 'S_AND_P',
  TRANSUNION = 'TRANSUNION',
  UNKNOWN = 'UNKNOWN',
}

export enum RoundingMethods {
  NONE = 'NONE',
  ROUND_DOWN = 'ROUND_DOWN',
  ROUND_NEAREST = 'ROUND_NEAREST',
  ROUND_UP = 'ROUND_UP',
  TRUNCATE = 'TRUNCATE',
  UNKNOWN = 'UNKNOWN',
}

export enum StatementStatues {
  CANCELLED = 'CANCELLED',
  DUE = 'DUE',
  OVERDUE = 'OVERDUE',
  PAID = 'PAID',
  PENDING = 'PENDING',
  UNKNOWN = 'UNKNOWN',
}

export enum TimeUnits {
  YEAR = 'YEAR',
  MONTH = 'MONTH',
  DAY = 'DAY',
  HOUR = 'HOUR',
  MINUTE = 'MINUTE',
  SECOND = 'SECOND',
  UNKNOWN = 'UNKNOWN',
}

export enum Triggers {
  ON_LEND_AMORTIZATION = 'ON_LEND_AMORTIZATION',
  ON_LEND_DELINQUENCY = 'ON_LEND_DELINQUENCY',
  ON_LEND_DRAW = 'ON_LEND_DRAW',
  ON_LEND_MATURITY = 'ON_LEND_MATURITY',
  ON_LEND_MODIFICATION = 'ON_LEND_MODIFICATION',
  ON_LEND_NON_ACCRUAL_EVENT = 'ON_LEND_NON_ACCRUAL_EVENT',
  ON_LEND_ORIGINATION = 'ON_LEND_ORIGINATION',
  ON_LEND_PAYMENT_DUE_DATE = 'ON_LEND_PAYMENT_DUE_DATE',
  ON_LEND_PAYOFF = 'ON_LEND_PAYOFF',
  ON_LEND_PREPAY = 'ON_LEND_PREPAY',
  ON_LEND_REFINANCE = 'ON_LEND_REFINANCE',
  ON_LEND_RENEWAL = 'ON_LEND_RENEWAL',
}

export enum UserTypes {
  CORPORATION = 'CORPORATION',
  GP = 'GP',
  INDIVIDUAL = 'INDIVIDUAL',
  LENDER = 'LENDER',
  LLC = 'LLC',
  LLP = 'LLP',
  LP = 'LP',
  TRUST = 'TRUST',
  UNKNOWN = 'UNKNOWN',
}
