import type { ToolbarItem } from '@nutrient-sdk/viewer';

export const PREVIEW_ONLY_TOOLBAR: ToolbarItem[] = [
  { type: 'spacer' },
  { type: 'pager' },
  { type: 'zoom-out' },
  { type: 'zoom-in' },
  { type: 'search' },
];

export const MOBILE_BASIC_TOOLBAR: ToolbarItem[] = [
  { type: 'spacer' },
  { type: 'pager' },
  { type: 'zoom-out' },
  { type: 'zoom-in' },
  { type: 'search' },
];

export const BASIC_TOOLBAR: ToolbarItem[] = [
  { type: 'sidebar-thumbnails' },
  { type: 'sidebar-document-outline' },
  { type: 'sidebar-bookmarks' },
  { type: 'sidebar-signatures' },
  { type: 'sidebar-annotations' },
  { type: 'pan' },
  { type: 'zoom-out' },
  { type: 'zoom-in' },
  { type: 'zoom-mode' },
  { type: 'spacer' },
  // { type: 'comment' },
  { type: 'print' },
  { type: 'search' },
];

export const ANNOTATION_TOOLS: ToolbarItem[] = [
  { type: 'arrow' },
  { type: 'annotate' },
  { type: 'ink' },
  { type: 'highlighter' },
  { type: 'text-highlighter' },
  { type: 'ink-eraser' },
  { type: 'note' },
  { type: 'text' },
  { type: 'callout' },
  { type: 'line' },
  { type: 'link' },
  { type: 'arrow' },
  { type: 'rectangle' },
  { type: 'ellipse' },
  { type: 'polygon' },
  { type: 'cloudy-polygon' },
  { type: 'polyline' },
];

export const EDITION_TOOLBAR: ToolbarItem[] = [
  { type: 'sidebar-thumbnails' },
  { type: 'sidebar-document-outline' },
  { type: 'sidebar-annotations' },
  { type: 'sidebar-bookmarks' },
  { type: 'sidebar-signatures' },
  { type: 'sidebar-layers' },
  { type: 'multi-annotations-selection' },
  { type: 'pan' },
  { type: 'zoom-out' },
  { type: 'zoom-in' },
  { type: 'zoom-mode' },
  { type: 'undo' },
  { type: 'redo' },
  { type: 'spacer' },
  { type: 'annotate' },
  { type: 'ink' },
  { type: 'highlighter' },
  { type: 'text-highlighter' },
  { type: 'ink-eraser' },
  { type: 'signature' },
  { type: 'image' },
  { type: 'stamp' },
  { type: 'note' },
  { type: 'text' },
  { type: 'callout' },
  { type: 'line' },
  { type: 'link' },
  { type: 'arrow' },
  { type: 'rectangle' },
  { type: 'ellipse' },
  { type: 'polygon' },
  { type: 'cloudy-polygon' },
  { type: 'polyline' },
  { type: 'print' },
  { type: 'search' },
  { type: 'form-creator' },
];
