/**
 * Formula categories extracted from @formulajs/formulajs
 * This mapping is extracted from the library's TypeScript definitions.
 *
 * Categories are synchronized with the formula.js library metadata.
 */
export const FORMULA_CATEGORIES: Record<string, string> = {
  ABS: 'Math and trigonometry',
  ACCRINT: 'Financial',
  ACOS: 'Math and trigonometry',
  ACOSH: 'Math and trigonometry',
  ACOT: 'Math and trigonometry',
  ACOTH: 'Math and trigonometry',
  AGGREGATE: 'Math and trigonometry',
  AND: 'Logical',
  ARABIC: 'Math and trigonometry',
  ASIN: 'Math and trigonometry',
  ASINH: 'Math and trigonometry',
  ATAN: 'Math and trigonometry',
  ATANH: 'Math and trigonometry',
  AVEDEV: 'Statistical',
  AVERAGE: 'Statistical',
  AVERAGEA: 'Statistical',
  AVERAGEIF: 'Statistical',
  AVERAGEIFS: 'Statistical',
  BASE: 'Math and trigonometry',
  BESSELI: 'Engineering',
  BESSELJ: 'Engineering',
  BESSELK: 'Engineering',
  BESSELY: 'Engineering',
  BETADIST: 'Statistical',
  BETAINV: 'Statistical',
  BINOMDIST: 'Statistical',
  BITAND: 'Engineering',
  BITLSHIFT: 'Engineering',
  BITOR: 'Engineering',
  BITRSHIFT: 'Engineering',
  BITXOR: 'Engineering',
  CEILING: 'Math and trigonometry',
  CEILINGMATH: 'Math and trigonometry',
  CEILINGPRECISE: 'Math and trigonometry',
  CHAR: 'Text',
  CHIDIST: 'Statistical',
  CHIDISTRT: 'Statistical',
  CHIINV: 'Statistical',
  CHIINVRT: 'Statistical',
  CHITEST: 'Statistical',
  CHOOSE: 'Lookup and reference',
  CLEAN: 'Text',
  CODE: 'Text',
  COLUMN: 'Lookup and reference',
  COLUMNS: 'Lookup and reference',
  COMBIN: 'Math and trigonometry',
  COMBINA: 'Math and trigonometry',
  COMPLEX: 'Engineering',
  CONCAT: 'Text',
  CONCATENATE: 'Text',
  CONFIDENCE: 'Statistical',
  CONVERT: 'Engineering',
  CORREL: 'Statistical',
  COS: 'Math and trigonometry',
  COSH: 'Math and trigonometry',
  COT: 'Math and trigonometry',
  COTH: 'Math and trigonometry',
  COUNT: 'Statistical',
  COUNTA: 'Statistical',
  COUNTBLANK: 'Statistical',
  COUNTIF: 'Statistical',
  COUNTIFS: 'Statistical',
  COUNTIN: 'Statistical',
  COUNTUNIQUE: 'Statistical',
  COVARIANCE: 'Statistical',
  COVARIANCEP: 'Statistical',
  COVARIANCES: 'Statistical',
  CSC: 'Math and trigonometry',
  CSCH: 'Math and trigonometry',
  CUMIPMT: 'Financial',
  CUMPRINC: 'Financial',
  DATE: 'Date and time',
  DATEVALUE: 'Date and time',
  DAVERAGE: 'Database',
  DAY: 'Date and time',
  DAYS: 'Date and time',
  DAYS360: 'Date and time',
  DB: 'Financial',
  DCOUNT: 'Database',
  DCOUNTA: 'Database',
  DDB: 'Financial',
  DEC2BIN: 'Engineering',
  DEC2HEX: 'Engineering',
  DEC2OCT: 'Engineering',
  DECIMAL: 'Math and trigonometry',
  DEGREES: 'Math and trigonometry',
  DELTA: 'Engineering',
  DEVSQ: 'Statistical',
  DGET: 'Database',
  DISC: 'Financial',
  DMAX: 'Database',
  DMIN: 'Database',
  DOLLARDE: 'Financial',
  DOLLARFR: 'Financial',
  DPRODUCT: 'Database',
  DSTDEV: 'Database',
  DSTDEVP: 'Database',
  DSUM: 'Database',
  DURATION: 'Financial',
  DVAR: 'Database',
  DVARP: 'Database',
  EDATE: 'Date and time',
  EFFECT: 'Financial',
  EOMONTH: 'Date and time',
  ERF: 'Engineering',
  ERFC: 'Engineering',
  EVEN: 'Math and trigonometry',
  EXACT: 'Text',
  EXP: 'Math and trigonometry',
  EXPONDIST: 'Statistical',
  F: 'Text',
  FACT: 'Math and trigonometry',
  FACTDOUBLE: 'Math and trigonometry',
  FALSE: 'Logical',
  FDIST: 'Statistical',
  FDISTRT: 'Statistical',
  FINV: 'Statistical',
  FINVRT: 'Statistical',
  FISHER: 'Statistical',
  FISHERINV: 'Statistical',
  FLATTEN: 'Lookup and reference',
  FLOOR: 'Math and trigonometry',
  FLOORMATH: 'Math and trigonometry',
  FLOORPRECISE: 'Math and trigonometry',
  FORECAST: 'Statistical',
  FREQUENCY: 'Statistical',
  FV: 'Financial',
  FVSCHEDULE: 'Financial',
  GAMMA: 'Statistical',
  GAMMADIST: 'Statistical',
  GAMMAINV: 'Statistical',
  GAMMALN: 'Statistical',
  GAMMALNPRECISE: 'Statistical',
  GAUSS: 'Statistical',
  GCD: 'Math and trigonometry',
  GEOMEAN: 'Statistical',
  GESTEP: 'Engineering',
  GROWTH: 'Statistical',
  HARMEAN: 'Statistical',
  HEX2BIN: 'Engineering',
  HEX2DEC: 'Engineering',
  HEX2OCT: 'Engineering',
  HLOOKUP: 'Lookup and reference',
  HOUR: 'Date and time',
  HTML2TEXT: 'Text',
  HYPGEOMDIST: 'Statistical',
  IF: 'Logical',
  IFERROR: 'Logical',
  IFNA: 'Logical',
  IFS: 'Logical',
  IMABS: 'Engineering',
  IMAGINARY: 'Engineering',
  IMARGUMENT: 'Engineering',
  IMCONJUGATE: 'Engineering',
  IMCOS: 'Engineering',
  IMCOSH: 'Engineering',
  IMCOT: 'Engineering',
  IMCSC: 'Engineering',
  IMCSCH: 'Engineering',
  IMDIV: 'Engineering',
  IMEXP: 'Engineering',
  IMLN: 'Engineering',
  IMLOG10: 'Engineering',
  IMLOG2: 'Engineering',
  IMPOWER: 'Engineering',
  IMPRODUCT: 'Engineering',
  IMREAL: 'Engineering',
  IMSEC: 'Engineering',
  IMSECH: 'Engineering',
  IMSIN: 'Engineering',
  IMSINH: 'Engineering',
  IMSQRT: 'Engineering',
  IMSUB: 'Engineering',
  IMSUM: 'Engineering',
  IMTAN: 'Engineering',
  INT: 'Math and trigonometry',
  INTERCEPT: 'Statistical',
  INTRATE: 'Financial',
  IPMT: 'Financial',
  IRR: 'Financial',
  ISBLANK: 'Information',
  ISERR: 'Information',
  ISERROR: 'Information',
  ISEVEN: 'Information',
  ISLOGICAL: 'Information',
  ISNA: 'Information',
  ISNONTEXT: 'Information',
  ISNUMBER: 'Information',
  ISODD: 'Information',
  ISOWEEKNUM: 'Date and time',
  ISPMT: 'Financial',
  ISTEXT: 'Information',
  JOIN: 'Text',
  KURT: 'Statistical',
  LARGE: 'Statistical',
  LCM: 'Math and trigonometry',
  LEFT: 'Text',
  LEN: 'Text',
  LINEST: 'Statistical',
  LN: 'Math and trigonometry',
  LOG: 'Math and trigonometry',
  LOG10: 'Math and trigonometry',
  LOGEST: 'Statistical',
  LOGINV: 'Statistical',
  LOGNORMDIST: 'Statistical',
  LOOKUP: 'Lookup and reference',
  LOWER: 'Text',
  MATCH: 'Lookup and reference',
  MAX: 'Statistical',
  MAXA: 'Statistical',
  MDURATION: 'Financial',
  MEDIAN: 'Statistical',
  MID: 'Text',
  MIN: 'Statistical',
  MINA: 'Statistical',
  MINUTE: 'Date and time',
  MIRR: 'Financial',
  MOD: 'Math and trigonometry',
  MODE: 'Statistical',
  MODESNGL: 'Statistical',
  MONTH: 'Date and time',
  MROUND: 'Math and trigonometry',
  MULTINOMIAL: 'Math and trigonometry',
  NEGBINOMDIST: 'Statistical',
  NETWORKDAYS: 'Date and time',
  NETWORKDAYSINTL: 'Date and time',
  NOMINAL: 'Financial',
  NORMDIST: 'Statistical',
  NORMINV: 'Statistical',
  NORMSDIST: 'Statistical',
  NORMSINV: 'Statistical',
  NOT: 'Logical',
  NOW: 'Date and time',
  NPER: 'Financial',
  NPV: 'Financial',
  NUMBERS: 'Text',
  NUMERAL: 'Text',
  OCT2BIN: 'Engineering',
  OCT2DEC: 'Engineering',
  OCT2HEX: 'Engineering',
  ODD: 'Math and trigonometry',
  OR: 'Logical',
  PDURATION: 'Financial',
  PEARSON: 'Statistical',
  PERCENTILEEXC: 'Statistical',
  PERCENTILEINC: 'Statistical',
  PERCENTRANKEXC: 'Statistical',
  PERCENTRANKINC: 'Statistical',
  PERMUT: 'Math and trigonometry',
  PERMUTATIONA: 'Math and trigonometry',
  PHI: 'Statistical',
  PI: 'Math and trigonometry',
  PMT: 'Financial',
  POISSON: 'Statistical',
  POWER: 'Math and trigonometry',
  PPMT: 'Financial',
  PROB: 'Statistical',
  PRODUCT: 'Math and trigonometry',
  PROPER: 'Text',
  PV: 'Financial',
  QUARTILEEXC: 'Statistical',
  QUARTILEINC: 'Statistical',
  QUOTIENT: 'Math and trigonometry',
  RADIANS: 'Math and trigonometry',
  RAND: 'Math and trigonometry',
  RANDBETWEEN: 'Math and trigonometry',
  RANKAVG: 'Statistical',
  RANKEQ: 'Statistical',
  RATE: 'Financial',
  RECEIVED: 'Financial',
  REPLACE: 'Text',
  REPT: 'Text',
  RIGHT: 'Text',
  ROMAN: 'Math and trigonometry',
  ROUND: 'Math and trigonometry',
  ROUNDDOWN: 'Math and trigonometry',
  ROUNDUP: 'Math and trigonometry',
  ROW: 'Lookup and reference',
  ROWS: 'Lookup and reference',
  RRI: 'Financial',
  RSQ: 'Statistical',
  SEARCH: 'Text',
  SEC: 'Math and trigonometry',
  SECH: 'Math and trigonometry',
  SECOND: 'Date and time',
  SERIESSUM: 'Math and trigonometry',
  SIGN: 'Math and trigonometry',
  SIN: 'Math and trigonometry',
  SINH: 'Math and trigonometry',
  SKEW: 'Statistical',
  SKEWP: 'Statistical',
  SLN: 'Financial',
  SLOPE: 'Statistical',
  SMALL: 'Statistical',
  SPLIT: 'Text',
  SQRT: 'Math and trigonometry',
  SQRTPI: 'Math and trigonometry',
  STANDARDIZE: 'Statistical',
  STDEVP: 'Statistical',
  STDEVS: 'Statistical',
  STEYX: 'Statistical',
  SUBSTITUTE: 'Text',
  SUBTOTAL: 'Math and trigonometry',
  SUM: 'Math and trigonometry',
  SUMIF: 'Math and trigonometry',
  SUMIFS: 'Math and trigonometry',
  SUMPRODUCT: 'Math and trigonometry',
  SUMSQ: 'Math and trigonometry',
  SUMX2MY2: 'Math and trigonometry',
  SUMX2PY2: 'Math and trigonometry',
  SUMXMY2: 'Math and trigonometry',
  SWITCH: 'Logical',
  SYD: 'Financial',
  T: 'Text',
  TAN: 'Math and trigonometry',
  TANH: 'Math and trigonometry',
  TBILLEQ: 'Financial',
  TBILLPRICE: 'Financial',
  TBILLYIELD: 'Financial',
  TDIST: 'Statistical',
  TDIST2T: 'Statistical',
  TDISTRT: 'Statistical',
  TEXT: 'Text',
  TIME: 'Date and time',
  TIMEVALUE: 'Date and time',
  TINV: 'Statistical',
  TINV2T: 'Statistical',
  TODAY: 'Date and time',
  TRANSPOSE: 'Lookup and reference',
  TREND: 'Statistical',
  TRIM: 'Text',
  TRIMMEAN: 'Statistical',
  TRUE: 'Logical',
  TRUNC: 'Math and trigonometry',
  UNICHAR: 'Text',
  UNICODE: 'Text',
  UNIQUE: 'Lookup and reference',
  UPPER: 'Text',
  VARP: 'Statistical',
  VARS: 'Statistical',
  VDB: 'Financial',
  VLOOKUP: 'Lookup and reference',
  WEEKDAY: 'Date and time',
  WEEKNUM: 'Date and time',
  WEIBULL: 'Statistical',
  WEIBULLDIST: 'Statistical',
  WORKDAY: 'Date and time',
  WORKDAYINTL: 'Date and time',
  XIRR: 'Financial',
  XNPV: 'Financial',
  XOR: 'Logical',
  YEAR: 'Date and time',
  YEARFRAC: 'Date and time',
  YIELD: 'Financial',
  YIELDDISC: 'Financial',
  YIELDMAT: 'Financial',
  ZTEST: 'Statistical',
};

