// This file is auto-generated by @hey-api/openapi-ts

export const BatchFileTemplateCloneSchemaSchema = {
  properties: {
    clones: {
      items: {
        $ref: '#/components/schemas/FileTemplateCloneSchema',
      },
      type: 'array',
    },
  },
  type: 'object',
  required: ['clones'],
} as const;

export const CloneArgsDynamicFormSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
    },
    digest: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  type: 'object',
  required: ['id'],
} as const;

export const CloneArgsFileSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
    },
    digest: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  type: 'object',
  required: ['id'],
} as const;

export const CloneArgsSchemaSchema = {
  properties: {
    files: {
      items: {
        $ref: '#/components/schemas/CloneArgsFileSchema',
      },
      type: 'array',
    },
    dynamicForms: {
      items: {
        $ref: '#/components/schemas/CloneArgsDynamicFormSchema',
      },
      type: 'array',
    },
  },
  type: 'object',
  required: ['files', 'dynamicForms'],
} as const;

export const ComparisonOperatorsSchema = {
  type: 'string',
  enum: [
    'NONE',
    'EQUAL',
    'NOT_EQUAL',
    'IN',
    'NOT_IN',
    'GREATER_THAN',
    'GREATER_THAN_OR_EQUAL',
    'LESS_THAN',
    'LESS_THAN_OR_EQUAL',
    'BETWEEN',
  ],
} as const;

export const CreateDynamicFormEmbeddingSchemaSchema = {
  properties: {
    templateFormId: {
      type: 'string',
      format: 'uuid4',
    },
    productId: {
      type: 'string',
      format: 'uuid4',
    },
    customCss: {
      type: 'string',
    },
    domains: {
      items: {
        type: 'string',
      },
      type: 'array',
    },
  },
  type: 'object',
  required: ['templateFormId', 'productId', 'customCss', 'domains'],
} as const;

export const CreateEmbeddedDocusignSignatureSchemaSchema = {
  properties: {
    fileId: {
      type: 'string',
      format: 'uuid4',
    },
    digest: {
      type: 'string',
    },
    returnUrl: {
      type: 'string',
    },
    recipients: {
      anyOf: [
        {
          items: {
            $ref: '#/components/schemas/DocusignRecipientSchema',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      default: [],
    },
  },
  type: 'object',
  required: ['fileId', 'digest', 'returnUrl'],
} as const;

export const DependsOnSchema = {
  properties: {
    field: {
      type: 'string',
    },
    operation: {
      $ref: '#/components/schemas/ComparisonOperators',
    },
    value: {
      type: 'string',
    },
  },
  type: 'object',
  required: ['field', 'operation', 'value'],
} as const;

export const DocusignRecipientSchemaSchema = {
  properties: {
    organizationUserId: {
      type: 'string',
      format: 'uuid4',
    },
    email: {
      type: 'string',
    },
    name: {
      type: 'string',
    },
  },
  type: 'object',
  required: ['organizationUserId', 'email', 'name'],
} as const;

export const DynamicFormBaseSchemaSchema = {
  properties: {
    name: {
      type: 'string',
    },
    template: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      default: false,
    },
    submitted: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      default: false,
    },
    submittedBy: {
      anyOf: [
        {
          type: 'string',
          format: 'uuid4',
        },
        {
          type: 'null',
        },
      ],
    },
    formType: {
      $ref: '#/components/schemas/FormTypes',
    },
    formDefinition: {
      items: {
        anyOf: [
          {
            $ref: '#/components/schemas/DynamicFormField-Input',
          },
          {
            $ref: '#/components/schemas/DynamicFormSection-Input',
          },
        ],
      },
      type: 'array',
    },
    formOptions: {
      type: 'object',
      default: {},
    },
    data: {
      anyOf: [
        {
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
    },
    createdAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    updatedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  type: 'object',
  required: ['name', 'formType', 'formDefinition'],
} as const;

export const DynamicFormCreatedSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
    },
    digest: {
      type: 'string',
      readOnly: true,
    },
  },
  type: 'object',
  required: ['id', 'digest'],
} as const;

export const DynamicFormDownloadSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
    },
    digest: {
      type: 'string',
    },
    signatures: {
      anyOf: [
        {
          items: {
            $ref: '#/components/schemas/DynamicFormExportSignatureBlockSchema',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      default: [],
    },
  },
  type: 'object',
  required: ['id', 'digest'],
} as const;

export const DynamicFormEmbeddingCreatedSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
    },
  },
  type: 'object',
  required: ['id'],
} as const;

export const DynamicFormExportSignatureBlockSchemaSchema = {
  properties: {
    userId: {
      type: 'string',
      format: 'uuid4',
    },
    name: {
      type: 'string',
    },
    email: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    phone: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  type: 'object',
  required: ['userId', 'name', 'email', 'phone'],
} as const;

export const DynamicFormField_InputSchema = {
  properties: {
    id: {
      type: 'string',
    },
    name: {
      type: 'string',
    },
    sectionId: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    label: {
      type: 'string',
    },
    fieldType: {
      $ref: '#/components/schemas/FieldTypes',
    },
    parameters: {
      $ref: '#/components/schemas/FieldParameters',
    },
    column: {
      type: 'integer',
      default: 0,
    },
    required: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      default: false,
    },
    value: {
      anyOf: [
        {},
        {
          type: 'null',
        },
      ],
    },
    dependsOn: {
      anyOf: [
        {
          $ref: '#/components/schemas/DependsOn',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  type: 'object',
  required: ['id', 'name', 'label', 'fieldType', 'parameters'],
} as const;

export const DynamicFormField_OutputSchema = {
  properties: {
    id: {
      type: 'string',
    },
    name: {
      type: 'string',
    },
    sectionId: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    label: {
      type: 'string',
    },
    fieldType: {
      $ref: '#/components/schemas/FieldTypes',
    },
    parameters: {
      $ref: '#/components/schemas/FieldParameters',
    },
    column: {
      type: 'integer',
      default: 0,
    },
    required: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      default: false,
    },
    value: {
      anyOf: [
        {},
        {
          type: 'null',
        },
      ],
    },
    dependsOn: {
      anyOf: [
        {
          $ref: '#/components/schemas/DependsOn',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  type: 'object',
  required: ['id', 'name', 'label', 'fieldType', 'parameters'],
} as const;

export const DynamicFormSection_InputSchema = {
  properties: {
    id: {
      type: 'string',
    },
    name: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    layout: {
      $ref: '#/components/schemas/SectionLayouts',
      default: 'ONE_COLUMN',
    },
    fields: {
      items: {
        anyOf: [
          {
            $ref: '#/components/schemas/DynamicFormField-Input',
          },
          {},
        ],
      },
      type: 'array',
    },
    dependsOn: {
      anyOf: [
        {
          $ref: '#/components/schemas/DependsOn',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  type: 'object',
  required: ['id', 'fields'],
} as const;

export const DynamicFormSection_OutputSchema = {
  properties: {
    id: {
      type: 'string',
    },
    name: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    layout: {
      $ref: '#/components/schemas/SectionLayouts',
      default: 'ONE_COLUMN',
    },
    fields: {
      items: {
        anyOf: [
          {
            $ref: '#/components/schemas/DynamicFormField-Output',
          },
          {},
        ],
      },
      type: 'array',
    },
    dependsOn: {
      anyOf: [
        {
          $ref: '#/components/schemas/DependsOn',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  type: 'object',
  required: ['id', 'fields'],
} as const;

export const DynamicFormTemplateBaseSchemaSchema = {
  properties: {
    name: {
      type: 'string',
    },
    template: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      default: true,
    },
    submitted: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      default: false,
    },
    submittedBy: {
      anyOf: [
        {
          type: 'string',
          format: 'uuid4',
        },
        {
          type: 'null',
        },
      ],
    },
    formType: {
      $ref: '#/components/schemas/FormTypes',
    },
    formDefinition: {
      items: {
        anyOf: [
          {
            $ref: '#/components/schemas/DynamicFormField-Input',
          },
          {
            $ref: '#/components/schemas/DynamicFormSection-Input',
          },
        ],
      },
      type: 'array',
    },
    formOptions: {
      type: 'object',
      default: {},
    },
    data: {
      anyOf: [
        {
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
    },
    productCompliance: {
      anyOf: [
        {
          items: {
            type: 'string',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      default: [],
    },
    createdAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    updatedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  type: 'object',
  required: ['name', 'formType', 'formDefinition'],
} as const;

export const DynamicFormTemplateCloneSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
    },
    originalId: {
      type: 'string',
      format: 'uuid4',
    },
    digest: {
      type: 'string',
      readOnly: true,
    },
  },
  type: 'object',
  required: ['id', 'originalId', 'digest'],
} as const;

export const DynamicFormTemplateCreatedSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
    },
  },
  type: 'object',
  required: ['id'],
} as const;

export const EmbeddedDocusignSignatureCreatedSchemaSchema = {
  properties: {
    url: {
      type: 'string',
    },
  },
  type: 'object',
  required: ['url'],
} as const;

export const ExistingDynamicFormSchema_InputSchema = {
  properties: {
    name: {
      type: 'string',
    },
    template: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      default: false,
    },
    submitted: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      default: false,
    },
    submittedBy: {
      anyOf: [
        {
          type: 'string',
          format: 'uuid4',
        },
        {
          type: 'null',
        },
      ],
    },
    formType: {
      $ref: '#/components/schemas/FormTypes',
    },
    formDefinition: {
      items: {
        anyOf: [
          {
            $ref: '#/components/schemas/DynamicFormField-Input',
          },
          {
            $ref: '#/components/schemas/DynamicFormSection-Input',
          },
        ],
      },
      type: 'array',
    },
    formOptions: {
      type: 'object',
      default: {},
    },
    data: {
      anyOf: [
        {
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
    },
    createdAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    updatedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    id: {
      type: 'string',
      format: 'uuid4',
    },
  },
  type: 'object',
  required: ['name', 'formType', 'formDefinition', 'id'],
} as const;

export const ExistingDynamicFormSchema_OutputSchema = {
  properties: {
    name: {
      type: 'string',
    },
    template: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      default: false,
    },
    submitted: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      default: false,
    },
    submittedBy: {
      anyOf: [
        {
          type: 'string',
          format: 'uuid4',
        },
        {
          type: 'null',
        },
      ],
    },
    formType: {
      $ref: '#/components/schemas/FormTypes',
    },
    formDefinition: {
      items: {
        anyOf: [
          {
            $ref: '#/components/schemas/DynamicFormField-Output',
          },
          {
            $ref: '#/components/schemas/DynamicFormSection-Output',
          },
        ],
      },
      type: 'array',
    },
    formOptions: {
      type: 'object',
      default: {},
    },
    data: {
      anyOf: [
        {
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
    },
    createdAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    updatedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    id: {
      type: 'string',
      format: 'uuid4',
    },
    digest: {
      type: 'string',
      readOnly: true,
    },
  },
  type: 'object',
  required: ['name', 'formType', 'formDefinition', 'id', 'digest'],
} as const;

export const ExistingDynamicFormTemplateSchema_InputSchema = {
  properties: {
    name: {
      type: 'string',
    },
    template: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      default: true,
    },
    submitted: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      default: false,
    },
    submittedBy: {
      anyOf: [
        {
          type: 'string',
          format: 'uuid4',
        },
        {
          type: 'null',
        },
      ],
    },
    formType: {
      $ref: '#/components/schemas/FormTypes',
    },
    formDefinition: {
      items: {
        anyOf: [
          {
            $ref: '#/components/schemas/DynamicFormField-Input',
          },
          {
            $ref: '#/components/schemas/DynamicFormSection-Input',
          },
        ],
      },
      type: 'array',
    },
    formOptions: {
      type: 'object',
      default: {},
    },
    data: {
      anyOf: [
        {
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
    },
    productCompliance: {
      anyOf: [
        {
          items: {
            type: 'string',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      default: [],
    },
    createdAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    updatedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    id: {
      type: 'string',
      format: 'uuid4',
    },
  },
  type: 'object',
  required: ['name', 'formType', 'formDefinition', 'id'],
} as const;

export const ExistingDynamicFormTemplateSchema_OutputSchema = {
  properties: {
    name: {
      type: 'string',
    },
    template: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      default: true,
    },
    submitted: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      default: false,
    },
    submittedBy: {
      anyOf: [
        {
          type: 'string',
          format: 'uuid4',
        },
        {
          type: 'null',
        },
      ],
    },
    formType: {
      $ref: '#/components/schemas/FormTypes',
    },
    formDefinition: {
      items: {
        anyOf: [
          {
            $ref: '#/components/schemas/DynamicFormField-Output',
          },
          {
            $ref: '#/components/schemas/DynamicFormSection-Output',
          },
        ],
      },
      type: 'array',
    },
    formOptions: {
      type: 'object',
      default: {},
    },
    data: {
      anyOf: [
        {
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
    },
    productCompliance: {
      anyOf: [
        {
          items: {
            type: 'string',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      default: [],
    },
    createdAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    updatedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    id: {
      type: 'string',
      format: 'uuid4',
    },
  },
  type: 'object',
  required: ['name', 'formType', 'formDefinition', 'id'],
} as const;

export const ExistingFileSchema_InputSchema = {
  properties: {
    template: {
      type: 'boolean',
      default: false,
    },
    fileMetadata: {
      anyOf: [
        {
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      default: {},
    },
    fileType: {
      anyOf: [
        {
          $ref: '#/components/schemas/FileTypes',
        },
        {
          type: 'null',
        },
      ],
      default: 'ANY',
    },
    originalName: {
      type: 'string',
    },
    path: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    createdAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    updatedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    id: {
      type: 'string',
      format: 'uuid4',
    },
    pdfGenerated: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      default: false,
    },
    pdfGeneratedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    thumbnailGenerated: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      default: false,
    },
    thumbnailGeneratedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    pageCount: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    thumbnailUrl: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    pdfUrl: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    originalUrl: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  type: 'object',
  required: ['originalName', 'id'],
} as const;

export const ExistingFileSchema_OutputSchema = {
  properties: {
    template: {
      type: 'boolean',
      default: false,
    },
    fileMetadata: {
      anyOf: [
        {
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      default: {},
    },
    fileType: {
      anyOf: [
        {
          $ref: '#/components/schemas/FileTypes',
        },
        {
          type: 'null',
        },
      ],
      default: 'ANY',
    },
    originalName: {
      type: 'string',
    },
    path: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    createdAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    updatedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    id: {
      type: 'string',
      format: 'uuid4',
    },
    pdfGenerated: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      default: false,
    },
    pdfGeneratedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    thumbnailGenerated: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      default: false,
    },
    thumbnailGeneratedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    pageCount: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    thumbnailUrl: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    pdfUrl: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    originalUrl: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    digest: {
      type: 'string',
      readOnly: true,
    },
  },
  type: 'object',
  required: ['originalName', 'id', 'digest'],
} as const;

export const ExistingFileTemplateSchemaSchema = {
  properties: {
    template: {
      type: 'boolean',
      default: true,
    },
    fileMetadata: {
      anyOf: [
        {
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      default: {},
    },
    fileType: {
      anyOf: [
        {
          $ref: '#/components/schemas/FileTypes',
        },
        {
          type: 'null',
        },
      ],
      default: 'ANY',
    },
    originalName: {
      type: 'string',
    },
    path: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    createdAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    updatedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    id: {
      type: 'string',
      format: 'uuid4',
    },
    pdfGenerated: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      default: false,
    },
    pdfGeneratedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    thumbnailGenerated: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      default: false,
    },
    thumbnailGeneratedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    pageCount: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    thumbnailUrl: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    pdfUrl: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    originalUrl: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  type: 'object',
  required: ['originalName', 'id'],
} as const;

export const ExistingFormEmbeddingSchemaSchema = {
  properties: {
    templateFormId: {
      type: 'string',
      format: 'uuid4',
    },
    productId: {
      type: 'string',
      format: 'uuid4',
    },
    customCss: {
      type: 'string',
    },
    domains: {
      items: {
        type: 'string',
      },
      type: 'array',
    },
    id: {
      type: 'string',
      format: 'uuid4',
    },
    form: {
      $ref: '#/components/schemas/ExistingDynamicFormSchema-Output',
    },
    nonce: {
      type: 'string',
      readOnly: true,
    },
  },
  type: 'object',
  required: [
    'templateFormId',
    'productId',
    'customCss',
    'domains',
    'id',
    'form',
    'nonce',
  ],
} as const;

export const ExistingFormEmbeddingSchemaWithCsrfTokenSchema = {
  properties: {
    templateFormId: {
      type: 'string',
      format: 'uuid4',
    },
    productId: {
      type: 'string',
      format: 'uuid4',
    },
    customCss: {
      type: 'string',
    },
    domains: {
      items: {
        type: 'string',
      },
      type: 'array',
    },
    id: {
      type: 'string',
      format: 'uuid4',
    },
    form: {
      $ref: '#/components/schemas/ExistingDynamicFormSchema-Output',
    },
    csrfToken: {
      type: 'string',
    },
    nonce: {
      type: 'string',
      readOnly: true,
    },
  },
  type: 'object',
  required: [
    'templateFormId',
    'productId',
    'customCss',
    'domains',
    'id',
    'form',
    'csrfToken',
    'nonce',
  ],
} as const;

export const ExistingSignatureSchemaSchema = {
  properties: {
    targetId: {
      type: 'string',
      format: 'uuid4',
    },
    targetType: {
      $ref: '#/components/schemas/SignatureTargets',
    },
    signatoryId: {
      type: 'string',
      format: 'uuid4',
    },
    signatoryType: {
      $ref: '#/components/schemas/SignatoryTypes',
    },
    signature: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    signatureDate: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    id: {
      type: 'string',
      format: 'uuid4',
    },
    digest: {
      type: 'string',
      readOnly: true,
    },
  },
  type: 'object',
  required: [
    'targetId',
    'targetType',
    'signatoryId',
    'signatoryType',
    'id',
    'digest',
  ],
} as const;

export const FieldOptionSchema = {
  properties: {
    label: {
      type: 'string',
    },
    value: {
      type: 'string',
    },
    description: {
      type: 'string',
    },
  },
  type: 'object',
  required: ['label', 'value', 'description'],
} as const;

export const FieldParametersSchema = {
  properties: {
    options: {
      anyOf: [
        {
          items: {
            $ref: '#/components/schemas/FieldOption',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
    },
    decimalPrecision: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    minimumLength: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    maximumLength: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    minimumValue: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    maximumValue: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    type: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    placeholder: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    validator: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  type: 'object',
  required: [
    'decimalPrecision',
    'minimumLength',
    'maximumLength',
    'minimumValue',
    'maximumValue',
    'type',
    'placeholder',
    'validator',
  ],
} as const;

export const FieldTypesSchema = {
  type: 'string',
  enum: [
    'INPUT',
    'DATE',
    'TEXT',
    'MONEY',
    'NUMBER',
    'RADIO',
    'SELECT',
    'CHECKBOX',
    'LOAN_INFORMATION',
    'LOAN_PURPOSE',
    'LOAN_SOURCES',
    'BORROWERS',
    'CREDIT_CHECK',
    'DISCLAIMER',
    'QUESTIONNAIRE',
    'SUBMIT_BUTTON',
    'FILE_UPLOAD',
    'CROP_DETAILS',
    'USE_OF_FUNDS',
    'LIVESTOCK',
  ],
} as const;

export const FileBaseSchemaSchema = {
  properties: {
    template: {
      type: 'boolean',
      default: false,
    },
    fileMetadata: {
      anyOf: [
        {
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      default: {},
    },
    fileType: {
      anyOf: [
        {
          $ref: '#/components/schemas/FileTypes',
        },
        {
          type: 'null',
        },
      ],
      default: 'ANY',
    },
    originalName: {
      type: 'string',
    },
    path: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    createdAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    updatedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  type: 'object',
  required: ['originalName'],
} as const;

export const FileCloneArgsSchemaSchema = {
  properties: {
    filesToClone: {
      items: {
        $ref: '#/components/schemas/CloneArgsFileSchema',
      },
      type: 'array',
    },
  },
  type: 'object',
  required: ['filesToClone'],
} as const;

export const FileCreatedSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
    },
    originalName: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    digest: {
      type: 'string',
      readOnly: true,
    },
  },
  type: 'object',
  required: ['id', 'digest'],
} as const;

export const FilePatchSchemaSchema = {
  properties: {
    pdfMetadata: {
      anyOf: [
        {
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      default: {},
    },
  },
  type: 'object',
} as const;

export const FileTemplateBaseSchemaSchema = {
  properties: {
    template: {
      type: 'boolean',
      default: true,
    },
    fileMetadata: {
      anyOf: [
        {
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      default: {},
    },
    fileType: {
      anyOf: [
        {
          $ref: '#/components/schemas/FileTypes',
        },
        {
          type: 'null',
        },
      ],
      default: 'ANY',
    },
    originalName: {
      type: 'string',
    },
    path: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    createdAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    updatedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  type: 'object',
  required: ['originalName'],
} as const;

export const FileTemplateCloneSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
    },
    originalName: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    originalId: {
      type: 'string',
      format: 'uuid4',
    },
    digest: {
      type: 'string',
      readOnly: true,
    },
  },
  type: 'object',
  required: ['id', 'originalId', 'digest'],
} as const;

export const FileTemplateCreatedSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
    },
    originalName: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  type: 'object',
  required: ['id'],
} as const;

export const FileTypesSchema = {
  type: 'string',
  enum: ['WORD', 'EXCEL', 'PDF', 'IMAGE', 'ARCHIVE', 'ANY'],
} as const;

export const FormTypesSchema = {
  type: 'string',
  enum: ['INLINE', 'TABS', 'STEPS'],
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: '#/components/schemas/ValidationError',
      },
      type: 'array',
    },
  },
  type: 'object',
} as const;

export const LLMInputSchema = {
  properties: {
    conversationId: {
      type: 'string',
      format: 'uuid4',
    },
    prompt: {
      type: 'string',
    },
  },
  type: 'object',
  required: ['conversationId', 'prompt'],
} as const;

export const LLMOutputSchema = {
  properties: {
    conversationId: {
      type: 'string',
      format: 'uuid4',
    },
    prompt: {
      type: 'string',
    },
    response: {},
  },
  type: 'object',
  required: ['conversationId', 'prompt', 'response'],
} as const;

export const MultipleDynamicFormsDownloadSchemaSchema = {
  properties: {
    forms: {
      items: {
        $ref: '#/components/schemas/DynamicFormDownloadSchema',
      },
      type: 'array',
    },
    signatures: {
      anyOf: [
        {
          items: {
            $ref: '#/components/schemas/DynamicFormExportSignatureBlockSchema',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      default: [],
    },
  },
  type: 'object',
  required: ['forms'],
} as const;

export const SectionLayoutsSchema = {
  type: 'string',
  enum: ['ONE_COLUMN', 'TWO_COLUMNS', 'THREE_COLUMNS'],
} as const;

export const SignatoryTypesSchema = {
  type: 'string',
  enum: ['USER', 'GROUP'],
} as const;

export const SignatureBaseSchemaSchema = {
  properties: {
    targetId: {
      type: 'string',
      format: 'uuid4',
    },
    targetType: {
      $ref: '#/components/schemas/SignatureTargets',
    },
    signatoryId: {
      type: 'string',
      format: 'uuid4',
    },
    signatoryType: {
      $ref: '#/components/schemas/SignatoryTypes',
    },
    signature: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    signatureDate: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  type: 'object',
  required: ['targetId', 'targetType', 'signatoryId', 'signatoryType'],
} as const;

export const SignatureCreatedSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
    },
  },
  type: 'object',
  required: ['id'],
} as const;

export const SignatureTargetsSchema = {
  type: 'string',
  enum: ['APPLICATION', 'REQUEST', 'DOCUMENT', 'FILE', 'DYNAMIC_FORM'],
} as const;

export const TemplateClonesSchemaSchema = {
  properties: {
    files: {
      items: {
        $ref: '#/components/schemas/FileTemplateCloneSchema',
      },
      type: 'array',
    },
    dynamicForms: {
      items: {
        $ref: '#/components/schemas/DynamicFormTemplateCloneSchema',
      },
      type: 'array',
    },
  },
  type: 'object',
  required: ['files', 'dynamicForms'],
} as const;

export const TenantDBArgsSchema = {
  properties: {
    databaseName: {
      type: 'string',
    },
  },
  type: 'object',
  required: ['databaseName'],
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: 'string',
          },
          {
            type: 'integer',
          },
        ],
      },
      type: 'array',
    },
    msg: {
      type: 'string',
    },
    type: {
      type: 'string',
    },
  },
  type: 'object',
  required: ['loc', 'msg', 'type'],
} as const;
