// This file is auto-generated by @hey-api/openapi-ts

import type {
  Options as ClientOptions,
  TDataShape,
  Client,
} from '@hey-api/client-fetch';
import type {
  CreateFileMetadataFilesPostData,
  CreateFileMetadataFilesPostResponse,
  CreateFileMetadataFilesPostError,
  CloneTemplateBatchFilesCloneBatchPostData,
  CloneTemplateBatchFilesCloneBatchPostResponse,
  CloneTemplateBatchFilesCloneBatchPostError,
  CreateBatchFileMetadataFilesBatchPostData,
  CreateBatchFileMetadataFilesBatchPostResponse,
  CreateBatchFileMetadataFilesBatchPostError,
  DeleteFileMetadataFilesFileIdDeleteData,
  DeleteFileMetadataFilesFileIdDeleteError,
  GetFileMetadataFilesFileIdGetData,
  GetFileMetadataFilesFileIdGetResponse,
  GetFileMetadataFilesFileIdGetError,
  GetHeadFileMetadataFilesFileIdHeadData,
  GetHeadFileMetadataFilesFileIdHeadResponse,
  GetHeadFileMetadataFilesFileIdHeadError,
  PatchFileMetadataFilesFileIdPatchData,
  PatchFileMetadataFilesFileIdPatchError,
  UpdateFileMetadataFilesFileIdPutData,
  UpdateFileMetadataFilesFileIdPutError,
  PostUploadFileFilesFileIdUploadPostData,
  PostUploadFileFilesFileIdUploadPostError,
  PutUploadFileFilesFileIdUploadPutData,
  PutUploadFileFilesFileIdUploadPutError,
  DownloadFileFilesFileIdDownloadGetData,
  DownloadFileFilesFileIdDownloadGetError,
  TriggerConversionFilesFileIdConvertPostData,
  TriggerConversionFilesFileIdConvertPostError,
  CreateFormFormsPostData,
  CreateFormFormsPostResponse,
  CreateFormFormsPostError,
  DeleteFormFormsDynamicFormIdDeleteData,
  DeleteFormFormsDynamicFormIdDeleteError,
  GetFormFormsDynamicFormIdGetData,
  GetFormFormsDynamicFormIdGetResponse,
  GetFormFormsDynamicFormIdGetError,
  UpdateFormFormsDynamicFormIdPutData,
  UpdateFormFormsDynamicFormIdPutError,
  DownloadMultipleFormsFormsDownloadBatchPostData,
  DownloadMultipleFormsFormsDownloadBatchPostError,
  DownloadFormFormsDynamicFormIdDownloadGetData,
  DownloadFormFormsDynamicFormIdDownloadGetError,
  SearchSearchGetData,
  CreateSignatureSignaturesPostData,
  CreateSignatureSignaturesPostResponse,
  CreateSignatureSignaturesPostError,
  DeleteSignatureSignaturesSignatureIdDeleteData,
  DeleteSignatureSignaturesSignatureIdDeleteError,
  GetSignatureSignaturesSignatureIdGetData,
  GetSignatureSignaturesSignatureIdGetResponse,
  GetSignatureSignaturesSignatureIdGetError,
  CreateEnveloppeFromFileIdSignaturesExternalDocusignPostData,
  CreateEnveloppeFromFileIdSignaturesExternalDocusignPostResponse,
  CreateEnveloppeFromFileIdSignaturesExternalDocusignPostError,
  GetAllTemplateMetadataTemplatesFilesGetData,
  GetAllTemplateMetadataTemplatesFilesGetResponse,
  CreateTemplateMetadataTemplatesFilesPostData,
  CreateTemplateMetadataTemplatesFilesPostResponse,
  CreateTemplateMetadataTemplatesFilesPostError,
  CreateBatchFileTemplateTemplatesFilesBatchPostData,
  CreateBatchFileTemplateTemplatesFilesBatchPostResponse,
  CreateBatchFileTemplateTemplatesFilesBatchPostError,
  DeleteTemplateMetadataTemplatesFilesTemplateIdDeleteData,
  DeleteTemplateMetadataTemplatesFilesTemplateIdDeleteError,
  GetTemplateMetadataTemplatesFilesTemplateIdGetData,
  GetTemplateMetadataTemplatesFilesTemplateIdGetResponse,
  GetTemplateMetadataTemplatesFilesTemplateIdGetError,
  UpdateTemplateMetadataTemplatesFilesTemplateIdPutData,
  UpdateTemplateMetadataTemplatesFilesTemplateIdPutError,
  PostUploadTemplateTemplatesFilesTemplateIdUploadPostData,
  PostUploadTemplateTemplatesFilesTemplateIdUploadPostError,
  PutUploadTemplateTemplatesFilesTemplateIdUploadPutData,
  PutUploadTemplateTemplatesFilesTemplateIdUploadPutError,
  DownloadTemplateTemplatesFilesTemplateIdDownloadGetData,
  DownloadTemplateTemplatesFilesTemplateIdDownloadGetError,
  CloneTemplateTemplatesFilesTemplateIdClonePostData,
  CloneTemplateTemplatesFilesTemplateIdClonePostResponse,
  CloneTemplateTemplatesFilesTemplateIdClonePostError,
  CloneTemplateBatchTemplatesFilesCloneBatchPostData,
  CloneTemplateBatchTemplatesFilesCloneBatchPostResponse,
  CloneTemplateBatchTemplatesFilesCloneBatchPostError,
  TriggerConversionTemplatesFilesTemplateIdConvertPostData,
  TriggerConversionTemplatesFilesTemplateIdConvertPostError,
  GetAllFormTemplatesTemplatesFormsGetData,
  GetAllFormTemplatesTemplatesFormsGetResponse,
  CreateFormTemplateTemplatesFormsPostData,
  CreateFormTemplateTemplatesFormsPostResponse,
  CreateFormTemplateTemplatesFormsPostError,
  DeleteFormTemplateTemplatesFormsTemplateIdDeleteData,
  DeleteFormTemplateTemplatesFormsTemplateIdDeleteError,
  GetFormTemplateTemplatesFormsTemplateIdGetData,
  GetFormTemplateTemplatesFormsTemplateIdGetResponse,
  GetFormTemplateTemplatesFormsTemplateIdGetError,
  UpdateFormTemplateTemplatesFormsTemplateIdPutData,
  UpdateFormTemplateTemplatesFormsTemplateIdPutError,
  CloneDynamicFormTemplateTemplatesFormsTemplateIdClonePostData,
  CloneDynamicFormTemplateTemplatesFormsTemplateIdClonePostResponse,
  CloneDynamicFormTemplateTemplatesFormsTemplateIdClonePostError,
  GetEmbeddingFormsExternalFormsGetData,
  GetEmbeddingFormsExternalFormsGetResponse,
  GetEmbeddingFormsExternalFormsGetError,
  CreateEmbeddingFormExternalFormsPostData,
  CreateEmbeddingFormExternalFormsPostResponse,
  CreateEmbeddingFormExternalFormsPostError,
  DeleteEmbeddingFormExternalFormsEmbeddingFormIdDeleteData,
  DeleteEmbeddingFormExternalFormsEmbeddingFormIdDeleteError,
  GetEmbeddingFormExternalFormsEmbeddingFormIdGetData,
  GetEmbeddingFormExternalFormsEmbeddingFormIdGetResponse,
  GetEmbeddingFormExternalFormsEmbeddingFormIdGetError,
  UpdateEmbeddingFormExternalFormsEmbeddingFormIdPutData,
  UpdateEmbeddingFormExternalFormsEmbeddingFormIdPutResponse,
  UpdateEmbeddingFormExternalFormsEmbeddingFormIdPutError,
  GetFormEmbeddingExternalFormsDefinitionEmbeddingFormIdGetData,
  GetFormEmbeddingExternalFormsDefinitionEmbeddingFormIdGetResponse,
  GetFormEmbeddingExternalFormsDefinitionEmbeddingFormIdGetError,
  GetFormEmbedScriptExternalFormsEmbeddingFormIdFormJsGetData,
  GetFormEmbedScriptExternalFormsEmbeddingFormIdFormJsGetError,
  CreateFormExternalFormsSubmitPostData,
  CreateFormExternalFormsSubmitPostResponse,
  CreateFormExternalFormsSubmitPostError,
  CreateDocumentDescriptionDocumentAnalysisDocumentIdPostData,
  CreateDocumentDescriptionDocumentAnalysisDocumentIdPostError,
  ApiConverseConversationFilesFileIdLlmPostData,
  ApiConverseConversationFilesFileIdLlmPostResponse,
  ApiConverseConversationFilesFileIdLlmPostError,
  CloneTemplateBatchCloneBatchPostData,
  CloneTemplateBatchCloneBatchPostResponse,
  CloneTemplateBatchCloneBatchPostError,
  InitializeTenantTenantsDatabasePostData,
  InitializeTenantTenantsDatabasePostError,
  RefreshSettingsCacheTenantsRefreshSettingsCachePostData,
  GetRootGetData,
  GetStatusCheckStatusGetData,
} from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Create File Metadata
 * Create a new document metadata object.That object is not the file itself but information about the file.After creating that object, you need to post a request on the /upload path.
 */
export const createFileMetadataFilesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateFileMetadataFilesPostData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateFileMetadataFilesPostResponse,
    CreateFileMetadataFilesPostError,
    ThrowOnError
  >({
    url: '/files',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Clone Template Batch
 * Clone a batch template to a new file.
 */
export const cloneTemplateBatchFilesCloneBatchPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CloneTemplateBatchFilesCloneBatchPostData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CloneTemplateBatchFilesCloneBatchPostResponse,
    CloneTemplateBatchFilesCloneBatchPostError,
    ThrowOnError
  >({
    url: '/files/clone/batch',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Create Batch File Metadata
 * Batch create of documents metadata object.That object is not the file itself but information about the file.After creating that object, you need to post a request on the /upload path.
 */
export const createBatchFileMetadataFilesBatchPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateBatchFileMetadataFilesBatchPostData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateBatchFileMetadataFilesBatchPostResponse,
    CreateBatchFileMetadataFilesBatchPostError,
    ThrowOnError
  >({
    url: '/files/batch',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete File Metadata
 * Delete a specific file metadata
 */
export const deleteFileMetadataFilesFileIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteFileMetadataFilesFileIdDeleteData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    unknown,
    DeleteFileMetadataFilesFileIdDeleteError,
    ThrowOnError
  >({
    url: '/files/{file_id}',
    ...options,
  });
};

/**
 * Get File Metadata
 * Get a specific file metadata or a batch
 */
export const getFileMetadataFilesFileIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetFileMetadataFilesFileIdGetData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetFileMetadataFilesFileIdGetResponse,
    GetFileMetadataFilesFileIdGetError,
    ThrowOnError
  >({
    url: '/files/{file_id}',
    ...options,
  });
};

/**
 * Get Head File Metadata
 * Get a specific file metadata
 */
export const getHeadFileMetadataFilesFileIdHead = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetHeadFileMetadataFilesFileIdHeadData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).head<
    GetHeadFileMetadataFilesFileIdHeadResponse,
    GetHeadFileMetadataFilesFileIdHeadError,
    ThrowOnError
  >({
    url: '/files/{file_id}',
    ...options,
  });
};

/**
 * Patch File Metadata
 * Update a specific file metadata
 */
export const patchFileMetadataFilesFileIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchFileMetadataFilesFileIdPatchData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    unknown,
    PatchFileMetadataFilesFileIdPatchError,
    ThrowOnError
  >({
    url: '/files/{file_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Update File Metadata
 * Update a specific file metadata
 */
export const updateFileMetadataFilesFileIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateFileMetadataFilesFileIdPutData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    unknown,
    UpdateFileMetadataFilesFileIdPutError,
    ThrowOnError
  >({
    url: '/files/{file_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Post Upload File
 * Get the upload link for a post request
 */
export const postUploadFileFilesFileIdUploadPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostUploadFileFilesFileIdUploadPostData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    unknown,
    PostUploadFileFilesFileIdUploadPostError,
    ThrowOnError
  >({
    url: '/files/{file_id}/upload',
    ...options,
  });
};

/**
 * Put Upload File
 * Get the upload link for a put request
 */
export const putUploadFileFilesFileIdUploadPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutUploadFileFilesFileIdUploadPutData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    unknown,
    PutUploadFileFilesFileIdUploadPutError,
    ThrowOnError
  >({
    url: '/files/{file_id}/upload',
    ...options,
  });
};

/**
 * Download File
 * Get the download link for a file
 */
export const downloadFileFilesFileIdDownloadGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DownloadFileFilesFileIdDownloadGetData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    unknown,
    DownloadFileFilesFileIdDownloadGetError,
    ThrowOnError
  >({
    url: '/files/{file_id}/download',
    ...options,
  });
};

/**
 * Trigger Conversion
 * Trigger the conversion of a file to PDF format.
 */
export const triggerConversionFilesFileIdConvertPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TriggerConversionFilesFileIdConvertPostData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    unknown,
    TriggerConversionFilesFileIdConvertPostError,
    ThrowOnError
  >({
    url: '/files/{file_id}/convert',
    ...options,
  });
};

/**
 * Create Form
 * Create a new dynamic form object.
 */
export const createFormFormsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateFormFormsPostData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateFormFormsPostResponse,
    CreateFormFormsPostError,
    ThrowOnError
  >({
    url: '/forms',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete Form
 * Delete a dynamic form, including the model and the data.
 */
export const deleteFormFormsDynamicFormIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteFormFormsDynamicFormIdDeleteData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    unknown,
    DeleteFormFormsDynamicFormIdDeleteError,
    ThrowOnError
  >({
    url: '/forms/{dynamic_form_id}',
    ...options,
  });
};

/**
 * Get Form
 * Get a dynamic form (definition and data).
 */
export const getFormFormsDynamicFormIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetFormFormsDynamicFormIdGetData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetFormFormsDynamicFormIdGetResponse,
    GetFormFormsDynamicFormIdGetError,
    ThrowOnError
  >({
    url: '/forms/{dynamic_form_id}',
    ...options,
  });
};

/**
 * Update Form
 * Update the definition and the model of a dynamic form.To update only a field of the model, consider implementing a patch...
 */
export const updateFormFormsDynamicFormIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateFormFormsDynamicFormIdPutData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    unknown,
    UpdateFormFormsDynamicFormIdPutError,
    ThrowOnError
  >({
    url: '/forms/{dynamic_form_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Download Multiple Forms
 * Downloads multiple dynamic forms .
 */
export const downloadMultipleFormsFormsDownloadBatchPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DownloadMultipleFormsFormsDownloadBatchPostData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).post<
    unknown,
    DownloadMultipleFormsFormsDownloadBatchPostError,
    ThrowOnError
  >({
    url: '/forms/download/batch',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Download Form
 * Downloads the dynamic form as a PDF.
 */
export const downloadFormFormsDynamicFormIdDownloadGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DownloadFormFormsDynamicFormIdDownloadGetData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    unknown,
    DownloadFormFormsDynamicFormIdDownloadGetError,
    ThrowOnError
  >({
    url: '/forms/{dynamic_form_id}/download',
    ...options,
  });
};

/**
 * Search
 * Search documents
 */
export const searchSearchGet = <ThrowOnError extends boolean = false>(
  options?: Options<SearchSearchGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>(
    {
      url: '/search/',
      ...options,
    }
  );
};

/**
 * Create Signature
 * Create a new signature.
 */
export const createSignatureSignaturesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateSignatureSignaturesPostData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateSignatureSignaturesPostResponse,
    CreateSignatureSignaturesPostError,
    ThrowOnError
  >({
    url: '/signatures',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete Signature
 * Delete a signature.
 */
export const deleteSignatureSignaturesSignatureIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteSignatureSignaturesSignatureIdDeleteData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    unknown,
    DeleteSignatureSignaturesSignatureIdDeleteError,
    ThrowOnError
  >({
    url: '/signatures/{signature_id}',
    ...options,
  });
};

/**
 * Get Signature
 * Get a signature.
 */
export const getSignatureSignaturesSignatureIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetSignatureSignaturesSignatureIdGetData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetSignatureSignaturesSignatureIdGetResponse,
    GetSignatureSignaturesSignatureIdGetError,
    ThrowOnError
  >({
    url: '/signatures/{signature_id}',
    ...options,
  });
};

/**
 * Create Enveloppe From File Id
 * Create a new embedded docusign signature enveloppe.
 */
export const createEnveloppeFromFileIdSignaturesExternalDocusignPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateEnveloppeFromFileIdSignaturesExternalDocusignPostData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).post<
    CreateEnveloppeFromFileIdSignaturesExternalDocusignPostResponse,
    CreateEnveloppeFromFileIdSignaturesExternalDocusignPostError,
    ThrowOnError
  >({
    url: '/signatures/external/docusign',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Get All Template Metadata
 * return a list of all file template metadata
 */
export const getAllTemplateMetadataTemplatesFilesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetAllTemplateMetadataTemplatesFilesGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetAllTemplateMetadataTemplatesFilesGetResponse,
    unknown,
    ThrowOnError
  >({
    url: '/templates/files',
    ...options,
  });
};

/**
 * Create Template Metadata
 * Create a new template metadata object.That object is not the file template itself but information about the template.After creating that object, you need to post a request on the /upload path.
 */
export const createTemplateMetadataTemplatesFilesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateTemplateMetadataTemplatesFilesPostData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateTemplateMetadataTemplatesFilesPostResponse,
    CreateTemplateMetadataTemplatesFilesPostError,
    ThrowOnError
  >({
    url: '/templates/files',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Create Batch File Template
 * Batch create of file template documents metadata object.That object is not the file itself but information about the file.After creating that object, you need to post a request on the /upload path.
 */
export const createBatchFileTemplateTemplatesFilesBatchPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateBatchFileTemplateTemplatesFilesBatchPostData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).post<
    CreateBatchFileTemplateTemplatesFilesBatchPostResponse,
    CreateBatchFileTemplateTemplatesFilesBatchPostError,
    ThrowOnError
  >({
    url: '/templates/files/batch',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete Template Metadata
 * Delete a specific file template metadata
 */
export const deleteTemplateMetadataTemplatesFilesTemplateIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteTemplateMetadataTemplatesFilesTemplateIdDeleteData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).delete<
    unknown,
    DeleteTemplateMetadataTemplatesFilesTemplateIdDeleteError,
    ThrowOnError
  >({
    url: '/templates/files/{template_id}',
    ...options,
  });
};

/**
 * Get Template Metadata
 * Return an existing file template metadata
 */
export const getTemplateMetadataTemplatesFilesTemplateIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetTemplateMetadataTemplatesFilesTemplateIdGetData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).get<
    GetTemplateMetadataTemplatesFilesTemplateIdGetResponse,
    GetTemplateMetadataTemplatesFilesTemplateIdGetError,
    ThrowOnError
  >({
    url: '/templates/files/{template_id}',
    ...options,
  });
};

/**
 * Update Template Metadata
 * Update a specific file template metadata
 */
export const updateTemplateMetadataTemplatesFilesTemplateIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateTemplateMetadataTemplatesFilesTemplateIdPutData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).put<
    unknown,
    UpdateTemplateMetadataTemplatesFilesTemplateIdPutError,
    ThrowOnError
  >({
    url: '/templates/files/{template_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Post Upload Template
 * Get the upload link for a post request
 */
export const postUploadTemplateTemplatesFilesTemplateIdUploadPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PostUploadTemplateTemplatesFilesTemplateIdUploadPostData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).post<
    unknown,
    PostUploadTemplateTemplatesFilesTemplateIdUploadPostError,
    ThrowOnError
  >({
    url: '/templates/files/{template_id}/upload',
    ...options,
  });
};

/**
 * Put Upload Template
 * Get the upload link for a put request
 */
export const putUploadTemplateTemplatesFilesTemplateIdUploadPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PutUploadTemplateTemplatesFilesTemplateIdUploadPutData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).put<
    unknown,
    PutUploadTemplateTemplatesFilesTemplateIdUploadPutError,
    ThrowOnError
  >({
    url: '/templates/files/{template_id}/upload',
    ...options,
  });
};

/**
 * Download Template
 * Get the download link for a template
 */
export const downloadTemplateTemplatesFilesTemplateIdDownloadGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DownloadTemplateTemplatesFilesTemplateIdDownloadGetData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).get<
    unknown,
    DownloadTemplateTemplatesFilesTemplateIdDownloadGetError,
    ThrowOnError
  >({
    url: '/templates/files/{template_id}/download',
    ...options,
  });
};

/**
 * Clone Template
 * Clone a template to a new file.
 */
export const cloneTemplateTemplatesFilesTemplateIdClonePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CloneTemplateTemplatesFilesTemplateIdClonePostData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).post<
    CloneTemplateTemplatesFilesTemplateIdClonePostResponse,
    CloneTemplateTemplatesFilesTemplateIdClonePostError,
    ThrowOnError
  >({
    url: '/templates/files/{template_id}/clone',
    ...options,
  });
};

/**
 * Clone Template Batch
 * Clone a batch template to a new file.
 */
export const cloneTemplateBatchTemplatesFilesCloneBatchPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CloneTemplateBatchTemplatesFilesCloneBatchPostData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).post<
    CloneTemplateBatchTemplatesFilesCloneBatchPostResponse,
    CloneTemplateBatchTemplatesFilesCloneBatchPostError,
    ThrowOnError
  >({
    url: '/templates/files/clone/batch',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Trigger Conversion
 * Trigger the conversion of a file to PDF format.
 */
export const triggerConversionTemplatesFilesTemplateIdConvertPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    TriggerConversionTemplatesFilesTemplateIdConvertPostData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).post<
    unknown,
    TriggerConversionTemplatesFilesTemplateIdConvertPostError,
    ThrowOnError
  >({
    url: '/templates/files/{template_id}/convert',
    ...options,
  });
};

/**
 * Get All Form Templates
 * return a list of all dynamic form template
 */
export const getAllFormTemplatesTemplatesFormsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetAllFormTemplatesTemplatesFormsGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetAllFormTemplatesTemplatesFormsGetResponse,
    unknown,
    ThrowOnError
  >({
    url: '/templates/forms',
    ...options,
  });
};

/**
 * Create Form Template
 * Create a new dynamic form template object.
 */
export const createFormTemplateTemplatesFormsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateFormTemplateTemplatesFormsPostData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateFormTemplateTemplatesFormsPostResponse,
    CreateFormTemplateTemplatesFormsPostError,
    ThrowOnError
  >({
    url: '/templates/forms',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete Form Template
 * Delete a specific dynamic form template
 */
export const deleteFormTemplateTemplatesFormsTemplateIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteFormTemplateTemplatesFormsTemplateIdDeleteData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).delete<
    unknown,
    DeleteFormTemplateTemplatesFormsTemplateIdDeleteError,
    ThrowOnError
  >({
    url: '/templates/forms/{template_id}',
    ...options,
  });
};

/**
 * Get Form Template
 * Return an existing dynamic form template
 */
export const getFormTemplateTemplatesFormsTemplateIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetFormTemplateTemplatesFormsTemplateIdGetData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetFormTemplateTemplatesFormsTemplateIdGetResponse,
    GetFormTemplateTemplatesFormsTemplateIdGetError,
    ThrowOnError
  >({
    url: '/templates/forms/{template_id}',
    ...options,
  });
};

/**
 * Update Form Template
 * Update a specific dynamic form template
 */
export const updateFormTemplateTemplatesFormsTemplateIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateFormTemplateTemplatesFormsTemplateIdPutData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).put<
    unknown,
    UpdateFormTemplateTemplatesFormsTemplateIdPutError,
    ThrowOnError
  >({
    url: '/templates/forms/{template_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Clone Dynamic Form Template
 * Clone a template to a new file.
 */
export const cloneDynamicFormTemplateTemplatesFormsTemplateIdClonePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CloneDynamicFormTemplateTemplatesFormsTemplateIdClonePostData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).post<
    CloneDynamicFormTemplateTemplatesFormsTemplateIdClonePostResponse,
    CloneDynamicFormTemplateTemplatesFormsTemplateIdClonePostError,
    ThrowOnError
  >({
    url: '/templates/forms/{template_id}/clone',
    ...options,
  });
};

/**
 * Get Embedding Forms
 * Get a list embeddings form (definition and data).
 */
export const getEmbeddingFormsExternalFormsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetEmbeddingFormsExternalFormsGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetEmbeddingFormsExternalFormsGetResponse,
    GetEmbeddingFormsExternalFormsGetError,
    ThrowOnError
  >({
    url: '/external/forms',
    ...options,
  });
};

/**
 * Create Embedding Form
 * Create a new dynamic form embedding object.
 */
export const createEmbeddingFormExternalFormsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateEmbeddingFormExternalFormsPostData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateEmbeddingFormExternalFormsPostResponse,
    CreateEmbeddingFormExternalFormsPostError,
    ThrowOnError
  >({
    url: '/external/forms',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete Embedding Form
 * Deletes a dynamic form embedding object.
 */
export const deleteEmbeddingFormExternalFormsEmbeddingFormIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteEmbeddingFormExternalFormsEmbeddingFormIdDeleteData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).delete<
    unknown,
    DeleteEmbeddingFormExternalFormsEmbeddingFormIdDeleteError,
    ThrowOnError
  >({
    url: '/external/forms/{embedding_form_id}',
    ...options,
  });
};

/**
 * Get Embedding Form
 * Get an embeddings form (definition and data).
 */
export const getEmbeddingFormExternalFormsEmbeddingFormIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetEmbeddingFormExternalFormsEmbeddingFormIdGetData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).get<
    GetEmbeddingFormExternalFormsEmbeddingFormIdGetResponse,
    GetEmbeddingFormExternalFormsEmbeddingFormIdGetError,
    ThrowOnError
  >({
    url: '/external/forms/{embedding_form_id}',
    ...options,
  });
};

/**
 * Update Embedding Form
 * Updates a dynamic form embedding object.
 */
export const updateEmbeddingFormExternalFormsEmbeddingFormIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateEmbeddingFormExternalFormsEmbeddingFormIdPutData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).put<
    UpdateEmbeddingFormExternalFormsEmbeddingFormIdPutResponse,
    UpdateEmbeddingFormExternalFormsEmbeddingFormIdPutError,
    ThrowOnError
  >({
    url: '/external/forms/{embedding_form_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Get Form Embedding
 * Get a form embedding (unauthenticated).
 */
export const getFormEmbeddingExternalFormsDefinitionEmbeddingFormIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetFormEmbeddingExternalFormsDefinitionEmbeddingFormIdGetData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).get<
    GetFormEmbeddingExternalFormsDefinitionEmbeddingFormIdGetResponse,
    GetFormEmbeddingExternalFormsDefinitionEmbeddingFormIdGetError,
    ThrowOnError
  >({
    url: '/external/forms/definition/{embedding_form_id}',
    ...options,
  });
};

/**
 * Get Form Embed Script
 * Return an existing dynamic form template embed script
 */
export const getFormEmbedScriptExternalFormsEmbeddingFormIdFormJsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetFormEmbedScriptExternalFormsEmbeddingFormIdFormJsGetData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).get<
    unknown,
    GetFormEmbedScriptExternalFormsEmbeddingFormIdFormJsGetError,
    ThrowOnError
  >({
    url: '/external/forms/{embedding_form_id}/form.js',
    ...options,
  });
};

/**
 * Create Form
 * Saves form data from a dynamic form.
 */
export const createFormExternalFormsSubmitPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateFormExternalFormsSubmitPostData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateFormExternalFormsSubmitPostResponse,
    CreateFormExternalFormsSubmitPostError,
    ThrowOnError
  >({
    url: '/external/forms/submit',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Create Document Description
 * Create an ai automatic description for a document
 */
export const createDocumentDescriptionDocumentAnalysisDocumentIdPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateDocumentDescriptionDocumentAnalysisDocumentIdPostData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).post<
    unknown,
    CreateDocumentDescriptionDocumentAnalysisDocumentIdPostError,
    ThrowOnError
  >({
    url: '/document-analysis/{document_id}',
    ...options,
  });
};

/**
 * Api Converse
 * Get the LLM output for the given file
 */
export const apiConverseConversationFilesFileIdLlmPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiConverseConversationFilesFileIdLlmPostData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    ApiConverseConversationFilesFileIdLlmPostResponse,
    ApiConverseConversationFilesFileIdLlmPostError,
    ThrowOnError
  >({
    url: '/conversation/files/{file_id}/llm',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Clone Template Batch
 * Clone documents to new objects.
 */
export const cloneTemplateBatchCloneBatchPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CloneTemplateBatchCloneBatchPostData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CloneTemplateBatchCloneBatchPostResponse,
    CloneTemplateBatchCloneBatchPostError,
    ThrowOnError
  >({
    url: '/clone/batch',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Initialize Tenant
 * Initializes a new tenant
 */
export const initializeTenantTenantsDatabasePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<InitializeTenantTenantsDatabasePostData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    unknown,
    InitializeTenantTenantsDatabasePostError,
    ThrowOnError
  >({
    url: '/tenants/database',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Refresh Settings Cache
 * Refresh settings cache
 */
export const refreshSettingsCacheTenantsRefreshSettingsCachePost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    RefreshSettingsCacheTenantsRefreshSettingsCachePostData,
    ThrowOnError
  >
) => {
  return (options?.client ?? _heyApiClient).post<
    unknown,
    unknown,
    ThrowOnError
  >({
    url: '/tenants/refresh-settings-cache',
    ...options,
  });
};

/**
 * Get Root
 * Provide the root level route for the service
 *
 * Returns:
 * dict: Name of the API and the version
 */
export const getRootGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetRootGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>(
    {
      url: '/',
      ...options,
    }
  );
};

/**
 * Get Status Check
 * Get the status of the API and the resources.
 *
 * Returns:
 * dict: Information about the status, the dependency status and the version.
 */
export const getStatusCheckStatusGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetStatusCheckStatusGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>(
    {
      url: '/status',
      ...options,
    }
  );
};
