// This file is auto-generated by @hey-api/openapi-ts

export const ComparisonOperatorsSchema = {
  type: 'string',
  enum: [
    'NONE',
    'EQUAL',
    'NOT_EQUAL',
    'IN',
    'NOT_IN',
    'GREATER_THAN',
    'GREATER_THAN_OR_EQUAL',
    'LESS_THAN',
    'LESS_THAN_OR_EQUAL',
    'BETWEEN',
  ],
  title: 'ComparisonOperators',
  description: 'Comparisons that can be done on the conditional fields',
} as const;

export const CreateDynamicFormEmbeddingSchemaSchema = {
  properties: {
    templateFormId: {
      type: 'string',
      format: 'uuid4',
      title: 'Templateformid',
    },
    productId: {
      type: 'string',
      format: 'uuid4',
      title: 'Productid',
    },
    customCss: {
      type: 'string',
      title: 'Customcss',
    },
    domains: {
      items: {
        type: 'string',
      },
      type: 'array',
      title: 'Domains',
    },
  },
  type: 'object',
  required: ['templateFormId', 'productId', 'customCss', 'domains'],
  title: 'CreateDynamicFormEmbeddingSchema',
  description: 'Schema for creating a new dynamic form embedding',
} as const;

export const DependsOnSchema = {
  properties: {
    field: {
      type: 'string',
      title: 'Field',
    },
    operation: {
      $ref: '#/components/schemas/ComparisonOperators',
    },
    value: {
      type: 'string',
      title: 'Value',
    },
  },
  type: 'object',
  required: ['field', 'operation', 'value'],
  title: 'DependsOn',
  description: 'Conditional fields structures',
} as const;

export const DynamicFormBaseSchemaSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    template: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Template',
      default: false,
    },
    formType: {
      $ref: '#/components/schemas/FormTypes',
    },
    formDefinition: {
      items: {
        anyOf: [
          {
            $ref: '#/components/schemas/DynamicFormField-Input',
          },
          {
            $ref: '#/components/schemas/DynamicFormSection-Input',
          },
        ],
      },
      type: 'array',
      title: 'Formdefinition',
    },
    data: {
      anyOf: [
        {
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Data',
    },
    createdAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Createdat',
    },
    updatedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Updatedat',
    },
  },
  type: 'object',
  required: ['name', 'formType', 'formDefinition'],
  title: 'DynamicFormBaseSchema',
  description: 'Base request schema for the dynamic form requests',
} as const;

export const DynamicFormCreatedSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
    digest: {
      type: 'string',
      title: 'Digest',
      description: 'Generate the dynamic form digest',
      readOnly: true,
    },
  },
  type: 'object',
  required: ['id', 'digest'],
  title: 'DynamicFormCreatedSchema',
  description: 'Response schema for when a dynamic form is created',
} as const;

export const DynamicFormEmbeddingCreatedSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
  },
  type: 'object',
  required: ['id'],
  title: 'DynamicFormEmbeddingCreatedSchema',
  description: 'Response when a new dynamic form embedding is created.',
} as const;

export const DynamicFormField_InputSchema = {
  properties: {
    id: {
      type: 'string',
      title: 'Id',
    },
    name: {
      type: 'string',
      title: 'Name',
    },
    sectionId: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Sectionid',
    },
    label: {
      type: 'string',
      title: 'Label',
    },
    fieldType: {
      $ref: '#/components/schemas/FieldTypes',
    },
    parameters: {
      $ref: '#/components/schemas/FieldParameters',
    },
    column: {
      type: 'integer',
      title: 'Column',
      default: 0,
    },
    required: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Required',
      default: false,
    },
    value: {
      anyOf: [
        {},
        {
          type: 'null',
        },
      ],
      title: 'Value',
    },
    dependsOn: {
      anyOf: [
        {
          $ref: '#/components/schemas/DependsOn',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  type: 'object',
  required: ['id', 'name', 'label', 'fieldType', 'parameters'],
  title: 'DynamicFormField',
  description: 'Fields definition',
} as const;

export const DynamicFormField_OutputSchema = {
  properties: {
    id: {
      type: 'string',
      title: 'Id',
    },
    name: {
      type: 'string',
      title: 'Name',
    },
    sectionId: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Sectionid',
    },
    label: {
      type: 'string',
      title: 'Label',
    },
    fieldType: {
      $ref: '#/components/schemas/FieldTypes',
    },
    parameters: {
      $ref: '#/components/schemas/FieldParameters',
    },
    column: {
      type: 'integer',
      title: 'Column',
      default: 0,
    },
    required: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Required',
      default: false,
    },
    value: {
      anyOf: [
        {},
        {
          type: 'null',
        },
      ],
      title: 'Value',
    },
    dependsOn: {
      anyOf: [
        {
          $ref: '#/components/schemas/DependsOn',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  type: 'object',
  required: ['id', 'name', 'label', 'fieldType', 'parameters'],
  title: 'DynamicFormField',
  description: 'Fields definition',
} as const;

export const DynamicFormSection_InputSchema = {
  properties: {
    id: {
      type: 'string',
      title: 'Id',
    },
    name: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Name',
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Description',
    },
    layout: {
      $ref: '#/components/schemas/SectionLayouts',
      default: 'ONE_COLUMN',
    },
    fields: {
      items: {
        anyOf: [
          {
            $ref: '#/components/schemas/DynamicFormField-Input',
          },
          {},
        ],
      },
      type: 'array',
      title: 'Fields',
    },
    dependsOn: {
      anyOf: [
        {
          $ref: '#/components/schemas/DependsOn',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  type: 'object',
  required: ['id', 'fields'],
  title: 'DynamicFormSection',
  description: 'Section definition',
} as const;

export const DynamicFormSection_OutputSchema = {
  properties: {
    id: {
      type: 'string',
      title: 'Id',
    },
    name: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Name',
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Description',
    },
    layout: {
      $ref: '#/components/schemas/SectionLayouts',
      default: 'ONE_COLUMN',
    },
    fields: {
      items: {
        anyOf: [
          {
            $ref: '#/components/schemas/DynamicFormField-Output',
          },
          {},
        ],
      },
      type: 'array',
      title: 'Fields',
    },
    dependsOn: {
      anyOf: [
        {
          $ref: '#/components/schemas/DependsOn',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  type: 'object',
  required: ['id', 'fields'],
  title: 'DynamicFormSection',
  description: 'Section definition',
} as const;

export const DynamicFormTemplateBaseSchemaSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    template: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Template',
      default: true,
    },
    formType: {
      $ref: '#/components/schemas/FormTypes',
    },
    formDefinition: {
      items: {
        anyOf: [
          {
            $ref: '#/components/schemas/DynamicFormField-Input',
          },
          {
            $ref: '#/components/schemas/DynamicFormSection-Input',
          },
        ],
      },
      type: 'array',
      title: 'Formdefinition',
    },
    data: {
      anyOf: [
        {
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Data',
    },
    productCompliance: {
      anyOf: [
        {
          items: {
            type: 'string',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Productcompliance',
      default: [],
    },
    createdAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Createdat',
    },
    updatedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Updatedat',
    },
  },
  type: 'object',
  required: ['name', 'formType', 'formDefinition'],
  title: 'DynamicFormTemplateBaseSchema',
  description: 'Base request schema for the dynamic form requests',
} as const;

export const DynamicFormTemplateCreatedSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
  },
  type: 'object',
  required: ['id'],
  title: 'DynamicFormTemplateCreatedSchema',
  description: 'Response schema for when a dynamic form template is created',
} as const;

export const ExistingDynamicFormSchema_InputSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    template: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Template',
      default: false,
    },
    formType: {
      $ref: '#/components/schemas/FormTypes',
    },
    formDefinition: {
      items: {
        anyOf: [
          {
            $ref: '#/components/schemas/DynamicFormField-Input',
          },
          {
            $ref: '#/components/schemas/DynamicFormSection-Input',
          },
        ],
      },
      type: 'array',
      title: 'Formdefinition',
    },
    data: {
      anyOf: [
        {
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Data',
    },
    createdAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Createdat',
    },
    updatedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Updatedat',
    },
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
  },
  type: 'object',
  required: ['name', 'formType', 'formDefinition', 'id'],
  title: 'ExistingDynamicFormSchema',
  description: 'Existing dynamic form schema',
} as const;

export const ExistingDynamicFormSchema_OutputSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    template: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Template',
      default: false,
    },
    formType: {
      $ref: '#/components/schemas/FormTypes',
    },
    formDefinition: {
      items: {
        anyOf: [
          {
            $ref: '#/components/schemas/DynamicFormField-Output',
          },
          {
            $ref: '#/components/schemas/DynamicFormSection-Output',
          },
        ],
      },
      type: 'array',
      title: 'Formdefinition',
    },
    data: {
      anyOf: [
        {
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Data',
    },
    createdAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Createdat',
    },
    updatedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Updatedat',
    },
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
    digest: {
      type: 'string',
      title: 'Digest',
      description: 'Generate the dynamic form digest',
      readOnly: true,
    },
  },
  type: 'object',
  required: ['name', 'formType', 'formDefinition', 'id', 'digest'],
  title: 'ExistingDynamicFormSchema',
  description: 'Existing dynamic form schema',
} as const;

export const ExistingDynamicFormTemplateSchema_InputSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    template: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Template',
      default: true,
    },
    formType: {
      $ref: '#/components/schemas/FormTypes',
    },
    formDefinition: {
      items: {
        anyOf: [
          {
            $ref: '#/components/schemas/DynamicFormField-Input',
          },
          {
            $ref: '#/components/schemas/DynamicFormSection-Input',
          },
        ],
      },
      type: 'array',
      title: 'Formdefinition',
    },
    data: {
      anyOf: [
        {
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Data',
    },
    productCompliance: {
      anyOf: [
        {
          items: {
            type: 'string',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Productcompliance',
      default: [],
    },
    createdAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Createdat',
    },
    updatedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Updatedat',
    },
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
  },
  type: 'object',
  required: ['name', 'formType', 'formDefinition', 'id'],
  title: 'ExistingDynamicFormTemplateSchema',
  description: 'Existing dynamic form template',
} as const;

export const ExistingDynamicFormTemplateSchema_OutputSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    template: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Template',
      default: true,
    },
    formType: {
      $ref: '#/components/schemas/FormTypes',
    },
    formDefinition: {
      items: {
        anyOf: [
          {
            $ref: '#/components/schemas/DynamicFormField-Output',
          },
          {
            $ref: '#/components/schemas/DynamicFormSection-Output',
          },
        ],
      },
      type: 'array',
      title: 'Formdefinition',
    },
    data: {
      anyOf: [
        {
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Data',
    },
    productCompliance: {
      anyOf: [
        {
          items: {
            type: 'string',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Productcompliance',
      default: [],
    },
    createdAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Createdat',
    },
    updatedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Updatedat',
    },
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
  },
  type: 'object',
  required: ['name', 'formType', 'formDefinition', 'id'],
  title: 'ExistingDynamicFormTemplateSchema',
  description: 'Existing dynamic form template',
} as const;

export const ExistingFileSchema_InputSchema = {
  properties: {
    template: {
      type: 'boolean',
      title: 'Template',
      default: false,
    },
    fileMetadata: {
      anyOf: [
        {
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Filemetadata',
      default: {},
    },
    fileType: {
      anyOf: [
        {
          $ref: '#/components/schemas/FileTypes',
        },
        {
          type: 'null',
        },
      ],
      default: 'ANY',
    },
    originalName: {
      type: 'string',
      title: 'Originalname',
    },
    path: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Path',
    },
    createdAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Createdat',
    },
    updatedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Updatedat',
    },
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
    pdfGenerated: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Pdfgenerated',
      default: false,
    },
    pdfGeneratedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Pdfgeneratedat',
    },
    thumbnailGenerated: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Thumbnailgenerated',
      default: false,
    },
    thumbnailGeneratedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Thumbnailgeneratedat',
    },
    pageCount: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Pagecount',
    },
    thumbnailUrl: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Thumbnailurl',
    },
    pdfUrl: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Pdfurl',
    },
    originalUrl: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Originalurl',
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Description',
    },
  },
  type: 'object',
  required: ['originalName', 'id'],
  title: 'ExistingFileSchema',
  description: 'Existing file schema',
} as const;

export const ExistingFileSchema_OutputSchema = {
  properties: {
    template: {
      type: 'boolean',
      title: 'Template',
      default: false,
    },
    fileMetadata: {
      anyOf: [
        {
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Filemetadata',
      default: {},
    },
    fileType: {
      anyOf: [
        {
          $ref: '#/components/schemas/FileTypes',
        },
        {
          type: 'null',
        },
      ],
      default: 'ANY',
    },
    originalName: {
      type: 'string',
      title: 'Originalname',
    },
    path: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Path',
    },
    createdAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Createdat',
    },
    updatedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Updatedat',
    },
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
    pdfGenerated: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Pdfgenerated',
      default: false,
    },
    pdfGeneratedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Pdfgeneratedat',
    },
    thumbnailGenerated: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Thumbnailgenerated',
      default: false,
    },
    thumbnailGeneratedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Thumbnailgeneratedat',
    },
    pageCount: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Pagecount',
    },
    thumbnailUrl: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Thumbnailurl',
    },
    pdfUrl: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Pdfurl',
    },
    originalUrl: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Originalurl',
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Description',
    },
    digest: {
      type: 'string',
      title: 'Digest',
      description: 'Generate the file digest',
      readOnly: true,
    },
  },
  type: 'object',
  required: ['originalName', 'id', 'digest'],
  title: 'ExistingFileSchema',
  description: 'Existing file schema',
} as const;

export const ExistingFileTemplateSchemaSchema = {
  properties: {
    template: {
      type: 'boolean',
      title: 'Template',
      default: true,
    },
    fileMetadata: {
      anyOf: [
        {
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Filemetadata',
      default: {},
    },
    fileType: {
      anyOf: [
        {
          $ref: '#/components/schemas/FileTypes',
        },
        {
          type: 'null',
        },
      ],
      default: 'ANY',
    },
    originalName: {
      type: 'string',
      title: 'Originalname',
    },
    path: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Path',
    },
    createdAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Createdat',
    },
    updatedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Updatedat',
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Description',
    },
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
    pdfGenerated: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Pdfgenerated',
      default: false,
    },
    pdfGeneratedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Pdfgeneratedat',
    },
    thumbnailGenerated: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Thumbnailgenerated',
      default: false,
    },
    thumbnailGeneratedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Thumbnailgeneratedat',
    },
    pageCount: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Pagecount',
    },
    thumbnailUrl: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Thumbnailurl',
    },
    pdfUrl: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Pdfurl',
    },
    originalUrl: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Originalurl',
    },
  },
  type: 'object',
  required: ['originalName', 'id'],
  title: 'ExistingFileTemplateSchema',
  description: 'Existing template',
} as const;

export const ExistingFormEmbeddingSchemaSchema = {
  properties: {
    templateFormId: {
      type: 'string',
      format: 'uuid4',
      title: 'Templateformid',
    },
    productId: {
      type: 'string',
      format: 'uuid4',
      title: 'Productid',
    },
    customCss: {
      type: 'string',
      title: 'Customcss',
    },
    domains: {
      items: {
        type: 'string',
      },
      type: 'array',
      title: 'Domains',
    },
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
    form: {
      $ref: '#/components/schemas/ExistingDynamicFormSchema-Output',
    },
    nonce: {
      type: 'string',
      title: 'Nonce',
      description: 'Generate a nonce for use in the script embedding',
      readOnly: true,
    },
  },
  type: 'object',
  required: [
    'templateFormId',
    'productId',
    'customCss',
    'domains',
    'id',
    'form',
    'nonce',
  ],
  title: 'ExistingFormEmbeddingSchema',
  description: 'Schema for existing form embedding',
} as const;

export const ExistingFormEmbeddingSchemaWithCsrfTokenSchema = {
  properties: {
    templateFormId: {
      type: 'string',
      format: 'uuid4',
      title: 'Templateformid',
    },
    productId: {
      type: 'string',
      format: 'uuid4',
      title: 'Productid',
    },
    customCss: {
      type: 'string',
      title: 'Customcss',
    },
    domains: {
      items: {
        type: 'string',
      },
      type: 'array',
      title: 'Domains',
    },
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
    form: {
      $ref: '#/components/schemas/ExistingDynamicFormSchema-Output',
    },
    csrfToken: {
      type: 'string',
      title: 'Csrftoken',
    },
    nonce: {
      type: 'string',
      title: 'Nonce',
      description: 'Generate a nonce for use in the script embedding',
      readOnly: true,
    },
  },
  type: 'object',
  required: [
    'templateFormId',
    'productId',
    'customCss',
    'domains',
    'id',
    'form',
    'csrfToken',
    'nonce',
  ],
  title: 'ExistingFormEmbeddingSchemaWithCsrfToken',
  description: 'Schema for existing form embedding with a CSRF token',
} as const;

export const ExistingSignatureSchemaSchema = {
  properties: {
    targetId: {
      type: 'string',
      format: 'uuid4',
      title: 'Targetid',
    },
    targetType: {
      $ref: '#/components/schemas/SignatureTargets',
    },
    signatoryId: {
      type: 'string',
      format: 'uuid4',
      title: 'Signatoryid',
    },
    signatoryType: {
      $ref: '#/components/schemas/SignatoryTypes',
    },
    signature: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Signature',
    },
    signatureDate: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Signaturedate',
    },
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
    digest: {
      type: 'string',
      title: 'Digest',
      description: 'Generate the dignature digest',
      readOnly: true,
    },
  },
  type: 'object',
  required: [
    'targetId',
    'targetType',
    'signatoryId',
    'signatoryType',
    'id',
    'digest',
  ],
  title: 'ExistingSignatureSchema',
  description: 'Existing signature schema',
} as const;

export const FieldOptionSchema = {
  properties: {
    label: {
      type: 'string',
      title: 'Label',
    },
    value: {
      type: 'string',
      title: 'Value',
    },
    description: {
      type: 'string',
      title: 'Description',
    },
  },
  type: 'object',
  required: ['label', 'value', 'description'],
  title: 'FieldOption',
  description: 'Options for fields that can contain options (select, radio)',
} as const;

export const FieldParametersSchema = {
  properties: {
    options: {
      anyOf: [
        {
          items: {
            $ref: '#/components/schemas/FieldOption',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Options',
    },
    decimalPrecision: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Decimalprecision',
    },
    minimumLength: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Minimumlength',
    },
    maximumLength: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Maximumlength',
    },
    minimumValue: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Minimumvalue',
    },
    maximumValue: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Maximumvalue',
    },
    type: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Type',
    },
    placeholder: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Placeholder',
    },
    validator: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Validator',
    },
  },
  type: 'object',
  required: [
    'decimalPrecision',
    'minimumLength',
    'maximumLength',
    'minimumValue',
    'maximumValue',
    'type',
    'placeholder',
    'validator',
  ],
  title: 'FieldParameters',
  description: 'Parameters that can be set on fields',
} as const;

export const FieldTypesSchema = {
  type: 'string',
  enum: [
    'INPUT',
    'DATE',
    'TEXT',
    'MONEY',
    'NUMBER',
    'RADIO',
    'SELECT',
    'CHECKBOX',
    'LOAN_INFORMATION',
    'LOAN_PURPOSE',
    'LOAN_SOURCES',
    'CREDIT_CHECK',
    'SUBMIT_BUTTON',
  ],
  title: 'FieldTypes',
  description: 'Field types',
} as const;

export const FileBaseSchemaSchema = {
  properties: {
    template: {
      type: 'boolean',
      title: 'Template',
      default: false,
    },
    fileMetadata: {
      anyOf: [
        {
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Filemetadata',
      default: {},
    },
    fileType: {
      anyOf: [
        {
          $ref: '#/components/schemas/FileTypes',
        },
        {
          type: 'null',
        },
      ],
      default: 'ANY',
    },
    originalName: {
      type: 'string',
      title: 'Originalname',
    },
    path: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Path',
    },
    createdAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Createdat',
    },
    updatedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Updatedat',
    },
  },
  type: 'object',
  required: ['originalName'],
  title: 'FileBaseSchema',
  description: 'Base request schema for the file requests',
} as const;

export const FileCreatedSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
    originalName: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Originalname',
    },
    digest: {
      type: 'string',
      title: 'Digest',
      description: 'Generate the file digest',
      readOnly: true,
    },
  },
  type: 'object',
  required: ['id', 'digest'],
  title: 'FileCreatedSchema',
  description: 'Response schema for when a file is created',
} as const;

export const FileTemplateBaseSchemaSchema = {
  properties: {
    template: {
      type: 'boolean',
      title: 'Template',
      default: true,
    },
    fileMetadata: {
      anyOf: [
        {
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Filemetadata',
      default: {},
    },
    fileType: {
      anyOf: [
        {
          $ref: '#/components/schemas/FileTypes',
        },
        {
          type: 'null',
        },
      ],
      default: 'ANY',
    },
    originalName: {
      type: 'string',
      title: 'Originalname',
    },
    path: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Path',
    },
    createdAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Createdat',
    },
    updatedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Updatedat',
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Description',
    },
  },
  type: 'object',
  required: ['originalName'],
  title: 'FileTemplateBaseSchema',
  description: 'Template base schema',
} as const;

export const FileTemplateCloneSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
    originalName: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Originalname',
    },
    originalId: {
      type: 'string',
      format: 'uuid4',
      title: 'Originalid',
    },
  },
  type: 'object',
  required: ['id', 'originalId'],
  title: 'FileTemplateCloneSchema',
  description: 'Response schema for when a file template batch is cloned',
} as const;

export const FileTemplateCreatedSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
    originalName: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Originalname',
    },
  },
  type: 'object',
  required: ['id'],
  title: 'FileTemplateCreatedSchema',
  description: 'Response schema for when a file template is created',
} as const;

export const FileTypesSchema = {
  type: 'string',
  enum: ['WORD', 'EXCEL', 'PDF', 'IMAGE', 'ARCHIVE', 'ANY'],
  title: 'FileTypes',
  description: 'Types of files',
} as const;

export const FormTypesSchema = {
  type: 'string',
  enum: ['INLINE', 'TABS', 'STEPS'],
  title: 'FormTypes',
  description: 'Types of forms',
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: '#/components/schemas/ValidationError',
      },
      type: 'array',
      title: 'Detail',
    },
  },
  type: 'object',
  title: 'HTTPValidationError',
} as const;

export const LLMInputSchema = {
  properties: {
    conversationId: {
      type: 'string',
      format: 'uuid4',
      title: 'Conversationid',
    },
    prompt: {
      type: 'string',
      title: 'Prompt',
    },
  },
  type: 'object',
  required: ['conversationId', 'prompt'],
  title: 'LLMInput',
  description: 'This class represents the base schema for Llm S',
} as const;

export const LLMOutputSchema = {
  properties: {
    conversationId: {
      type: 'string',
      format: 'uuid4',
      title: 'Conversationid',
    },
    prompt: {
      type: 'string',
      title: 'Prompt',
    },
    response: {
      title: 'Response',
    },
  },
  type: 'object',
  required: ['conversationId', 'prompt', 'response'],
  title: 'LLMOutput',
  description: 'This class represents the base schema for Llm S',
} as const;

export const SectionLayoutsSchema = {
  type: 'string',
  enum: ['ONE_COLUMN', 'TWO_COLUMNS', 'THREE_COLUMN'],
  title: 'SectionLayouts',
  description: 'Layout that a section can display fields',
} as const;

export const SignatoryTypesSchema = {
  type: 'string',
  enum: ['USER', 'GROUP'],
  title: 'SignatoryTypes',
  description: 'Types of signatory',
} as const;

export const SignatureBaseSchemaSchema = {
  properties: {
    targetId: {
      type: 'string',
      format: 'uuid4',
      title: 'Targetid',
    },
    targetType: {
      $ref: '#/components/schemas/SignatureTargets',
    },
    signatoryId: {
      type: 'string',
      format: 'uuid4',
      title: 'Signatoryid',
    },
    signatoryType: {
      $ref: '#/components/schemas/SignatoryTypes',
    },
    signature: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Signature',
    },
    signatureDate: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Signaturedate',
    },
  },
  type: 'object',
  required: ['targetId', 'targetType', 'signatoryId', 'signatoryType'],
  title: 'SignatureBaseSchema',
  description: 'Base request schema for the signature requests',
} as const;

export const SignatureCreatedSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
  },
  type: 'object',
  required: ['id'],
  title: 'SignatureCreatedSchema',
  description: 'Response schema for when a signature is created',
} as const;

export const SignatureTargetsSchema = {
  type: 'string',
  enum: ['APPLICATION', 'REQUEST', 'DOCUMENT', 'FILE', 'DYNAMIC_FORM'],
  title: 'SignatureTargets',
  description: 'Types of target for a signature',
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: 'string',
          },
          {
            type: 'integer',
          },
        ],
      },
      type: 'array',
      title: 'Location',
    },
    msg: {
      type: 'string',
      title: 'Message',
    },
    type: {
      type: 'string',
      title: 'Error Type',
    },
  },
  type: 'object',
  required: ['loc', 'msg', 'type'],
  title: 'ValidationError',
} as const;
