// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type Options,
} from '@hey-api/client-fetch';
import type {
  CreateFileMetadataFilesPostData,
  CreateFileMetadataFilesPostError,
  CreateFileMetadataFilesPostResponse,
  CreateBatchFileMetadataFilesBatchPostData,
  CreateBatchFileMetadataFilesBatchPostError,
  CreateBatchFileMetadataFilesBatchPostResponse,
  DeleteFileMetadataFilesFileIdDeleteData,
  DeleteFileMetadataFilesFileIdDeleteError,
  GetFileMetadataFilesFileIdGetData,
  GetFileMetadataFilesFileIdGetError,
  GetFileMetadataFilesFileIdGetResponse,
  GetHeadFileMetadataFilesFileIdHeadData,
  GetHeadFileMetadataFilesFileIdHeadError,
  GetHeadFileMetadataFilesFileIdHeadResponse,
  UpdateFileMetadataFilesFileIdPutData,
  UpdateFileMetadataFilesFileIdPutError,
  PostUploadFileFilesFileIdUploadPostData,
  PostUploadFileFilesFileIdUploadPostError,
  PutUploadFileFilesFileIdUploadPutData,
  PutUploadFileFilesFileIdUploadPutError,
  DownloadFileFilesFileIdDownloadGetData,
  DownloadFileFilesFileIdDownloadGetError,
  TriggerConversionFilesFileIdConvertPostData,
  TriggerConversionFilesFileIdConvertPostError,
  CreateFormFormsPostData,
  CreateFormFormsPostError,
  CreateFormFormsPostResponse,
  DeleteFormFormsDynamicFormIdDeleteData,
  DeleteFormFormsDynamicFormIdDeleteError,
  GetFormFormsDynamicFormIdGetData,
  GetFormFormsDynamicFormIdGetError,
  GetFormFormsDynamicFormIdGetResponse,
  UpdateFormFormsDynamicFormIdPutData,
  UpdateFormFormsDynamicFormIdPutError,
  SearchSearchGetData,
  CreateSignatureSignaturesPostData,
  CreateSignatureSignaturesPostError,
  CreateSignatureSignaturesPostResponse,
  DeleteSignatureSignaturesSignatureIdDeleteData,
  DeleteSignatureSignaturesSignatureIdDeleteError,
  GetSignatureSignaturesSignatureIdGetData,
  GetSignatureSignaturesSignatureIdGetError,
  GetSignatureSignaturesSignatureIdGetResponse,
  GetAllTemplateMetadataTemplatesFilesGetData,
  GetAllTemplateMetadataTemplatesFilesGetResponse,
  CreateTemplateMetadataTemplatesFilesPostData,
  CreateTemplateMetadataTemplatesFilesPostError,
  CreateTemplateMetadataTemplatesFilesPostResponse,
  CreateBatchFileTemplateTemplatesFilesBatchPostData,
  CreateBatchFileTemplateTemplatesFilesBatchPostError,
  CreateBatchFileTemplateTemplatesFilesBatchPostResponse,
  DeleteTemplateMetadataTemplatesFilesTemplateIdDeleteData,
  DeleteTemplateMetadataTemplatesFilesTemplateIdDeleteError,
  GetTemplateMetadataTemplatesFilesTemplateIdGetData,
  GetTemplateMetadataTemplatesFilesTemplateIdGetError,
  GetTemplateMetadataTemplatesFilesTemplateIdGetResponse,
  UpdateTemplateMetadataTemplatesFilesTemplateIdPutData,
  UpdateTemplateMetadataTemplatesFilesTemplateIdPutError,
  PostUploadTemplateTemplatesFilesTemplateIdUploadPostData,
  PostUploadTemplateTemplatesFilesTemplateIdUploadPostError,
  PutUploadTemplateTemplatesFilesTemplateIdUploadPutData,
  PutUploadTemplateTemplatesFilesTemplateIdUploadPutError,
  DownloadTemplateTemplatesFilesTemplateIdDownloadGetData,
  DownloadTemplateTemplatesFilesTemplateIdDownloadGetError,
  CloneTemplateTemplatesFilesTemplateIdClonePostData,
  CloneTemplateTemplatesFilesTemplateIdClonePostError,
  CloneTemplateTemplatesFilesTemplateIdClonePostResponse,
  CloneTemplateBatchTemplatesFilesCloneBatchPostData,
  CloneTemplateBatchTemplatesFilesCloneBatchPostError,
  CloneTemplateBatchTemplatesFilesCloneBatchPostResponse,
  TriggerConversionTemplatesFilesTemplateIdConvertPostData,
  TriggerConversionTemplatesFilesTemplateIdConvertPostError,
  GetAllFormTemplatesTemplatesFormsGetData,
  GetAllFormTemplatesTemplatesFormsGetResponse,
  CreateFormTemplateTemplatesFormsPostData,
  CreateFormTemplateTemplatesFormsPostError,
  CreateFormTemplateTemplatesFormsPostResponse,
  DeleteFormTemplateTemplatesFormsTemplateIdDeleteData,
  DeleteFormTemplateTemplatesFormsTemplateIdDeleteError,
  GetFormTemplateTemplatesFormsTemplateIdGetData,
  GetFormTemplateTemplatesFormsTemplateIdGetError,
  GetFormTemplateTemplatesFormsTemplateIdGetResponse,
  UpdateFormTemplateTemplatesFormsTemplateIdPutData,
  UpdateFormTemplateTemplatesFormsTemplateIdPutError,
  GetEmbeddingFormsExternalFormsGetData,
  GetEmbeddingFormsExternalFormsGetError,
  GetEmbeddingFormsExternalFormsGetResponse,
  CreateEmbeddingFormExternalFormsPostData,
  CreateEmbeddingFormExternalFormsPostError,
  CreateEmbeddingFormExternalFormsPostResponse,
  DeleteEmbeddingFormExternalFormsEmbeddingFormIdDeleteData,
  DeleteEmbeddingFormExternalFormsEmbeddingFormIdDeleteError,
  GetEmbeddingFormExternalFormsEmbeddingFormIdGetData,
  GetEmbeddingFormExternalFormsEmbeddingFormIdGetError,
  GetEmbeddingFormExternalFormsEmbeddingFormIdGetResponse,
  UpdateEmbeddingFormExternalFormsEmbeddingFormIdPutData,
  UpdateEmbeddingFormExternalFormsEmbeddingFormIdPutError,
  UpdateEmbeddingFormExternalFormsEmbeddingFormIdPutResponse,
  GetFormEmbeddingExternalFormsDefinitionEmbeddingFormIdGetData,
  GetFormEmbeddingExternalFormsDefinitionEmbeddingFormIdGetError,
  GetFormEmbeddingExternalFormsDefinitionEmbeddingFormIdGetResponse,
  GetFormEmbedScriptExternalFormsEmbeddingFormIdFormJsGetData,
  GetFormEmbedScriptExternalFormsEmbeddingFormIdFormJsGetError,
  CreateFormExternalFormsSubmitPostData,
  CreateFormExternalFormsSubmitPostError,
  CreateFormExternalFormsSubmitPostResponse,
  CreateDocumentDescriptionDocumentAnalysisDocumentIdPostData,
  CreateDocumentDescriptionDocumentAnalysisDocumentIdPostError,
  ApiConverseConversationFilesFileIdLlmPostData,
  ApiConverseConversationFilesFileIdLlmPostError,
  ApiConverseConversationFilesFileIdLlmPostResponse,
  GetRootGetData,
  GetStatusCheckStatusGetData,
} from './types.gen';

export const client = createClient(createConfig());

/**
 * Create File Metadata
 * Create a new document metadata object.That object is not the file itself but information about the file.After creating that object, you need to post a request on the /upload path.
 */
export const createFileMetadataFilesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateFileMetadataFilesPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    CreateFileMetadataFilesPostResponse,
    CreateFileMetadataFilesPostError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/files',
  });
};

/**
 * Create Batch File Metadata
 * Batch create of documents metadata object.That object is not the file itself but information about the file.After creating that object, you need to post a request on the /upload path.
 */
export const createBatchFileMetadataFilesBatchPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateBatchFileMetadataFilesBatchPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    CreateBatchFileMetadataFilesBatchPostResponse,
    CreateBatchFileMetadataFilesBatchPostError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/files/batch',
  });
};

/**
 * Delete File Metadata
 * Delete a specific file metadata
 */
export const deleteFileMetadataFilesFileIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteFileMetadataFilesFileIdDeleteData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    unknown,
    DeleteFileMetadataFilesFileIdDeleteError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/files/{file_id}',
  });
};

/**
 * Get File Metadata
 * Get a specific file metadata
 */
export const getFileMetadataFilesFileIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetFileMetadataFilesFileIdGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetFileMetadataFilesFileIdGetResponse,
    GetFileMetadataFilesFileIdGetError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/files/{file_id}',
  });
};

/**
 * Get Head File Metadata
 * Get a specific file metadata
 */
export const getHeadFileMetadataFilesFileIdHead = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetHeadFileMetadataFilesFileIdHeadData, ThrowOnError>
) => {
  return (options?.client ?? client).head<
    GetHeadFileMetadataFilesFileIdHeadResponse,
    GetHeadFileMetadataFilesFileIdHeadError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/files/{file_id}',
  });
};

/**
 * Update File Metadata
 * Update a specific file metadata
 */
export const updateFileMetadataFilesFileIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateFileMetadataFilesFileIdPutData, ThrowOnError>
) => {
  return (options?.client ?? client).put<
    unknown,
    UpdateFileMetadataFilesFileIdPutError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/files/{file_id}',
  });
};

/**
 * Post Upload File
 * Get the upload link for a post request
 */
export const postUploadFileFilesFileIdUploadPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostUploadFileFilesFileIdUploadPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    unknown,
    PostUploadFileFilesFileIdUploadPostError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/files/{file_id}/upload',
  });
};

/**
 * Put Upload File
 * Get the upload link for a put request
 */
export const putUploadFileFilesFileIdUploadPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutUploadFileFilesFileIdUploadPutData, ThrowOnError>
) => {
  return (options?.client ?? client).put<
    unknown,
    PutUploadFileFilesFileIdUploadPutError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/files/{file_id}/upload',
  });
};

/**
 * Download File
 * Get the download link for a file
 */
export const downloadFileFilesFileIdDownloadGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DownloadFileFilesFileIdDownloadGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    unknown,
    DownloadFileFilesFileIdDownloadGetError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/files/{file_id}/download',
  });
};

/**
 * Trigger Conversion
 * Trigger the conversion of a file to PDF format.
 */
export const triggerConversionFilesFileIdConvertPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TriggerConversionFilesFileIdConvertPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    unknown,
    TriggerConversionFilesFileIdConvertPostError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/files/{file_id}/convert',
  });
};

/**
 * Create Form
 * Create a new dynamic form object.
 */
export const createFormFormsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateFormFormsPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    CreateFormFormsPostResponse,
    CreateFormFormsPostError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/forms',
  });
};

/**
 * Delete Form
 * Delete a dynamic form, including the model and the data.
 */
export const deleteFormFormsDynamicFormIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteFormFormsDynamicFormIdDeleteData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    unknown,
    DeleteFormFormsDynamicFormIdDeleteError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/forms/{dynamic_form_id}',
  });
};

/**
 * Get Form
 * Get a dynamic form (definition and data).
 */
export const getFormFormsDynamicFormIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetFormFormsDynamicFormIdGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetFormFormsDynamicFormIdGetResponse,
    GetFormFormsDynamicFormIdGetError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/forms/{dynamic_form_id}',
  });
};

/**
 * Update Form
 * Update the definition and the model of a dynamic form.To update only a field of the model, consider implementing a patch...
 */
export const updateFormFormsDynamicFormIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateFormFormsDynamicFormIdPutData, ThrowOnError>
) => {
  return (options?.client ?? client).put<
    unknown,
    UpdateFormFormsDynamicFormIdPutError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/forms/{dynamic_form_id}',
  });
};

/**
 * Search
 * Search documents
 */
export const searchSearchGet = <ThrowOnError extends boolean = false>(
  options?: Options<SearchSearchGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/search/',
  });
};

/**
 * Create Signature
 * Create a new signature.
 */
export const createSignatureSignaturesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateSignatureSignaturesPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    CreateSignatureSignaturesPostResponse,
    CreateSignatureSignaturesPostError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/signatures',
  });
};

/**
 * Delete Signature
 * Delete a signature.
 */
export const deleteSignatureSignaturesSignatureIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteSignatureSignaturesSignatureIdDeleteData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    unknown,
    DeleteSignatureSignaturesSignatureIdDeleteError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/signatures/{signature_id}',
  });
};

/**
 * Get Signature
 * Get a signature.
 */
export const getSignatureSignaturesSignatureIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetSignatureSignaturesSignatureIdGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetSignatureSignaturesSignatureIdGetResponse,
    GetSignatureSignaturesSignatureIdGetError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/signatures/{signature_id}',
  });
};

/**
 * Get All Template Metadata
 * return a list of all file template metadata
 */
export const getAllTemplateMetadataTemplatesFilesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetAllTemplateMetadataTemplatesFilesGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetAllTemplateMetadataTemplatesFilesGetResponse,
    unknown,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/templates/files',
  });
};

/**
 * Create Template Metadata
 * Create a new template metadata object.That object is not the file template itself but information about the template.After creating that object, you need to post a request on the /upload path.
 */
export const createTemplateMetadataTemplatesFilesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateTemplateMetadataTemplatesFilesPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    CreateTemplateMetadataTemplatesFilesPostResponse,
    CreateTemplateMetadataTemplatesFilesPostError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/templates/files',
  });
};

/**
 * Create Batch File Template
 * Batch create of file template documents metadata object.That object is not the file itself but information about the file.After creating that object, you need to post a request on the /upload path.
 */
export const createBatchFileTemplateTemplatesFilesBatchPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateBatchFileTemplateTemplatesFilesBatchPostData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).post<
    CreateBatchFileTemplateTemplatesFilesBatchPostResponse,
    CreateBatchFileTemplateTemplatesFilesBatchPostError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/templates/files/batch',
  });
};

/**
 * Delete Template Metadata
 * Delete a specific file template metadata
 */
export const deleteTemplateMetadataTemplatesFilesTemplateIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteTemplateMetadataTemplatesFilesTemplateIdDeleteData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).delete<
    unknown,
    DeleteTemplateMetadataTemplatesFilesTemplateIdDeleteError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/templates/files/{template_id}',
  });
};

/**
 * Get Template Metadata
 * Return an existing file template metadata
 */
export const getTemplateMetadataTemplatesFilesTemplateIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetTemplateMetadataTemplatesFilesTemplateIdGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    GetTemplateMetadataTemplatesFilesTemplateIdGetResponse,
    GetTemplateMetadataTemplatesFilesTemplateIdGetError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/templates/files/{template_id}',
  });
};

/**
 * Update Template Metadata
 * Update a specific file template metadata
 */
export const updateTemplateMetadataTemplatesFilesTemplateIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateTemplateMetadataTemplatesFilesTemplateIdPutData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).put<
    unknown,
    UpdateTemplateMetadataTemplatesFilesTemplateIdPutError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/templates/files/{template_id}',
  });
};

/**
 * Post Upload Template
 * Get the upload link for a post request
 */
export const postUploadTemplateTemplatesFilesTemplateIdUploadPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PostUploadTemplateTemplatesFilesTemplateIdUploadPostData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).post<
    unknown,
    PostUploadTemplateTemplatesFilesTemplateIdUploadPostError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/templates/files/{template_id}/upload',
  });
};

/**
 * Put Upload Template
 * Get the upload link for a put request
 */
export const putUploadTemplateTemplatesFilesTemplateIdUploadPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PutUploadTemplateTemplatesFilesTemplateIdUploadPutData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).put<
    unknown,
    PutUploadTemplateTemplatesFilesTemplateIdUploadPutError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/templates/files/{template_id}/upload',
  });
};

/**
 * Download Template
 * Get the download link for a template
 */
export const downloadTemplateTemplatesFilesTemplateIdDownloadGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DownloadTemplateTemplatesFilesTemplateIdDownloadGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    unknown,
    DownloadTemplateTemplatesFilesTemplateIdDownloadGetError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/templates/files/{template_id}/download',
  });
};

/**
 * Clone Template
 * Clone a template to a new file.
 */
export const cloneTemplateTemplatesFilesTemplateIdClonePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CloneTemplateTemplatesFilesTemplateIdClonePostData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).post<
    CloneTemplateTemplatesFilesTemplateIdClonePostResponse,
    CloneTemplateTemplatesFilesTemplateIdClonePostError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/templates/files/{template_id}/clone',
  });
};

/**
 * Clone Template Batch
 * Clone a batch template to a new file.
 */
export const cloneTemplateBatchTemplatesFilesCloneBatchPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CloneTemplateBatchTemplatesFilesCloneBatchPostData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).post<
    CloneTemplateBatchTemplatesFilesCloneBatchPostResponse,
    CloneTemplateBatchTemplatesFilesCloneBatchPostError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/templates/files/clone/batch',
  });
};

/**
 * Trigger Conversion
 * Trigger the conversion of a file to PDF format.
 */
export const triggerConversionTemplatesFilesTemplateIdConvertPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    TriggerConversionTemplatesFilesTemplateIdConvertPostData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).post<
    unknown,
    TriggerConversionTemplatesFilesTemplateIdConvertPostError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/templates/files/{template_id}/convert',
  });
};

/**
 * Get All Form Templates
 * return a list of all dynamic form template
 */
export const getAllFormTemplatesTemplatesFormsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetAllFormTemplatesTemplatesFormsGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetAllFormTemplatesTemplatesFormsGetResponse,
    unknown,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/templates/forms',
  });
};

/**
 * Create Form Template
 * Create a new dynamic form template object.
 */
export const createFormTemplateTemplatesFormsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateFormTemplateTemplatesFormsPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    CreateFormTemplateTemplatesFormsPostResponse,
    CreateFormTemplateTemplatesFormsPostError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/templates/forms',
  });
};

/**
 * Delete Form Template
 * Delete a specific dynamic form template
 */
export const deleteFormTemplateTemplatesFormsTemplateIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteFormTemplateTemplatesFormsTemplateIdDeleteData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).delete<
    unknown,
    DeleteFormTemplateTemplatesFormsTemplateIdDeleteError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/templates/forms/{template_id}',
  });
};

/**
 * Get Form Template
 * Return an existing dynamic form template
 */
export const getFormTemplateTemplatesFormsTemplateIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetFormTemplateTemplatesFormsTemplateIdGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetFormTemplateTemplatesFormsTemplateIdGetResponse,
    GetFormTemplateTemplatesFormsTemplateIdGetError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/templates/forms/{template_id}',
  });
};

/**
 * Update Form Template
 * Update a specific dynamic form template
 */
export const updateFormTemplateTemplatesFormsTemplateIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateFormTemplateTemplatesFormsTemplateIdPutData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).put<
    unknown,
    UpdateFormTemplateTemplatesFormsTemplateIdPutError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/templates/forms/{template_id}',
  });
};

/**
 * Get Embedding Forms
 * Get a list embeddings form (definition and data).
 */
export const getEmbeddingFormsExternalFormsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetEmbeddingFormsExternalFormsGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetEmbeddingFormsExternalFormsGetResponse,
    GetEmbeddingFormsExternalFormsGetError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/external/forms',
  });
};

/**
 * Create Embedding Form
 * Create a new dynamic form embedding object.
 */
export const createEmbeddingFormExternalFormsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateEmbeddingFormExternalFormsPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    CreateEmbeddingFormExternalFormsPostResponse,
    CreateEmbeddingFormExternalFormsPostError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/external/forms',
  });
};

/**
 * Delete Embedding Form
 * Deletes a dynamic form embedding object.
 */
export const deleteEmbeddingFormExternalFormsEmbeddingFormIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteEmbeddingFormExternalFormsEmbeddingFormIdDeleteData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).delete<
    unknown,
    DeleteEmbeddingFormExternalFormsEmbeddingFormIdDeleteError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/external/forms/{embedding_form_id}',
  });
};

/**
 * Get Embedding Form
 * Get an embeddings form (definition and data).
 */
export const getEmbeddingFormExternalFormsEmbeddingFormIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetEmbeddingFormExternalFormsEmbeddingFormIdGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    GetEmbeddingFormExternalFormsEmbeddingFormIdGetResponse,
    GetEmbeddingFormExternalFormsEmbeddingFormIdGetError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/external/forms/{embedding_form_id}',
  });
};

/**
 * Update Embedding Form
 * Updates a dynamic form embedding object.
 */
export const updateEmbeddingFormExternalFormsEmbeddingFormIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateEmbeddingFormExternalFormsEmbeddingFormIdPutData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).put<
    UpdateEmbeddingFormExternalFormsEmbeddingFormIdPutResponse,
    UpdateEmbeddingFormExternalFormsEmbeddingFormIdPutError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/external/forms/{embedding_form_id}',
  });
};

/**
 * Get Form Embedding
 * Get a form embedding (unauthenticated).
 */
export const getFormEmbeddingExternalFormsDefinitionEmbeddingFormIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetFormEmbeddingExternalFormsDefinitionEmbeddingFormIdGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    GetFormEmbeddingExternalFormsDefinitionEmbeddingFormIdGetResponse,
    GetFormEmbeddingExternalFormsDefinitionEmbeddingFormIdGetError,
    ThrowOnError
  >({
    ...options,
    url: '/external/forms/definition/{embedding_form_id}',
  });
};

/**
 * Get Form Embed Script
 * Return an existing dynamic form template embed script
 */
export const getFormEmbedScriptExternalFormsEmbeddingFormIdFormJsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetFormEmbedScriptExternalFormsEmbeddingFormIdFormJsGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    unknown,
    GetFormEmbedScriptExternalFormsEmbeddingFormIdFormJsGetError,
    ThrowOnError
  >({
    ...options,
    url: '/external/forms/{embedding_form_id}/form.js',
  });
};

/**
 * Create Form
 * Saves form data from a dynamic form.
 */
export const createFormExternalFormsSubmitPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateFormExternalFormsSubmitPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    CreateFormExternalFormsSubmitPostResponse,
    CreateFormExternalFormsSubmitPostError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    url: '/external/forms/submit',
  });
};

/**
 * Create Document Description
 * Create an ai automatic description for a document
 */
export const createDocumentDescriptionDocumentAnalysisDocumentIdPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateDocumentDescriptionDocumentAnalysisDocumentIdPostData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).post<
    unknown,
    CreateDocumentDescriptionDocumentAnalysisDocumentIdPostError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/document-analysis/{document_id}',
  });
};

/**
 * Api Converse
 * Get the LLM output for the given file
 */
export const apiConverseConversationFilesFileIdLlmPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiConverseConversationFilesFileIdLlmPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ApiConverseConversationFilesFileIdLlmPostResponse,
    ApiConverseConversationFilesFileIdLlmPostError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/conversation/files/{file_id}/llm',
  });
};

/**
 * Get Root
 * Provide the root level route for the service
 *
 * Returns:
 * dict: Name of the API and the version
 */
export const getRootGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetRootGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
    ...options,
    url: '/',
  });
};

/**
 * Get Status Check
 * Get the status of the API and the resources.
 *
 * Returns:
 * dict: Information about the status, the dependency status and the version.
 */
export const getStatusCheckStatusGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetStatusCheckStatusGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
    ...options,
    url: '/status',
  });
};
