// This file is auto-generated by @hey-api/openapi-ts

/**
 * Comparisons that can be done on the conditional fields
 */
export type ComparisonOperators =
  | 'NONE'
  | 'EQUAL'
  | 'NOT_EQUAL'
  | 'IN'
  | 'NOT_IN'
  | 'GREATER_THAN'
  | 'GREATER_THAN_OR_EQUAL'
  | 'LESS_THAN'
  | 'LESS_THAN_OR_EQUAL'
  | 'BETWEEN';

/**
 * Comparisons that can be done on the conditional fields
 */
export const ComparisonOperators = {
  NONE: 'NONE',
  EQUAL: 'EQUAL',
  NOT_EQUAL: 'NOT_EQUAL',
  IN: 'IN',
  NOT_IN: 'NOT_IN',
  GREATER_THAN: 'GREATER_THAN',
  GREATER_THAN_OR_EQUAL: 'GREATER_THAN_OR_EQUAL',
  LESS_THAN: 'LESS_THAN',
  LESS_THAN_OR_EQUAL: 'LESS_THAN_OR_EQUAL',
  BETWEEN: 'BETWEEN',
} as const;

/**
 * Schema for creating a new dynamic form embedding
 */
export type CreateDynamicFormEmbeddingSchema = {
  templateFormId: string;
  productId: string;
  customCss: string;
  domains: Array<string>;
};

/**
 * Conditional fields structures
 */
export type DependsOn = {
  field: string;
  operation: ComparisonOperators;
  value: string;
};

/**
 * Base request schema for the dynamic form requests
 */
export type DynamicFormBaseSchema = {
  name: string;
  template?: boolean | null;
  formType: FormTypes;
  formDefinition: Array<DynamicFormFieldInput | DynamicFormSectionInput>;
  data?: Record<string, unknown> | null;
  createdAt?: number | null;
  updatedAt?: number | null;
};

/**
 * Response schema for when a dynamic form is created
 */
export type DynamicFormCreatedSchema = {
  id: string;
  /**
   * Generate the dynamic form digest
   */
  readonly digest: string;
};

/**
 * Response when a new dynamic form embedding is created.
 */
export type DynamicFormEmbeddingCreatedSchema = {
  id: string;
};

/**
 * Fields definition
 */
export type DynamicFormFieldInput = {
  id: string;
  name: string;
  sectionId?: string | null;
  label: string;
  fieldType: FieldTypes;
  parameters: FieldParameters;
  column?: number;
  required?: boolean | null;
  value?: unknown | null;
  dependsOn?: DependsOn | null;
};

/**
 * Fields definition
 */
export type DynamicFormFieldOutput = {
  id: string;
  name: string;
  sectionId?: string | null;
  label: string;
  fieldType: FieldTypes;
  parameters: FieldParameters;
  column?: number;
  required?: boolean | null;
  value?: unknown | null;
  dependsOn?: DependsOn | null;
};

/**
 * Section definition
 */
export type DynamicFormSectionInput = {
  id: string;
  name?: string | null;
  description?: string | null;
  layout?: SectionLayouts;
  fields: Array<DynamicFormFieldInput | unknown>;
  dependsOn?: DependsOn | null;
};

/**
 * Section definition
 */
export type DynamicFormSectionOutput = {
  id: string;
  name?: string | null;
  description?: string | null;
  layout?: SectionLayouts;
  fields: Array<DynamicFormFieldOutput | unknown>;
  dependsOn?: DependsOn | null;
};

/**
 * Base request schema for the dynamic form requests
 */
export type DynamicFormTemplateBaseSchema = {
  name: string;
  template?: boolean | null;
  formType: FormTypes;
  formDefinition: Array<DynamicFormFieldInput | DynamicFormSectionInput>;
  data?: Record<string, unknown> | null;
  productCompliance?: Array<string> | null;
  createdAt?: number | null;
  updatedAt?: number | null;
};

/**
 * Response schema for when a dynamic form template is created
 */
export type DynamicFormTemplateCreatedSchema = {
  id: string;
};

/**
 * Existing dynamic form schema
 */
export type ExistingDynamicFormSchemaInput = {
  name: string;
  template?: boolean | null;
  formType: FormTypes;
  formDefinition: Array<DynamicFormFieldInput | DynamicFormSectionInput>;
  data?: Record<string, unknown> | null;
  createdAt?: number | null;
  updatedAt?: number | null;
  id: string;
};

/**
 * Existing dynamic form schema
 */
export type ExistingDynamicFormSchemaOutput = {
  name: string;
  template?: boolean | null;
  formType: FormTypes;
  formDefinition: Array<DynamicFormFieldOutput | DynamicFormSectionOutput>;
  data?: Record<string, unknown> | null;
  createdAt?: number | null;
  updatedAt?: number | null;
  id: string;
  /**
   * Generate the dynamic form digest
   */
  readonly digest: string;
};

/**
 * Existing dynamic form template
 */
export type ExistingDynamicFormTemplateSchemaInput = {
  name: string;
  template?: boolean | null;
  formType: FormTypes;
  formDefinition: Array<DynamicFormFieldInput | DynamicFormSectionInput>;
  data?: Record<string, unknown> | null;
  productCompliance?: Array<string> | null;
  createdAt?: number | null;
  updatedAt?: number | null;
  id: string;
};

/**
 * Existing dynamic form template
 */
export type ExistingDynamicFormTemplateSchemaOutput = {
  name: string;
  template?: boolean | null;
  formType: FormTypes;
  formDefinition: Array<DynamicFormFieldOutput | DynamicFormSectionOutput>;
  data?: Record<string, unknown> | null;
  productCompliance?: Array<string> | null;
  createdAt?: number | null;
  updatedAt?: number | null;
  id: string;
};

/**
 * Existing file schema
 */
export type ExistingFileSchemaInput = {
  template?: boolean;
  fileMetadata?: Record<string, unknown> | null;
  fileType?: FileTypes | null;
  originalName: string;
  path?: string | null;
  createdAt?: number | null;
  updatedAt?: number | null;
  id: string;
  pdfGenerated?: boolean | null;
  pdfGeneratedAt?: number | null;
  thumbnailGenerated?: boolean | null;
  thumbnailGeneratedAt?: number | null;
  pageCount?: number | null;
  thumbnailUrl?: string | null;
  pdfUrl?: string | null;
  originalUrl?: string | null;
  description?: string | null;
};

/**
 * Existing file schema
 */
export type ExistingFileSchemaOutput = {
  template?: boolean;
  fileMetadata?: Record<string, unknown> | null;
  fileType?: FileTypes | null;
  originalName: string;
  path?: string | null;
  createdAt?: number | null;
  updatedAt?: number | null;
  id: string;
  pdfGenerated?: boolean | null;
  pdfGeneratedAt?: number | null;
  thumbnailGenerated?: boolean | null;
  thumbnailGeneratedAt?: number | null;
  pageCount?: number | null;
  thumbnailUrl?: string | null;
  pdfUrl?: string | null;
  originalUrl?: string | null;
  description?: string | null;
  /**
   * Generate the file digest
   */
  readonly digest: string;
};

/**
 * Existing template
 */
export type ExistingFileTemplateSchema = {
  template?: boolean;
  fileMetadata?: Record<string, unknown> | null;
  fileType?: FileTypes | null;
  originalName: string;
  path?: string | null;
  createdAt?: number | null;
  updatedAt?: number | null;
  description?: string | null;
  id: string;
  pdfGenerated?: boolean | null;
  pdfGeneratedAt?: number | null;
  thumbnailGenerated?: boolean | null;
  thumbnailGeneratedAt?: number | null;
  pageCount?: number | null;
  thumbnailUrl?: string | null;
  pdfUrl?: string | null;
  originalUrl?: string | null;
};

/**
 * Schema for existing form embedding
 */
export type ExistingFormEmbeddingSchema = {
  templateFormId: string;
  productId: string;
  customCss: string;
  domains: Array<string>;
  id: string;
  form: ExistingDynamicFormSchemaOutput;
  /**
   * Generate a nonce for use in the script embedding
   */
  readonly nonce: string;
};

/**
 * Schema for existing form embedding with a CSRF token
 */
export type ExistingFormEmbeddingSchemaWithCsrfToken = {
  templateFormId: string;
  productId: string;
  customCss: string;
  domains: Array<string>;
  id: string;
  form: ExistingDynamicFormSchemaOutput;
  csrfToken: string;
  /**
   * Generate a nonce for use in the script embedding
   */
  readonly nonce: string;
};

/**
 * Existing signature schema
 */
export type ExistingSignatureSchema = {
  targetId: string;
  targetType: SignatureTargets;
  signatoryId: string;
  signatoryType: SignatoryTypes;
  signature?: string | null;
  signatureDate?: number | null;
  id: string;
  /**
   * Generate the dignature digest
   */
  readonly digest: string;
};

/**
 * Options for fields that can contain options (select, radio)
 */
export type FieldOption = {
  label: string;
  value: string;
  description: string;
};

/**
 * Parameters that can be set on fields
 */
export type FieldParameters = {
  options?: Array<FieldOption> | null;
  decimalPrecision: number | null;
  minimumLength: number | null;
  maximumLength: number | null;
  minimumValue: number | null;
  maximumValue: number | null;
  type: string | null;
  placeholder: string | null;
  validator: string | null;
};

/**
 * Field types
 */
export type FieldTypes =
  | 'INPUT'
  | 'DATE'
  | 'TEXT'
  | 'MONEY'
  | 'NUMBER'
  | 'RADIO'
  | 'SELECT'
  | 'CHECKBOX'
  | 'LOAN_INFORMATION'
  | 'LOAN_PURPOSE'
  | 'LOAN_SOURCES'
  | 'CREDIT_CHECK'
  | 'SUBMIT_BUTTON';

/**
 * Field types
 */
export const FieldTypes = {
  INPUT: 'INPUT',
  DATE: 'DATE',
  TEXT: 'TEXT',
  MONEY: 'MONEY',
  NUMBER: 'NUMBER',
  RADIO: 'RADIO',
  SELECT: 'SELECT',
  CHECKBOX: 'CHECKBOX',
  LOAN_INFORMATION: 'LOAN_INFORMATION',
  LOAN_PURPOSE: 'LOAN_PURPOSE',
  LOAN_SOURCES: 'LOAN_SOURCES',
  CREDIT_CHECK: 'CREDIT_CHECK',
  SUBMIT_BUTTON: 'SUBMIT_BUTTON',
} as const;

/**
 * Base request schema for the file requests
 */
export type FileBaseSchema = {
  template?: boolean;
  fileMetadata?: Record<string, unknown> | null;
  fileType?: FileTypes | null;
  originalName: string;
  path?: string | null;
  createdAt?: number | null;
  updatedAt?: number | null;
};

/**
 * Response schema for when a file is created
 */
export type FileCreatedSchema = {
  id: string;
  originalName?: string | null;
  /**
   * Generate the file digest
   */
  readonly digest: string;
};

/**
 * Template base schema
 */
export type FileTemplateBaseSchema = {
  template?: boolean;
  fileMetadata?: Record<string, unknown> | null;
  fileType?: FileTypes | null;
  originalName: string;
  path?: string | null;
  createdAt?: number | null;
  updatedAt?: number | null;
  description?: string | null;
};

/**
 * Response schema for when a file template batch is cloned
 */
export type FileTemplateCloneSchema = {
  id: string;
  originalName?: string | null;
  originalId: string;
};

/**
 * Response schema for when a file template is created
 */
export type FileTemplateCreatedSchema = {
  id: string;
  originalName?: string | null;
};

/**
 * Types of files
 */
export type FileTypes = 'WORD' | 'EXCEL' | 'PDF' | 'IMAGE' | 'ARCHIVE' | 'ANY';

/**
 * Types of files
 */
export const FileTypes = {
  WORD: 'WORD',
  EXCEL: 'EXCEL',
  PDF: 'PDF',
  IMAGE: 'IMAGE',
  ARCHIVE: 'ARCHIVE',
  ANY: 'ANY',
} as const;

/**
 * Types of forms
 */
export type FormTypes = 'INLINE' | 'TABS' | 'STEPS';

/**
 * Types of forms
 */
export const FormTypes = {
  INLINE: 'INLINE',
  TABS: 'TABS',
  STEPS: 'STEPS',
} as const;

export type HttpValidationError = {
  detail?: Array<ValidationError>;
};

/**
 * This class represents the base schema for Llm S
 */
export type LlmInput = {
  conversationId: string;
  prompt: string;
};

/**
 * This class represents the base schema for Llm S
 */
export type LlmOutput = {
  conversationId: string;
  prompt: string;
  response: unknown;
};

/**
 * Layout that a section can display fields
 */
export type SectionLayouts = 'ONE_COLUMN' | 'TWO_COLUMNS' | 'THREE_COLUMN';

/**
 * Layout that a section can display fields
 */
export const SectionLayouts = {
  ONE_COLUMN: 'ONE_COLUMN',
  TWO_COLUMNS: 'TWO_COLUMNS',
  THREE_COLUMN: 'THREE_COLUMN',
} as const;

/**
 * Types of signatory
 */
export type SignatoryTypes = 'USER' | 'GROUP';

/**
 * Types of signatory
 */
export const SignatoryTypes = {
  USER: 'USER',
  GROUP: 'GROUP',
} as const;

/**
 * Base request schema for the signature requests
 */
export type SignatureBaseSchema = {
  targetId: string;
  targetType: SignatureTargets;
  signatoryId: string;
  signatoryType: SignatoryTypes;
  signature?: string | null;
  signatureDate?: number | null;
};

/**
 * Response schema for when a signature is created
 */
export type SignatureCreatedSchema = {
  id: string;
};

/**
 * Types of target for a signature
 */
export type SignatureTargets =
  | 'APPLICATION'
  | 'REQUEST'
  | 'DOCUMENT'
  | 'FILE'
  | 'DYNAMIC_FORM';

/**
 * Types of target for a signature
 */
export const SignatureTargets = {
  APPLICATION: 'APPLICATION',
  REQUEST: 'REQUEST',
  DOCUMENT: 'DOCUMENT',
  FILE: 'FILE',
  DYNAMIC_FORM: 'DYNAMIC_FORM',
} as const;

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type CreateFileMetadataFilesPostData = {
  body: FileBaseSchema;
  path?: never;
  query?: never;
  url: '/files';
};

export type CreateFileMetadataFilesPostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateFileMetadataFilesPostError =
  CreateFileMetadataFilesPostErrors[keyof CreateFileMetadataFilesPostErrors];

export type CreateFileMetadataFilesPostResponses = {
  /**
   * Successful Response
   */
  200: FileCreatedSchema;
};

export type CreateFileMetadataFilesPostResponse =
  CreateFileMetadataFilesPostResponses[keyof CreateFileMetadataFilesPostResponses];

export type CreateBatchFileMetadataFilesBatchPostData = {
  body: Array<FileBaseSchema>;
  path?: never;
  query?: never;
  url: '/files/batch';
};

export type CreateBatchFileMetadataFilesBatchPostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateBatchFileMetadataFilesBatchPostError =
  CreateBatchFileMetadataFilesBatchPostErrors[keyof CreateBatchFileMetadataFilesBatchPostErrors];

export type CreateBatchFileMetadataFilesBatchPostResponses = {
  /**
   * Successful Response
   */
  200: Array<FileCreatedSchema>;
};

export type CreateBatchFileMetadataFilesBatchPostResponse =
  CreateBatchFileMetadataFilesBatchPostResponses[keyof CreateBatchFileMetadataFilesBatchPostResponses];

export type DeleteFileMetadataFilesFileIdDeleteData = {
  body?: never;
  path: {
    fileId: string;
  };
  query?: never;
  url: '/files/{file_id}';
};

export type DeleteFileMetadataFilesFileIdDeleteErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteFileMetadataFilesFileIdDeleteError =
  DeleteFileMetadataFilesFileIdDeleteErrors[keyof DeleteFileMetadataFilesFileIdDeleteErrors];

export type DeleteFileMetadataFilesFileIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetFileMetadataFilesFileIdGetData = {
  body?: never;
  path: {
    fileId: string;
  };
  query?: never;
  url: '/files/{file_id}';
};

export type GetFileMetadataFilesFileIdGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetFileMetadataFilesFileIdGetError =
  GetFileMetadataFilesFileIdGetErrors[keyof GetFileMetadataFilesFileIdGetErrors];

export type GetFileMetadataFilesFileIdGetResponses = {
  /**
   * Successful Response
   */
  200: ExistingFileSchemaOutput;
};

export type GetFileMetadataFilesFileIdGetResponse =
  GetFileMetadataFilesFileIdGetResponses[keyof GetFileMetadataFilesFileIdGetResponses];

export type GetHeadFileMetadataFilesFileIdHeadData = {
  body?: never;
  path: {
    fileId: string;
  };
  query?: never;
  url: '/files/{file_id}';
};

export type GetHeadFileMetadataFilesFileIdHeadErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetHeadFileMetadataFilesFileIdHeadError =
  GetHeadFileMetadataFilesFileIdHeadErrors[keyof GetHeadFileMetadataFilesFileIdHeadErrors];

export type GetHeadFileMetadataFilesFileIdHeadResponses = {
  /**
   * Successful Response
   */
  200: ExistingFileSchemaOutput;
};

export type GetHeadFileMetadataFilesFileIdHeadResponse =
  GetHeadFileMetadataFilesFileIdHeadResponses[keyof GetHeadFileMetadataFilesFileIdHeadResponses];

export type UpdateFileMetadataFilesFileIdPutData = {
  body: ExistingFileSchemaInput;
  path: {
    fileId: string;
  };
  query?: never;
  url: '/files/{file_id}';
};

export type UpdateFileMetadataFilesFileIdPutErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateFileMetadataFilesFileIdPutError =
  UpdateFileMetadataFilesFileIdPutErrors[keyof UpdateFileMetadataFilesFileIdPutErrors];

export type UpdateFileMetadataFilesFileIdPutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PostUploadFileFilesFileIdUploadPostData = {
  body?: never;
  path: {
    fileId: string;
  };
  query?: never;
  url: '/files/{file_id}/upload';
};

export type PostUploadFileFilesFileIdUploadPostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PostUploadFileFilesFileIdUploadPostError =
  PostUploadFileFilesFileIdUploadPostErrors[keyof PostUploadFileFilesFileIdUploadPostErrors];

export type PostUploadFileFilesFileIdUploadPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PutUploadFileFilesFileIdUploadPutData = {
  body?: never;
  path: {
    fileId: string;
  };
  query?: never;
  url: '/files/{file_id}/upload';
};

export type PutUploadFileFilesFileIdUploadPutErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PutUploadFileFilesFileIdUploadPutError =
  PutUploadFileFilesFileIdUploadPutErrors[keyof PutUploadFileFilesFileIdUploadPutErrors];

export type PutUploadFileFilesFileIdUploadPutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DownloadFileFilesFileIdDownloadGetData = {
  body?: never;
  path: {
    fileId: string;
  };
  query?: {
    redirect?: boolean;
    pdfConversion?: boolean;
  };
  url: '/files/{file_id}/download';
};

export type DownloadFileFilesFileIdDownloadGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DownloadFileFilesFileIdDownloadGetError =
  DownloadFileFilesFileIdDownloadGetErrors[keyof DownloadFileFilesFileIdDownloadGetErrors];

export type DownloadFileFilesFileIdDownloadGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type TriggerConversionFilesFileIdConvertPostData = {
  body?: never;
  path: {
    fileId: string;
  };
  query?: never;
  url: '/files/{file_id}/convert';
};

export type TriggerConversionFilesFileIdConvertPostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TriggerConversionFilesFileIdConvertPostError =
  TriggerConversionFilesFileIdConvertPostErrors[keyof TriggerConversionFilesFileIdConvertPostErrors];

export type TriggerConversionFilesFileIdConvertPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type CreateFormFormsPostData = {
  body: DynamicFormBaseSchema;
  path?: never;
  query?: never;
  url: '/forms';
};

export type CreateFormFormsPostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateFormFormsPostError =
  CreateFormFormsPostErrors[keyof CreateFormFormsPostErrors];

export type CreateFormFormsPostResponses = {
  /**
   * Successful Response
   */
  200: DynamicFormCreatedSchema;
};

export type CreateFormFormsPostResponse =
  CreateFormFormsPostResponses[keyof CreateFormFormsPostResponses];

export type DeleteFormFormsDynamicFormIdDeleteData = {
  body?: never;
  path: {
    dynamicFormId: string;
  };
  query?: never;
  url: '/forms/{dynamic_form_id}';
};

export type DeleteFormFormsDynamicFormIdDeleteErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteFormFormsDynamicFormIdDeleteError =
  DeleteFormFormsDynamicFormIdDeleteErrors[keyof DeleteFormFormsDynamicFormIdDeleteErrors];

export type DeleteFormFormsDynamicFormIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetFormFormsDynamicFormIdGetData = {
  body?: never;
  path: {
    dynamicFormId: string;
  };
  query?: never;
  url: '/forms/{dynamic_form_id}';
};

export type GetFormFormsDynamicFormIdGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetFormFormsDynamicFormIdGetError =
  GetFormFormsDynamicFormIdGetErrors[keyof GetFormFormsDynamicFormIdGetErrors];

export type GetFormFormsDynamicFormIdGetResponses = {
  /**
   * Successful Response
   */
  200: ExistingDynamicFormSchemaOutput;
};

export type GetFormFormsDynamicFormIdGetResponse =
  GetFormFormsDynamicFormIdGetResponses[keyof GetFormFormsDynamicFormIdGetResponses];

export type UpdateFormFormsDynamicFormIdPutData = {
  body: ExistingDynamicFormSchemaInput;
  path: {
    dynamicFormId: string;
  };
  query?: never;
  url: '/forms/{dynamic_form_id}';
};

export type UpdateFormFormsDynamicFormIdPutErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateFormFormsDynamicFormIdPutError =
  UpdateFormFormsDynamicFormIdPutErrors[keyof UpdateFormFormsDynamicFormIdPutErrors];

export type UpdateFormFormsDynamicFormIdPutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type SearchSearchGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/search/';
};

export type SearchSearchGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
};

export type SearchSearchGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type CreateSignatureSignaturesPostData = {
  body: SignatureBaseSchema;
  path?: never;
  query?: never;
  url: '/signatures';
};

export type CreateSignatureSignaturesPostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateSignatureSignaturesPostError =
  CreateSignatureSignaturesPostErrors[keyof CreateSignatureSignaturesPostErrors];

export type CreateSignatureSignaturesPostResponses = {
  /**
   * Successful Response
   */
  200: SignatureCreatedSchema;
};

export type CreateSignatureSignaturesPostResponse =
  CreateSignatureSignaturesPostResponses[keyof CreateSignatureSignaturesPostResponses];

export type DeleteSignatureSignaturesSignatureIdDeleteData = {
  body?: never;
  path: {
    signatureId: string;
  };
  query?: never;
  url: '/signatures/{signature_id}';
};

export type DeleteSignatureSignaturesSignatureIdDeleteErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteSignatureSignaturesSignatureIdDeleteError =
  DeleteSignatureSignaturesSignatureIdDeleteErrors[keyof DeleteSignatureSignaturesSignatureIdDeleteErrors];

export type DeleteSignatureSignaturesSignatureIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetSignatureSignaturesSignatureIdGetData = {
  body?: never;
  path: {
    signatureId: string;
  };
  query?: never;
  url: '/signatures/{signature_id}';
};

export type GetSignatureSignaturesSignatureIdGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetSignatureSignaturesSignatureIdGetError =
  GetSignatureSignaturesSignatureIdGetErrors[keyof GetSignatureSignaturesSignatureIdGetErrors];

export type GetSignatureSignaturesSignatureIdGetResponses = {
  /**
   * Successful Response
   */
  200: ExistingSignatureSchema;
};

export type GetSignatureSignaturesSignatureIdGetResponse =
  GetSignatureSignaturesSignatureIdGetResponses[keyof GetSignatureSignaturesSignatureIdGetResponses];

export type GetAllTemplateMetadataTemplatesFilesGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/templates/files';
};

export type GetAllTemplateMetadataTemplatesFilesGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
};

export type GetAllTemplateMetadataTemplatesFilesGetResponses = {
  /**
   * Successful Response
   */
  200: Array<ExistingFileTemplateSchema>;
};

export type GetAllTemplateMetadataTemplatesFilesGetResponse =
  GetAllTemplateMetadataTemplatesFilesGetResponses[keyof GetAllTemplateMetadataTemplatesFilesGetResponses];

export type CreateTemplateMetadataTemplatesFilesPostData = {
  body: FileTemplateBaseSchema;
  path?: never;
  query?: never;
  url: '/templates/files';
};

export type CreateTemplateMetadataTemplatesFilesPostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTemplateMetadataTemplatesFilesPostError =
  CreateTemplateMetadataTemplatesFilesPostErrors[keyof CreateTemplateMetadataTemplatesFilesPostErrors];

export type CreateTemplateMetadataTemplatesFilesPostResponses = {
  /**
   * Successful Response
   */
  200: FileTemplateCreatedSchema;
};

export type CreateTemplateMetadataTemplatesFilesPostResponse =
  CreateTemplateMetadataTemplatesFilesPostResponses[keyof CreateTemplateMetadataTemplatesFilesPostResponses];

export type CreateBatchFileTemplateTemplatesFilesBatchPostData = {
  body: Array<FileTemplateBaseSchema>;
  path?: never;
  query?: never;
  url: '/templates/files/batch';
};

export type CreateBatchFileTemplateTemplatesFilesBatchPostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateBatchFileTemplateTemplatesFilesBatchPostError =
  CreateBatchFileTemplateTemplatesFilesBatchPostErrors[keyof CreateBatchFileTemplateTemplatesFilesBatchPostErrors];

export type CreateBatchFileTemplateTemplatesFilesBatchPostResponses = {
  /**
   * Successful Response
   */
  200: Array<FileTemplateCreatedSchema>;
};

export type CreateBatchFileTemplateTemplatesFilesBatchPostResponse =
  CreateBatchFileTemplateTemplatesFilesBatchPostResponses[keyof CreateBatchFileTemplateTemplatesFilesBatchPostResponses];

export type DeleteTemplateMetadataTemplatesFilesTemplateIdDeleteData = {
  body?: never;
  path: {
    templateId: string;
  };
  query?: never;
  url: '/templates/files/{template_id}';
};

export type DeleteTemplateMetadataTemplatesFilesTemplateIdDeleteErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTemplateMetadataTemplatesFilesTemplateIdDeleteError =
  DeleteTemplateMetadataTemplatesFilesTemplateIdDeleteErrors[keyof DeleteTemplateMetadataTemplatesFilesTemplateIdDeleteErrors];

export type DeleteTemplateMetadataTemplatesFilesTemplateIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetTemplateMetadataTemplatesFilesTemplateIdGetData = {
  body?: never;
  path: {
    templateId: string;
  };
  query?: never;
  url: '/templates/files/{template_id}';
};

export type GetTemplateMetadataTemplatesFilesTemplateIdGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTemplateMetadataTemplatesFilesTemplateIdGetError =
  GetTemplateMetadataTemplatesFilesTemplateIdGetErrors[keyof GetTemplateMetadataTemplatesFilesTemplateIdGetErrors];

export type GetTemplateMetadataTemplatesFilesTemplateIdGetResponses = {
  /**
   * Successful Response
   */
  200: ExistingFileTemplateSchema;
};

export type GetTemplateMetadataTemplatesFilesTemplateIdGetResponse =
  GetTemplateMetadataTemplatesFilesTemplateIdGetResponses[keyof GetTemplateMetadataTemplatesFilesTemplateIdGetResponses];

export type UpdateTemplateMetadataTemplatesFilesTemplateIdPutData = {
  body: ExistingFileTemplateSchema;
  path: {
    templateId: string;
  };
  query?: never;
  url: '/templates/files/{template_id}';
};

export type UpdateTemplateMetadataTemplatesFilesTemplateIdPutErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTemplateMetadataTemplatesFilesTemplateIdPutError =
  UpdateTemplateMetadataTemplatesFilesTemplateIdPutErrors[keyof UpdateTemplateMetadataTemplatesFilesTemplateIdPutErrors];

export type UpdateTemplateMetadataTemplatesFilesTemplateIdPutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PostUploadTemplateTemplatesFilesTemplateIdUploadPostData = {
  body?: never;
  path: {
    templateId: string;
  };
  query?: never;
  url: '/templates/files/{template_id}/upload';
};

export type PostUploadTemplateTemplatesFilesTemplateIdUploadPostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PostUploadTemplateTemplatesFilesTemplateIdUploadPostError =
  PostUploadTemplateTemplatesFilesTemplateIdUploadPostErrors[keyof PostUploadTemplateTemplatesFilesTemplateIdUploadPostErrors];

export type PostUploadTemplateTemplatesFilesTemplateIdUploadPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PutUploadTemplateTemplatesFilesTemplateIdUploadPutData = {
  body?: never;
  path: {
    templateId: string;
  };
  query?: never;
  url: '/templates/files/{template_id}/upload';
};

export type PutUploadTemplateTemplatesFilesTemplateIdUploadPutErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PutUploadTemplateTemplatesFilesTemplateIdUploadPutError =
  PutUploadTemplateTemplatesFilesTemplateIdUploadPutErrors[keyof PutUploadTemplateTemplatesFilesTemplateIdUploadPutErrors];

export type PutUploadTemplateTemplatesFilesTemplateIdUploadPutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DownloadTemplateTemplatesFilesTemplateIdDownloadGetData = {
  body?: never;
  path: {
    templateId: string;
  };
  query?: {
    redirect?: boolean;
    pdfConversion?: boolean;
  };
  url: '/templates/files/{template_id}/download';
};

export type DownloadTemplateTemplatesFilesTemplateIdDownloadGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DownloadTemplateTemplatesFilesTemplateIdDownloadGetError =
  DownloadTemplateTemplatesFilesTemplateIdDownloadGetErrors[keyof DownloadTemplateTemplatesFilesTemplateIdDownloadGetErrors];

export type DownloadTemplateTemplatesFilesTemplateIdDownloadGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type CloneTemplateTemplatesFilesTemplateIdClonePostData = {
  body?: never;
  path: {
    templateId: string;
  };
  query?: never;
  url: '/templates/files/{template_id}/clone';
};

export type CloneTemplateTemplatesFilesTemplateIdClonePostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CloneTemplateTemplatesFilesTemplateIdClonePostError =
  CloneTemplateTemplatesFilesTemplateIdClonePostErrors[keyof CloneTemplateTemplatesFilesTemplateIdClonePostErrors];

export type CloneTemplateTemplatesFilesTemplateIdClonePostResponses = {
  /**
   * Successful Response
   */
  200: FileTemplateCreatedSchema;
};

export type CloneTemplateTemplatesFilesTemplateIdClonePostResponse =
  CloneTemplateTemplatesFilesTemplateIdClonePostResponses[keyof CloneTemplateTemplatesFilesTemplateIdClonePostResponses];

export type CloneTemplateBatchTemplatesFilesCloneBatchPostData = {
  body: Array<string>;
  path?: never;
  query?: never;
  url: '/templates/files/clone/batch';
};

export type CloneTemplateBatchTemplatesFilesCloneBatchPostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CloneTemplateBatchTemplatesFilesCloneBatchPostError =
  CloneTemplateBatchTemplatesFilesCloneBatchPostErrors[keyof CloneTemplateBatchTemplatesFilesCloneBatchPostErrors];

export type CloneTemplateBatchTemplatesFilesCloneBatchPostResponses = {
  /**
   * Successful Response
   */
  200: Array<FileTemplateCloneSchema>;
};

export type CloneTemplateBatchTemplatesFilesCloneBatchPostResponse =
  CloneTemplateBatchTemplatesFilesCloneBatchPostResponses[keyof CloneTemplateBatchTemplatesFilesCloneBatchPostResponses];

export type TriggerConversionTemplatesFilesTemplateIdConvertPostData = {
  body?: never;
  path: {
    templateId: string;
  };
  query?: never;
  url: '/templates/files/{template_id}/convert';
};

export type TriggerConversionTemplatesFilesTemplateIdConvertPostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TriggerConversionTemplatesFilesTemplateIdConvertPostError =
  TriggerConversionTemplatesFilesTemplateIdConvertPostErrors[keyof TriggerConversionTemplatesFilesTemplateIdConvertPostErrors];

export type TriggerConversionTemplatesFilesTemplateIdConvertPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetAllFormTemplatesTemplatesFormsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/templates/forms';
};

export type GetAllFormTemplatesTemplatesFormsGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
};

export type GetAllFormTemplatesTemplatesFormsGetResponses = {
  /**
   * Successful Response
   */
  200: Array<ExistingDynamicFormTemplateSchemaOutput>;
};

export type GetAllFormTemplatesTemplatesFormsGetResponse =
  GetAllFormTemplatesTemplatesFormsGetResponses[keyof GetAllFormTemplatesTemplatesFormsGetResponses];

export type CreateFormTemplateTemplatesFormsPostData = {
  body: DynamicFormTemplateBaseSchema;
  path?: never;
  query?: never;
  url: '/templates/forms';
};

export type CreateFormTemplateTemplatesFormsPostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateFormTemplateTemplatesFormsPostError =
  CreateFormTemplateTemplatesFormsPostErrors[keyof CreateFormTemplateTemplatesFormsPostErrors];

export type CreateFormTemplateTemplatesFormsPostResponses = {
  /**
   * Successful Response
   */
  200: DynamicFormTemplateCreatedSchema;
};

export type CreateFormTemplateTemplatesFormsPostResponse =
  CreateFormTemplateTemplatesFormsPostResponses[keyof CreateFormTemplateTemplatesFormsPostResponses];

export type DeleteFormTemplateTemplatesFormsTemplateIdDeleteData = {
  body?: never;
  path: {
    templateId: string;
  };
  query?: never;
  url: '/templates/forms/{template_id}';
};

export type DeleteFormTemplateTemplatesFormsTemplateIdDeleteErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteFormTemplateTemplatesFormsTemplateIdDeleteError =
  DeleteFormTemplateTemplatesFormsTemplateIdDeleteErrors[keyof DeleteFormTemplateTemplatesFormsTemplateIdDeleteErrors];

export type DeleteFormTemplateTemplatesFormsTemplateIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetFormTemplateTemplatesFormsTemplateIdGetData = {
  body?: never;
  path: {
    templateId: string;
  };
  query?: never;
  url: '/templates/forms/{template_id}';
};

export type GetFormTemplateTemplatesFormsTemplateIdGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetFormTemplateTemplatesFormsTemplateIdGetError =
  GetFormTemplateTemplatesFormsTemplateIdGetErrors[keyof GetFormTemplateTemplatesFormsTemplateIdGetErrors];

export type GetFormTemplateTemplatesFormsTemplateIdGetResponses = {
  /**
   * Successful Response
   */
  200: ExistingDynamicFormTemplateSchemaOutput;
};

export type GetFormTemplateTemplatesFormsTemplateIdGetResponse =
  GetFormTemplateTemplatesFormsTemplateIdGetResponses[keyof GetFormTemplateTemplatesFormsTemplateIdGetResponses];

export type UpdateFormTemplateTemplatesFormsTemplateIdPutData = {
  body: ExistingDynamicFormTemplateSchemaInput;
  path: {
    templateId: string;
  };
  query?: never;
  url: '/templates/forms/{template_id}';
};

export type UpdateFormTemplateTemplatesFormsTemplateIdPutErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateFormTemplateTemplatesFormsTemplateIdPutError =
  UpdateFormTemplateTemplatesFormsTemplateIdPutErrors[keyof UpdateFormTemplateTemplatesFormsTemplateIdPutErrors];

export type UpdateFormTemplateTemplatesFormsTemplateIdPutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetEmbeddingFormsExternalFormsGetData = {
  body?: never;
  path?: never;
  query?: {
    productId?: string | null;
    templateFormId?: string | null;
    page?: number;
    pageSize?: number;
  };
  url: '/external/forms';
};

export type GetEmbeddingFormsExternalFormsGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetEmbeddingFormsExternalFormsGetError =
  GetEmbeddingFormsExternalFormsGetErrors[keyof GetEmbeddingFormsExternalFormsGetErrors];

export type GetEmbeddingFormsExternalFormsGetResponses = {
  /**
   * Successful Response
   */
  200: Array<ExistingFormEmbeddingSchema>;
};

export type GetEmbeddingFormsExternalFormsGetResponse =
  GetEmbeddingFormsExternalFormsGetResponses[keyof GetEmbeddingFormsExternalFormsGetResponses];

export type CreateEmbeddingFormExternalFormsPostData = {
  body: CreateDynamicFormEmbeddingSchema;
  path?: never;
  query?: never;
  url: '/external/forms';
};

export type CreateEmbeddingFormExternalFormsPostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateEmbeddingFormExternalFormsPostError =
  CreateEmbeddingFormExternalFormsPostErrors[keyof CreateEmbeddingFormExternalFormsPostErrors];

export type CreateEmbeddingFormExternalFormsPostResponses = {
  /**
   * Successful Response
   */
  200: DynamicFormEmbeddingCreatedSchema;
};

export type CreateEmbeddingFormExternalFormsPostResponse =
  CreateEmbeddingFormExternalFormsPostResponses[keyof CreateEmbeddingFormExternalFormsPostResponses];

export type DeleteEmbeddingFormExternalFormsEmbeddingFormIdDeleteData = {
  body?: never;
  path: {
    embeddingFormId: string;
  };
  query?: never;
  url: '/external/forms/{embedding_form_id}';
};

export type DeleteEmbeddingFormExternalFormsEmbeddingFormIdDeleteErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteEmbeddingFormExternalFormsEmbeddingFormIdDeleteError =
  DeleteEmbeddingFormExternalFormsEmbeddingFormIdDeleteErrors[keyof DeleteEmbeddingFormExternalFormsEmbeddingFormIdDeleteErrors];

export type DeleteEmbeddingFormExternalFormsEmbeddingFormIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetEmbeddingFormExternalFormsEmbeddingFormIdGetData = {
  body?: never;
  path: {
    embeddingFormId: string;
  };
  query?: never;
  url: '/external/forms/{embedding_form_id}';
};

export type GetEmbeddingFormExternalFormsEmbeddingFormIdGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetEmbeddingFormExternalFormsEmbeddingFormIdGetError =
  GetEmbeddingFormExternalFormsEmbeddingFormIdGetErrors[keyof GetEmbeddingFormExternalFormsEmbeddingFormIdGetErrors];

export type GetEmbeddingFormExternalFormsEmbeddingFormIdGetResponses = {
  /**
   * Successful Response
   */
  200: ExistingFormEmbeddingSchema;
};

export type GetEmbeddingFormExternalFormsEmbeddingFormIdGetResponse =
  GetEmbeddingFormExternalFormsEmbeddingFormIdGetResponses[keyof GetEmbeddingFormExternalFormsEmbeddingFormIdGetResponses];

export type UpdateEmbeddingFormExternalFormsEmbeddingFormIdPutData = {
  body: CreateDynamicFormEmbeddingSchema;
  path: {
    embeddingFormId: string;
  };
  query?: never;
  url: '/external/forms/{embedding_form_id}';
};

export type UpdateEmbeddingFormExternalFormsEmbeddingFormIdPutErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateEmbeddingFormExternalFormsEmbeddingFormIdPutError =
  UpdateEmbeddingFormExternalFormsEmbeddingFormIdPutErrors[keyof UpdateEmbeddingFormExternalFormsEmbeddingFormIdPutErrors];

export type UpdateEmbeddingFormExternalFormsEmbeddingFormIdPutResponses = {
  /**
   * Successful Response
   */
  200: DynamicFormEmbeddingCreatedSchema;
};

export type UpdateEmbeddingFormExternalFormsEmbeddingFormIdPutResponse =
  UpdateEmbeddingFormExternalFormsEmbeddingFormIdPutResponses[keyof UpdateEmbeddingFormExternalFormsEmbeddingFormIdPutResponses];

export type GetFormEmbeddingExternalFormsDefinitionEmbeddingFormIdGetData = {
  body?: never;
  path: {
    embeddingFormId: string;
  };
  query?: {
    signature?: string;
    organization?: string;
  };
  url: '/external/forms/definition/{embedding_form_id}';
};

export type GetFormEmbeddingExternalFormsDefinitionEmbeddingFormIdGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetFormEmbeddingExternalFormsDefinitionEmbeddingFormIdGetError =
  GetFormEmbeddingExternalFormsDefinitionEmbeddingFormIdGetErrors[keyof GetFormEmbeddingExternalFormsDefinitionEmbeddingFormIdGetErrors];

export type GetFormEmbeddingExternalFormsDefinitionEmbeddingFormIdGetResponses =
  {
    /**
     * Successful Response
     */
    200: ExistingFormEmbeddingSchemaWithCsrfToken;
  };

export type GetFormEmbeddingExternalFormsDefinitionEmbeddingFormIdGetResponse =
  GetFormEmbeddingExternalFormsDefinitionEmbeddingFormIdGetResponses[keyof GetFormEmbeddingExternalFormsDefinitionEmbeddingFormIdGetResponses];

export type GetFormEmbedScriptExternalFormsEmbeddingFormIdFormJsGetData = {
  body?: never;
  path: {
    embeddingFormId: string;
  };
  query?: never;
  url: '/external/forms/{embedding_form_id}/form.js';
};

export type GetFormEmbedScriptExternalFormsEmbeddingFormIdFormJsGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetFormEmbedScriptExternalFormsEmbeddingFormIdFormJsGetError =
  GetFormEmbedScriptExternalFormsEmbeddingFormIdFormJsGetErrors[keyof GetFormEmbedScriptExternalFormsEmbeddingFormIdFormJsGetErrors];

export type GetFormEmbedScriptExternalFormsEmbeddingFormIdFormJsGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type CreateFormExternalFormsSubmitPostData = {
  body: DynamicFormBaseSchema;
  path?: never;
  query?: never;
  url: '/external/forms/submit';
};

export type CreateFormExternalFormsSubmitPostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateFormExternalFormsSubmitPostError =
  CreateFormExternalFormsSubmitPostErrors[keyof CreateFormExternalFormsSubmitPostErrors];

export type CreateFormExternalFormsSubmitPostResponses = {
  /**
   * Successful Response
   */
  200: DynamicFormCreatedSchema;
};

export type CreateFormExternalFormsSubmitPostResponse =
  CreateFormExternalFormsSubmitPostResponses[keyof CreateFormExternalFormsSubmitPostResponses];

export type CreateDocumentDescriptionDocumentAnalysisDocumentIdPostData = {
  body?: never;
  path: {
    documentId: string;
  };
  query?: never;
  url: '/document-analysis/{document_id}';
};

export type CreateDocumentDescriptionDocumentAnalysisDocumentIdPostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateDocumentDescriptionDocumentAnalysisDocumentIdPostError =
  CreateDocumentDescriptionDocumentAnalysisDocumentIdPostErrors[keyof CreateDocumentDescriptionDocumentAnalysisDocumentIdPostErrors];

export type CreateDocumentDescriptionDocumentAnalysisDocumentIdPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ApiConverseConversationFilesFileIdLlmPostData = {
  body: LlmInput;
  path: {
    fileId: string;
  };
  query?: never;
  url: '/conversation/files/{file_id}/llm';
};

export type ApiConverseConversationFilesFileIdLlmPostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ApiConverseConversationFilesFileIdLlmPostError =
  ApiConverseConversationFilesFileIdLlmPostErrors[keyof ApiConverseConversationFilesFileIdLlmPostErrors];

export type ApiConverseConversationFilesFileIdLlmPostResponses = {
  /**
   * Successful Response
   */
  200: LlmOutput;
};

export type ApiConverseConversationFilesFileIdLlmPostResponse =
  ApiConverseConversationFilesFileIdLlmPostResponses[keyof ApiConverseConversationFilesFileIdLlmPostResponses];

export type GetRootGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/';
};

export type GetRootGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetStatusCheckStatusGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/status';
};

export type GetStatusCheckStatusGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};
