export interface Fee {
  id?: string;
  amount?: string | null;
  amountApplicationRule: string;
  amountType: string;
  assessAfterMaturity: boolean;
  category: string;
  deferredFeeAmountCents?: number | null;
  deferredFeeCostAmountCents?: number | null;
  deferredFeeCostRateBps?: string | null;
  deferredFeeRateBps?: string | null;
  deferredTermCount?: number | null;
  deferredTermUnits: string;
  earningMethod: string;
  feeComputeSource: string;
  frequencyStartDate?: number | null;
  frequencyEndDate?: number | null;
  frequencyValue?: number | null;
  frequencyUnit: string;
  globalActivationDate?: number | null;
  globalDeactivationDate?: number | null;
  isDeferrable: boolean;
  maxApplicableCents?: number | null;
  minApplicableCents?: number | null;
  name?: string | null;
  roundingMethod: string;
  triggers: string[];
  triggerData: Record<string, unknown>;
  createdAt?: number;
  updatedAt?: number | null;
  disabled?: boolean;
  disabledDate?: number | null;
  disabledReason?: string | null;
}

export interface FeeSearchParams {
  id?: string[] | null;
  amount?: string[] | null;
  amountRange?: readonly [string, string] | null;
  amountApplicationRule?: string[] | null;
  amountType?: string[] | null;
  assessAfterMaturity?: boolean | null;
  category?: string[] | null;
  deferredFeeAmountCents?: number[] | null;
  deferredFeeAmountCentsRange?: readonly [number, number] | null;
  deferredFeeCostAmountCents?: number[] | null;
  deferredFeeCostAmountCentsRange?: readonly [number, number] | null;
  deferredFeeCostRateBps?: string[] | null;
  deferredFeeCostRateBpsRange?: readonly [string, string] | null;
  deferredFeeRateBps?: string[] | null;
  deferredFeeRateBpsRange?: readonly [string, string] | null;
  deferredTermCount?: number[] | null;
  deferredTermCountRange?: readonly [number, number] | null;
  deferredTermUnits?: string[] | null;
  earningMethod?: string[] | null;
  feeComputeSource?: string[] | null;
  frequencyStartDate?: number[] | null;
  frequencyStartDateRange?: readonly [number, number] | null;
  frequencyEndDate?: number[] | null;
  frequencyEndDateRange?: readonly [number, number] | null;
  frequencyValue?: number[] | null;
  frequencyValueRange?: readonly [number, number] | null;
  frequencyUnit?: string[] | null;
  globalActivationDate?: number[] | null;
  globalActivationDateRange?: readonly [number, number] | null;
  globalDeactivationDate?: number[] | null;
  globalDeactivationDateRange?: readonly [number, number] | null;
  isDeferrable?: boolean | null;
  maxApplicableCents?: number[] | null;
  maxApplicableCentsRange?: readonly [number, number] | null;
  minApplicableCents?: number[] | null;
  minApplicableCentsRange?: readonly [number, number] | null;
  name?: string[] | null;
  roundingMethod?: string[] | null;
  disabled?: boolean | null;
}
