// This file is auto-generated by @hey-api/openapi-ts

export const AddUserToOrganizationSchemaSchema = {
  properties: {
    organizationId: {
      type: 'string',
      format: 'uuid4',
      title: 'Organizationid',
    },
    userId: {
      type: 'string',
      format: 'uuid4',
      title: 'Userid',
    },
    groups: {
      anyOf: [
        {
          items: {
            type: 'string',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Groups',
      default: [],
    },
    firstName: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Firstname',
    },
    lastName: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Lastname',
    },
    email: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Email',
    },
    phoneNumber: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Phonenumber',
    },
  },
  type: 'object',
  required: ['organizationId', 'userId'],
  title: 'AddUserToOrganizationSchema',
  description: 'Fields required to add a user to an organization',
} as const;

export const AddressBaseSchemaSchema = {
  properties: {
    organizationId: {
      type: 'string',
      format: 'uuid4',
      title: 'Organizationid',
    },
    entityId: {
      type: 'string',
      format: 'uuid4',
      title: 'Entityid',
    },
    entityType: {
      $ref: '#/components/schemas/EntityTypes',
    },
    street: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Street',
    },
    city: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'City',
    },
    state: {
      type: 'string',
      title: 'State',
    },
    country: {
      type: 'string',
      title: 'Country',
    },
    zipCode: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Zipcode',
    },
    extra: {
      type: 'string',
      title: 'Extra',
    },
  },
  type: 'object',
  required: [
    'organizationId',
    'entityId',
    'entityType',
    'state',
    'country',
    'extra',
  ],
  title: 'AddressBaseSchema',
  description: 'Base schema for addresses',
} as const;

export const ApiKeyIdOnlySchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
    name: {
      type: 'string',
      title: 'Name',
    },
    createdAt: {
      type: 'integer',
      title: 'Createdat',
    },
  },
  type: 'object',
  required: ['id', 'name', 'createdAt'],
  title: 'ApiKeyIdOnlySchema',
  description: 'API key id only schema',
} as const;

export const ApiKeySchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
    name: {
      type: 'string',
      title: 'Name',
    },
    createdAt: {
      type: 'integer',
      title: 'Createdat',
    },
    apiKey: {
      type: 'string',
      title: 'Apikey',
    },
  },
  type: 'object',
  required: ['id', 'name', 'createdAt', 'apiKey'],
  title: 'ApiKeySchema',
  description: 'API key schema',
} as const;

export const AuthTokenTypesSchema = {
  type: 'string',
  enum: ['AUTH_CODE', 'MAGIC_LINK', 'COMBINED', 'SHARE_LINK'],
  title: 'AuthTokenTypes',
  description: 'Authentication token types',
} as const;

export const BasicGroupInformationSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
    name: {
      type: 'string',
      title: 'Name',
    },
    system: {
      type: 'boolean',
      title: 'System',
    },
    workgroup: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Workgroup',
      default: false,
    },
  },
  type: 'object',
  required: ['id', 'name', 'system'],
  title: 'BasicGroupInformationSchema',
  description: 'Schema used to return information on groups along with users',
} as const;

export const BasicUserProfileSchema = {
  properties: {
    email: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Email',
    },
    phoneNumber: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Phonenumber',
    },
    lastActive: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Lastactive',
      default: 0,
    },
    disabled: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Disabled',
      default: false,
    },
    firstName: {
      type: 'string',
      title: 'Firstname',
    },
    lastName: {
      type: 'string',
      title: 'Lastname',
    },
    avatarUri: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Avataruri',
    },
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
  },
  type: 'object',
  required: ['firstName', 'lastName', 'id'],
  title: 'BasicUserProfile',
  description:
    'Response for a simple user query, for display, used with digest',
} as const;

export const BusinessBaseSchemaSchema = {
  properties: {
    organizationId: {
      anyOf: [
        {
          type: 'string',
          format: 'uuid4',
        },
        {
          type: 'null',
        },
      ],
      title: 'Organizationid',
    },
    primaryContactId: {
      anyOf: [
        {
          type: 'string',
          format: 'uuid4',
        },
        {
          type: 'null',
        },
      ],
      title: 'Primarycontactid',
    },
    primaryAddressId: {
      anyOf: [
        {
          type: 'string',
          format: 'uuid4',
        },
        {
          type: 'null',
        },
      ],
      title: 'Primaryaddressid',
    },
    name: {
      type: 'string',
      title: 'Name',
    },
    email: {
      type: 'string',
      title: 'Email',
    },
    businessType: {
      $ref: '#/components/schemas/BusinessTypes',
    },
    uniqueBusinessIdentifier: {
      type: 'string',
      title: 'UniqueBusinessIdentifier',
    },
    users: {
      anyOf: [
        {
          items: {
            $ref: '#/components/schemas/SafeUserCreate',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Users',
    },
  },
  type: 'object',
  required: ['name', 'email', 'businessType'],
  title: 'BusinessBaseSchema',
  description: 'Base request schema for the business requests',
} as const;

export const BusinessCreatedSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
    users: {
      anyOf: [
        {
          items: {
            $ref: '#/components/schemas/BasicUserProfile',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Users',
    },
  },
  type: 'object',
  required: ['id'],
  title: 'BusinessCreatedSchema',
  description: 'Id returned when a business is successfully created',
} as const;

export const BusinessQueryResultSchemaSchema = {
  properties: {
    items: {
      items: {
        $ref: '#/components/schemas/ExistingBusinessSchema-Output',
      },
      type: 'array',
      title: 'Items',
    },
    totalCount: {
      type: 'integer',
      title: 'Totalcount',
    },
  },
  type: 'object',
  required: ['items', 'totalCount'],
  title: 'BusinessQueryResultSchema',
  description: 'Response for a user query, including the count',
} as const;

export const BusinessTypesSchema = {
  type: 'string',
  enum: ['CORPORATION', 'LLC', 'LLP', 'GP', 'LP', 'TRUST'],
  title: 'BusinessTypes',
  description: 'Types of users',
} as const;

export const CreateApiKeySchemaSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
  },
  type: 'object',
  required: ['name'],
  title: 'CreateApiKeySchema',
  description: 'Create api key schema',
} as const;

export const CreateBusinessBatchArgsSchema = {
  properties: {
    businesses: {
      items: {
        $ref: '#/components/schemas/BusinessBaseSchema',
      },
      type: 'array',
      title: 'Businesses',
      default: [],
    },
    organizationId: {
      type: 'string',
      format: 'uuid4',
      title: 'Organizationid',
    },
  },
  type: 'object',
  required: ['organizationId'],
  title: 'CreateBusinessBatchArgs',
  description: 'Input for creating a batch of businesses',
} as const;

export const CreateOrganizationSchemaSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    dnsPrefix: {
      type: 'string',
      title: 'Dnsprefix',
    },
    logoUri: {
      type: 'string',
      title: 'Logouri',
    },
    logoUriSmall: {
      type: 'string',
      title: 'Logourismall',
    },
    colors: {
      title: 'Colors',
    },
    syncEnabled: {
      type: 'boolean',
      title: 'Syncenabled',
      default: false,
    },
    syncKeySecretName: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Synckeysecretname',
    },
    syncOutboundQueueName: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Syncoutboundqueuename',
    },
    backofficeJwtTtlMinutes: {
      type: 'integer',
      title: 'Backofficejwtttlminutes',
    },
    clientAppsJwtTtlMinutes: {
      type: 'integer',
      title: 'Clientappsjwtttlminutes',
    },
    databaseName: {
      type: 'string',
      title: 'Databasename',
    },
    documentBucket: {
      type: 'string',
      title: 'Documentbucket',
    },
    cacheEncryptionKey: {
      type: 'string',
      title: 'Cacheencryptionkey',
    },
    root: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Root',
    },
  },
  type: 'object',
  required: [
    'name',
    'dnsPrefix',
    'logoUri',
    'logoUriSmall',
    'colors',
    'backofficeJwtTtlMinutes',
    'clientAppsJwtTtlMinutes',
    'databaseName',
    'documentBucket',
    'cacheEncryptionKey',
  ],
  title: 'CreateOrganizationSchema',
  description: 'Schema for when creating an organization',
} as const;

export const CreateShareLinkBatchSchema = {
  properties: {
    shareLinks: {
      items: {
        $ref: '#/components/schemas/CreateShareLinkSchema',
      },
      type: 'array',
      title: 'Sharelinks',
    },
  },
  type: 'object',
  required: ['shareLinks'],
  title: 'CreateShareLinkBatch',
  description: 'Schema for creating multiple share links at the same time',
} as const;

export const CreateShareLinkSchemaSchema = {
  properties: {
    organizationUserId: {
      type: 'string',
      format: 'uuid4',
      title: 'Organizationuserid',
    },
    redirectPath: {
      type: 'string',
      title: 'Redirectpath',
    },
    externalId: {
      type: 'string',
      format: 'uuid4',
      title: 'Externalid',
    },
    senderName: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Sendername',
    },
    requestName: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Requestname',
    },
    subjectOverride: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Subjectoverride',
    },
    messageOverride: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Messageoverride',
    },
    tasksOverride: {
      anyOf: [
        {
          items: {
            $ref: '#/components/schemas/TaskOverride',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Tasksoverride',
    },
  },
  type: 'object',
  required: ['organizationUserId', 'redirectPath', 'externalId'],
  title: 'CreateShareLinkSchema',
  description: 'Schema for initiating a token based auth',
} as const;

export const CreateTokenAuthSchemaSchema = {
  properties: {
    organizationUserId: {
      anyOf: [
        {
          type: 'string',
          format: 'uuid4',
        },
        {
          type: 'null',
        },
      ],
      title: 'Organizationuserid',
    },
    recipient: {
      type: 'string',
      title: 'Recipient',
    },
    organizationKey: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Organizationkey',
    },
    tokenType: {
      $ref: '#/components/schemas/AuthTokenTypes',
    },
  },
  type: 'object',
  required: ['recipient', 'tokenType'],
  title: 'CreateTokenAuthSchema',
  description: 'Schema for initiating a token based auth',
} as const;

export const CreateUserBatchArgsSchema = {
  properties: {
    users: {
      items: {
        $ref: '#/components/schemas/SafeUserCreate',
      },
      type: 'array',
      title: 'Users',
      default: [],
    },
    organizationId: {
      type: 'string',
      format: 'uuid4',
      title: 'Organizationid',
    },
  },
  type: 'object',
  required: ['organizationId'],
  title: 'CreateUserBatchArgs',
  description: 'Input for creating a batch of users',
} as const;

export const CreatedAddressSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
  },
  type: 'object',
  required: ['id'],
  title: 'CreatedAddressSchema',
  description: 'Created address schema',
} as const;

export const EntityTypesSchema = {
  type: 'string',
  enum: ['INDIVIDUAL', 'BUSINESS'],
  title: 'EntityTypes',
  description: 'Type of entity for the address',
} as const;

export const ExistingAddressSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
    organizationId: {
      type: 'string',
      format: 'uuid4',
      title: 'Organizationid',
    },
    entityId: {
      type: 'string',
      format: 'uuid4',
      title: 'Entityid',
    },
    entityType: {
      $ref: '#/components/schemas/EntityTypes',
    },
    street: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Street',
    },
    city: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'City',
    },
    state: {
      type: 'string',
      title: 'State',
    },
    country: {
      type: 'string',
      title: 'Country',
    },
    zipCode: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Zipcode',
    },
    extra: {
      type: 'string',
      title: 'Extra',
    },
  },
  type: 'object',
  required: [
    'id',
    'organizationId',
    'entityId',
    'entityType',
    'state',
    'country',
    'extra',
  ],
  title: 'ExistingAddressSchema',
  description: 'Existing address schema',
} as const;

export const ExistingBusinessSchema_InputSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
    organizationId: {
      type: 'string',
      format: 'uuid4',
      title: 'Organizationid',
    },
    primaryContactId: {
      anyOf: [
        {
          type: 'string',
          format: 'uuid4',
        },
        {
          type: 'null',
        },
      ],
      title: 'Primarycontactid',
    },
    primaryAddressId: {
      anyOf: [
        {
          type: 'string',
          format: 'uuid4',
        },
        {
          type: 'null',
        },
      ],
      title: 'Primaryaddressid',
    },
    name: {
      type: 'string',
      title: 'Name',
    },
    email: {
      type: 'string',
      title: 'Email',
    },
    businessType: {
      $ref: '#/components/schemas/BusinessTypes',
    },
    uniqueBusinessIdentifier: {
      type: 'string',
      title: 'UniqueBusinessIdentifier',
    },
    addresses: {
      anyOf: [
        {
          items: {
            $ref: '#/components/schemas/ExistingAddressSchema',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Addresses',
      default: [],
    },
    users: {
      anyOf: [
        {
          items: {
            $ref: '#/components/schemas/BasicUserProfile',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Users',
      default: [],
    },
  },
  type: 'object',
  required: ['id', 'organizationId', 'name', 'email', 'businessType'],
  title: 'ExistingBusinessSchema',
  description: 'Existing business schema',
} as const;

export const ExistingBusinessSchema_OutputSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
    organizationId: {
      type: 'string',
      format: 'uuid4',
      title: 'Organizationid',
    },
    primaryContactId: {
      anyOf: [
        {
          type: 'string',
          format: 'uuid4',
        },
        {
          type: 'null',
        },
      ],
      title: 'Primarycontactid',
    },
    primaryAddressId: {
      anyOf: [
        {
          type: 'string',
          format: 'uuid4',
        },
        {
          type: 'null',
        },
      ],
      title: 'Primaryaddressid',
    },
    name: {
      type: 'string',
      title: 'Name',
    },
    email: {
      type: 'string',
      title: 'Email',
    },
    businessType: {
      $ref: '#/components/schemas/BusinessTypes',
    },
    uniqueBusinessIdentifier: {
      type: 'string',
      title: 'uniqueBusinessIdentifier',
    },
    addresses: {
      anyOf: [
        {
          items: {
            $ref: '#/components/schemas/ExistingAddressSchema',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Addresses',
      default: [],
    },
    users: {
      anyOf: [
        {
          items: {
            $ref: '#/components/schemas/BasicUserProfile',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Users',
      default: [],
    },
  },
  type: 'object',
  required: ['id', 'organizationId', 'name', 'email', 'businessType'],
  title: 'ExistingBusinessSchema',
  description: 'Existing business schema',
} as const;

export const ExistingGroupSchemaSchema = {
  properties: {
    organizationId: {
      type: 'string',
      format: 'uuid4',
      title: 'Organizationid',
    },
    name: {
      type: 'string',
      title: 'Name',
    },
    email: {
      anyOf: [
        {
          type: 'string',
          format: 'email',
        },
        {
          type: 'null',
        },
      ],
      title: 'Email',
    },
    permissions: {
      title: 'Permissions',
    },
    system: {
      type: 'boolean',
      title: 'System',
    },
    workgroup: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Workgroup',
      default: false,
    },
    createdAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Createdat',
    },
    updatedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Updatedat',
    },
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
  },
  type: 'object',
  required: ['organizationId', 'name', 'permissions', 'system', 'id'],
  title: 'ExistingGroupSchema',
  description: 'Existing group schema',
} as const;

export const ExistingOrganizationFullConfigurationSchemaSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    dnsPrefix: {
      type: 'string',
      title: 'Dnsprefix',
    },
    logoUri: {
      type: 'string',
      title: 'Logouri',
    },
    logoUriSmall: {
      type: 'string',
      title: 'Logourismall',
    },
    colors: {
      title: 'Colors',
    },
    syncEnabled: {
      type: 'boolean',
      title: 'Syncenabled',
      default: false,
    },
    syncKeySecretName: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Synckeysecretname',
    },
    syncOutboundQueueName: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Syncoutboundqueuename',
    },
    backofficeJwtTtlMinutes: {
      type: 'integer',
      title: 'Backofficejwtttlminutes',
    },
    clientAppsJwtTtlMinutes: {
      type: 'integer',
      title: 'Clientappsjwtttlminutes',
    },
    databaseName: {
      type: 'string',
      title: 'Databasename',
    },
    documentBucket: {
      type: 'string',
      title: 'Documentbucket',
    },
    cacheEncryptionKey: {
      type: 'string',
      title: 'Cacheencryptionkey',
    },
    root: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Root',
    },
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
    groups: {
      anyOf: [
        {
          items: {
            $ref: '#/components/schemas/ExistingGroupSchema',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Groups',
      default: [],
    },
  },
  type: 'object',
  required: [
    'name',
    'dnsPrefix',
    'logoUri',
    'logoUriSmall',
    'colors',
    'backofficeJwtTtlMinutes',
    'clientAppsJwtTtlMinutes',
    'databaseName',
    'documentBucket',
    'cacheEncryptionKey',
    'id',
  ],
  title: 'ExistingOrganizationFullConfigurationSchema',
  description: 'Full configuration, for use by the service',
} as const;

export const ExistingOrganizationSchemaSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    dnsPrefix: {
      type: 'string',
      title: 'Dnsprefix',
    },
    logoUri: {
      type: 'string',
      title: 'Logouri',
    },
    logoUriSmall: {
      type: 'string',
      title: 'Logourismall',
    },
    colors: {
      title: 'Colors',
    },
    syncEnabled: {
      type: 'boolean',
      title: 'Syncenabled',
      default: false,
    },
    syncKeySecretName: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Synckeysecretname',
    },
    syncOutboundQueueName: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Syncoutboundqueuename',
    },
    backofficeJwtTtlMinutes: {
      type: 'integer',
      title: 'Backofficejwtttlminutes',
    },
    clientAppsJwtTtlMinutes: {
      type: 'integer',
      title: 'Clientappsjwtttlminutes',
    },
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
  },
  type: 'object',
  required: [
    'name',
    'dnsPrefix',
    'logoUri',
    'logoUriSmall',
    'colors',
    'backofficeJwtTtlMinutes',
    'clientAppsJwtTtlMinutes',
    'id',
  ],
  title: 'ExistingOrganizationSchema',
  description: 'Existing organization schema',
} as const;

export const FeatureFlagCacheActionSchemaSchema = {
  properties: {
    action: {
      $ref: '#/components/schemas/FeatureFlagCacheActions',
    },
  },
  type: 'object',
  required: ['action'],
  title: 'FeatureFlagCacheActionSchema',
  description: 'Schema used to send an action to the cache',
} as const;

export const FeatureFlagCacheActionsSchema = {
  type: 'string',
  enum: ['INVALIDATE', 'REFRESH'],
  title: 'FeatureFlagCacheActions',
  description: 'Actions that can be posted on the cache',
} as const;

export const FeatureFlagSchemaSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    activated: {
      type: 'boolean',
      title: 'Activated',
    },
  },
  type: 'object',
  required: ['name', 'activated'],
  title: 'FeatureFlagSchema',
  description: 'Base request schema for the a feature flag',
} as const;

export const GroupBaseSchemaSchema = {
  properties: {
    organizationId: {
      type: 'string',
      format: 'uuid4',
      title: 'Organizationid',
    },
    name: {
      type: 'string',
      title: 'Name',
    },
    email: {
      anyOf: [
        {
          type: 'string',
          format: 'email',
        },
        {
          type: 'null',
        },
      ],
      title: 'Email',
    },
    permissions: {
      title: 'Permissions',
    },
    system: {
      type: 'boolean',
      title: 'System',
    },
    workgroup: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Workgroup',
      default: false,
    },
    createdAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Createdat',
    },
    updatedAt: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Updatedat',
    },
  },
  type: 'object',
  required: ['organizationId', 'name', 'permissions', 'system'],
  title: 'GroupBaseSchema',
  description: 'Base request schema for the groups requests',
} as const;

export const GroupCreatedSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
  },
  type: 'object',
  required: ['id'],
  title: 'GroupCreatedSchema',
  description: 'Id returned when a user is successfully created',
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: '#/components/schemas/ValidationError',
      },
      type: 'array',
      title: 'Detail',
    },
  },
  type: 'object',
  title: 'HTTPValidationError',
} as const;

export const LoginWithApiKeySchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
    apiKey: {
      type: 'string',
      title: 'Apikey',
    },
  },
  type: 'object',
  required: ['id', 'apiKey'],
  title: 'LoginWithApiKeySchema',
  description: 'Login with API key schema',
} as const;

export const NotificationTypesSchema = {
  type: 'string',
  enum: ['EMAIL', 'SMS', 'IN_APP', 'PUSH'],
  title: 'NotificationTypes',
  description: 'Types of notification',
} as const;

export const OrganizationCreatedSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
  },
  type: 'object',
  required: ['id'],
  title: 'OrganizationCreatedSchema',
  description: 'Id of the created organization',
} as const;

export const OrganizationUIConfigurationSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    dnsPrefix: {
      type: 'string',
      title: 'Dnsprefix',
    },
    logoUri: {
      type: 'string',
      title: 'Logouri',
    },
    logoUriSmall: {
      type: 'string',
      title: 'Logourismall',
    },
    colors: {
      title: 'Colors',
    },
  },
  type: 'object',
  required: ['name', 'dnsPrefix', 'logoUri', 'logoUriSmall', 'colors'],
  title: 'OrganizationUIConfiguration',
  description: 'UI Configuration returned with a tenant.',
} as const;

export const OrganizationUserSchemaSchema = {
  properties: {
    email: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Email',
    },
    phoneNumber: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Phonenumber',
    },
    lastActive: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Lastactive',
      default: 0,
    },
    disabled: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Disabled',
      default: false,
    },
    firstName: {
      type: 'string',
      title: 'Firstname',
    },
    lastName: {
      type: 'string',
      title: 'Lastname',
    },
    avatarUri: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Avataruri',
    },
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
    groups: {
      anyOf: [
        {
          items: {
            type: 'string',
            format: 'uuid4',
          },
          type: 'array',
        },
        {
          items: {
            $ref: '#/components/schemas/BasicGroupInformationSchema',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Groups',
      default: [],
    },
  },
  type: 'object',
  required: ['firstName', 'lastName', 'id'],
  title: 'OrganizationUserSchema',
  description: 'Response for when an organization user is returned',
} as const;

export const SafeUserCreateSchema = {
  properties: {
    email: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Email',
    },
    phoneNumber: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Phonenumber',
    },
    lastActive: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Lastactive',
      default: 0,
    },
    disabled: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Disabled',
      default: false,
    },
    firstName: {
      type: 'string',
      title: 'Firstname',
    },
    lastName: {
      type: 'string',
      title: 'Lastname',
    },
    avatarUri: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Avataruri',
    },
    groups: {
      anyOf: [
        {
          items: {
            type: 'string',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Groups',
      default: [],
    },
  },
  type: 'object',
  required: ['firstName', 'lastName'],
  title: 'SafeUserCreate',
  description: 'Request schema for the safe user create',
} as const;

export const ShareLinkBaseSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
    organizationUserId: {
      type: 'string',
      format: 'uuid4',
      title: 'Organizationuserid',
    },
    recipient: {
      type: 'string',
      title: 'Recipient',
    },
    recipientType: {
      $ref: '#/components/schemas/NotificationTypes',
    },
    expiresAt: {
      type: 'integer',
      title: 'Expiresat',
    },
    redirectPath: {
      type: 'string',
      title: 'Redirectpath',
    },
    externalId: {
      type: 'string',
      format: 'uuid4',
      title: 'Externalid',
    },
  },
  type: 'object',
  required: [
    'id',
    'organizationUserId',
    'recipient',
    'recipientType',
    'expiresAt',
    'redirectPath',
    'externalId',
  ],
  title: 'ShareLinkBaseSchema',
  description: 'Base share link model',
} as const;

export const TaskOverrideSchema = {
  properties: {
    taskType: {
      type: 'string',
      title: 'Tasktype',
    },
    taskName: {
      type: 'string',
      title: 'Taskname',
    },
    taskPath: {
      type: 'string',
      title: 'Taskpath',
    },
  },
  type: 'object',
  required: ['taskType', 'taskName', 'taskPath'],
  title: 'TaskOverride',
  description: 'Schema for task override',
} as const;

export const UpdateOrganizationUserSchemaSchema = {
  properties: {
    userId: {
      type: 'string',
      format: 'uuid4',
      title: 'Userid',
    },
    firstName: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Firstname',
    },
    lastName: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Lastname',
    },
    email: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Email',
    },
    phoneNumber: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Phonenumber',
    },
  },
  type: 'object',
  required: ['userId'],
  title: 'UpdateOrganizationUserSchema',
  description: 'Fields required to update an organization user',
} as const;

export const UpdateShareLinkSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
    disabled: {
      type: 'boolean',
      title: 'Disabled',
    },
    disabledDate: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Disableddate',
    },
    disabledReason: {
      type: 'string',
      title: 'Disabledreason',
    },
  },
  type: 'object',
  required: ['id', 'disabled', 'disabledReason'],
  title: 'UpdateShareLinkSchema',
  description:
    'Schema to update a shared link, need to be careful when changing this',
} as const;

export const UserAddedToOrganizationSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
  },
  type: 'object',
  required: ['id'],
  title: 'UserAddedToOrganizationSchema',
  description:
    'Id returned when a user is successfully added to an organization',
} as const;

export const UserCreateSchema = {
  properties: {
    email: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Email',
    },
    phoneNumber: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Phonenumber',
    },
    lastActive: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Lastactive',
      default: 0,
    },
    disabled: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Disabled',
      default: false,
    },
    firstName: {
      type: 'string',
      title: 'Firstname',
    },
    lastName: {
      type: 'string',
      title: 'Lastname',
    },
    avatarUri: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Avataruri',
    },
  },
  type: 'object',
  required: ['firstName', 'lastName'],
  title: 'UserCreate',
  description: 'Request schema to be used for creating a new user',
} as const;

export const UserCreatedSchemaSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
  },
  type: 'object',
  required: ['id'],
  title: 'UserCreatedSchema',
  description: 'Response mapping for the user created request',
} as const;

export const UserProfileSchema = {
  properties: {
    email: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Email',
    },
    phoneNumber: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Phonenumber',
    },
    lastActive: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Lastactive',
      default: 0,
    },
    disabled: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Disabled',
      default: false,
    },
    firstName: {
      type: 'string',
      title: 'Firstname',
    },
    lastName: {
      type: 'string',
      title: 'Lastname',
    },
    avatarUri: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Avataruri',
    },
    id: {
      type: 'string',
      format: 'uuid4',
      title: 'Id',
    },
    activeOrganization: {
      anyOf: [
        {
          type: 'string',
          format: 'uuid4',
        },
        {
          type: 'null',
        },
      ],
      title: 'Activeorganization',
    },
    activeOrganizationUserId: {
      anyOf: [
        {
          type: 'string',
          format: 'uuid4',
        },
        {
          type: 'null',
        },
      ],
      title: 'Activeorganizationuserid',
    },
    digest: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Digest',
    },
  },
  type: 'object',
  required: ['firstName', 'lastName', 'id'],
  title: 'UserProfile',
  description: 'Response mapping for the user profile and user data',
} as const;

export const UserQueryResultSchemaSchema = {
  properties: {
    items: {
      items: {
        $ref: '#/components/schemas/OrganizationUserSchema',
      },
      type: 'array',
      title: 'Items',
    },
    totalCount: {
      type: 'integer',
      title: 'Totalcount',
    },
  },
  type: 'object',
  required: ['items', 'totalCount'],
  title: 'UserQueryResultSchema',
  description: 'Response for a user query, including the count',
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: 'string',
          },
          {
            type: 'integer',
          },
        ],
      },
      type: 'array',
      title: 'Location',
    },
    msg: {
      type: 'string',
      title: 'Message',
    },
    type: {
      type: 'string',
      title: 'Error Type',
    },
  },
  type: 'object',
  required: ['loc', 'msg', 'type'],
  title: 'ValidationError',
} as const;
