// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type Options,
} from '@hey-api/client-fetch';
import type {
  ReadUsersUsersGetData,
  CreateUserUsersPostData,
  CreateUserUsersPostError,
  CreateUserUsersPostResponse,
  ReadUserMeUsersMeGetData,
  ReadUserMeUsersMeGetResponse,
  ReadUserUsersUsernameGetData,
  RefreshTokenTokenRefreshGetData,
  LoginViaTokenLoginTokenPostData,
  LoginViaTokenLoginTokenPostError,
  LoginViaGoogleLoginGoogleGetData,
  LoginViaGoogleLoginGoogleGetError,
  AuthViaGoogleAuthGoogleGetData,
  LoginViaMicrosoftLoginMicrosoftGetData,
  LoginViaMicrosoftLoginMicrosoftGetError,
  AuthViaMicrosoftAuthMicrosoftGetData,
  AuthViaMagicLinkAuthLinkGetData,
  AuthViaMagicLinkAuthLinkGetError,
  LoginViaApiKeyLoginApiKeyPostData,
  LoginViaApiKeyLoginApiKeyPostError,
  AuthViaAuthCodeAuthCodeGetData,
  LogoutLogoutGetData,
  GetAllOrganizationsOrganizationsGetData,
  GetAllOrganizationsOrganizationsGetResponse,
  CreateOrganizationOrganizationsPostData,
  CreateOrganizationOrganizationsPostError,
  CreateOrganizationOrganizationsPostResponse,
  DeleteOrganizationOrganizationsOrganizationIdDeleteData,
  DeleteOrganizationOrganizationsOrganizationIdDeleteError,
  GetOrganizationOrganizationsOrganizationIdGetData,
  GetOrganizationOrganizationsOrganizationIdGetError,
  GetOrganizationOrganizationsOrganizationIdGetResponse,
  UpdateOrganizationOrganizationsOrganizationIdPutData,
  UpdateOrganizationOrganizationsOrganizationIdPutError,
  GetAllOrganizationUsersOrganizationsOrganizationIdUsersGetData,
  GetAllOrganizationUsersOrganizationsOrganizationIdUsersGetError,
  GetAllOrganizationUsersOrganizationsOrganizationIdUsersGetResponse,
  AddUserToOrganizationOrganizationsOrganizationIdUsersPostData,
  AddUserToOrganizationOrganizationsOrganizationIdUsersPostError,
  AddUserToOrganizationOrganizationsOrganizationIdUsersPostResponse,
  CreateUsersBatchOrganizationsOrganizationIdUsersBatchPostData,
  CreateUsersBatchOrganizationsOrganizationIdUsersBatchPostError,
  CreateUsersBatchOrganizationsOrganizationIdUsersBatchPostResponse,
  SafeAddUserToOrganizationOrganizationsOrganizationIdUsersSafePostData,
  SafeAddUserToOrganizationOrganizationsOrganizationIdUsersSafePostError,
  SafeAddUserToOrganizationOrganizationsOrganizationIdUsersSafePostResponse,
  GetUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdGetData,
  GetUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdGetError,
  GetUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdGetResponse,
  PatchUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdPatchData,
  PatchUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdPatchError,
  RemoveUserFromOrganizationOrganizationsOrganizationIdUsersUserIdDeleteData,
  RemoveUserFromOrganizationOrganizationsOrganizationIdUsersUserIdDeleteError,
  GetAddressesForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesGetData,
  GetAddressesForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesGetError,
  GetAddressesForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesGetResponse,
  CreateAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesPostData,
  CreateAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesPostError,
  CreateAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesPostResponse,
  DeleteAddressFromUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesAddressIdDeleteData,
  DeleteAddressFromUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesAddressIdDeleteError,
  UpdateAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesAddressIdPutData,
  UpdateAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesAddressIdPutError,
  GetUiConfigurationOrganizationsExternalUiConfigurationGetData,
  GetUiConfigurationOrganizationsExternalUiConfigurationGetResponse,
  ReadOrganizationConfigurationOrganizationsOrganizationKeyConfigurationGetData,
  ReadOrganizationConfigurationOrganizationsOrganizationKeyConfigurationGetError,
  ReadOrganizationConfigurationOrganizationsOrganizationKeyConfigurationGetResponse,
  GetGroupsForOrganizationOrganizationsOrganizationIdGroupsGetData,
  GetGroupsForOrganizationOrganizationsOrganizationIdGroupsGetError,
  GetGroupsForOrganizationOrganizationsOrganizationIdGroupsGetResponse,
  CreateGroupOrganizationsOrganizationIdGroupsPostData,
  CreateGroupOrganizationsOrganizationIdGroupsPostError,
  CreateGroupOrganizationsOrganizationIdGroupsPostResponse,
  DeleteGroupOrganizationsOrganizationIdGroupsGroupIdDeleteData,
  DeleteGroupOrganizationsOrganizationIdGroupsGroupIdDeleteError,
  GetGroupOrganizationsOrganizationIdGroupsGroupIdGetData,
  GetGroupOrganizationsOrganizationIdGroupsGroupIdGetError,
  GetGroupOrganizationsOrganizationIdGroupsGroupIdGetResponse,
  UpdateGroupOrganizationsOrganizationIdGroupsGroupIdPutData,
  UpdateGroupOrganizationsOrganizationIdGroupsGroupIdPutError,
  RemoveUserFromGroupOrganizationsOrganizationIdGroupsGroupIdUsersOrganizationUserIdDeleteData,
  RemoveUserFromGroupOrganizationsOrganizationIdGroupsGroupIdUsersOrganizationUserIdDeleteError,
  AddUserToGroupOrganizationsOrganizationIdGroupsGroupIdUsersOrganizationUserIdPostData,
  AddUserToGroupOrganizationsOrganizationIdGroupsGroupIdUsersOrganizationUserIdPostError,
  GetGlobalFeatureFlagsFeaturesGetData,
  GetGlobalFeatureFlagsFeaturesGetResponse,
  SetGlobalFeatureFlagsFeaturesPutData,
  SetGlobalFeatureFlagsFeaturesPutError,
  GetOrganizationFeatureFlagsFeaturesOrganizationsOrganizationIdGetData,
  GetOrganizationFeatureFlagsFeaturesOrganizationsOrganizationIdGetResponse,
  SetOrganizationFeatureFlagsFeaturesOrganizationsOrganizationIdPutData,
  SetOrganizationFeatureFlagsFeaturesOrganizationsOrganizationIdPutError,
  CacheActionFeaturesCachePostData,
  CacheActionFeaturesCachePostError,
  GetShareLinksByUserShareUsersOrganizationUserIdGetData,
  GetShareLinksByUserShareUsersOrganizationUserIdGetError,
  GetShareLinksByUserShareUsersOrganizationUserIdGetResponse,
  GetShareLinksByExternalIdShareResourcesExternalIdGetData,
  GetShareLinksByExternalIdShareResourcesExternalIdGetError,
  GetShareLinksByExternalIdShareResourcesExternalIdGetResponse,
  CreateShareLinkBatchShareBatchPostData,
  CreateShareLinkBatchShareBatchPostError,
  CreateShareLinkSharePostData,
  CreateShareLinkSharePostError,
  DeleteShareLinkShareShareLinkIdDeleteData,
  DeleteShareLinkShareShareLinkIdDeleteError,
  UpdateShareLinkShareShareLinkIdPutData,
  UpdateShareLinkShareShareLinkIdPutError,
  DeleteAllApiKeysApiKeysDeleteData,
  GetApiKeysApiKeysGetData,
  GetApiKeysApiKeysGetResponse,
  CreateApiKeyApiKeysPostData,
  CreateApiKeyApiKeysPostError,
  CreateApiKeyApiKeysPostResponse,
  DeleteApiKeyApiKeysApiKeyIdDeleteData,
  DeleteApiKeyApiKeysApiKeyIdDeleteError,
  GetBusinessesForUserOrganizationsOrganizationIdBusinessesUsersOrganizationUserIdGetData,
  GetBusinessesForUserOrganizationsOrganizationIdBusinessesUsersOrganizationUserIdGetError,
  GetBusinessesForUserOrganizationsOrganizationIdBusinessesUsersOrganizationUserIdGetResponse,
  GetBusinessesForOrganizationOrganizationsOrganizationIdBusinessesGetData,
  GetBusinessesForOrganizationOrganizationsOrganizationIdBusinessesGetError,
  GetBusinessesForOrganizationOrganizationsOrganizationIdBusinessesGetResponse,
  CreateBusinessOrganizationsOrganizationIdBusinessesPostData,
  CreateBusinessOrganizationsOrganizationIdBusinessesPostError,
  CreateBusinessOrganizationsOrganizationIdBusinessesPostResponse,
  DeleteBusinessOrganizationsOrganizationIdBusinessesBusinessIdDeleteData,
  DeleteBusinessOrganizationsOrganizationIdBusinessesBusinessIdDeleteError,
  GetBusinessOrganizationsOrganizationIdBusinessesBusinessIdGetData,
  GetBusinessOrganizationsOrganizationIdBusinessesBusinessIdGetError,
  GetBusinessOrganizationsOrganizationIdBusinessesBusinessIdGetResponse,
  UpdateBusinessOrganizationsOrganizationIdBusinessesBusinessIdPutData,
  UpdateBusinessOrganizationsOrganizationIdBusinessesBusinessIdPutError,
  CreateBusinessBatchOrganizationsOrganizationIdBusinessesBatchPostData,
  CreateBusinessBatchOrganizationsOrganizationIdBusinessesBatchPostError,
  CreateBusinessBatchOrganizationsOrganizationIdBusinessesBatchPostResponse,
  GetBusinessUsersOrganizationsOrganizationIdBusinessesBusinessIdUsersGetData,
  GetBusinessUsersOrganizationsOrganizationIdBusinessesBusinessIdUsersGetError,
  GetBusinessUsersOrganizationsOrganizationIdBusinessesBusinessIdUsersGetResponse,
  RemoveUserFromBusinessOrganizationsOrganizationIdBusinessesBusinessIdUsersOrganizationUserIdDeleteData,
  RemoveUserFromBusinessOrganizationsOrganizationIdBusinessesBusinessIdUsersOrganizationUserIdDeleteError,
  AddUserToBusinessOrganizationsOrganizationIdBusinessesBusinessIdUsersOrganizationUserIdPostData,
  AddUserToBusinessOrganizationsOrganizationIdBusinessesBusinessIdUsersOrganizationUserIdPostError,
  GetAddressesForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesGetData,
  GetAddressesForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesGetError,
  GetAddressesForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesGetResponse,
  CreateAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesPostData,
  CreateAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesPostError,
  CreateAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesPostResponse,
  DeleteAddressFromBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesAddressIdDeleteData,
  DeleteAddressFromBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesAddressIdDeleteError,
  UpdateAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesAddressIdPutData,
  UpdateAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesAddressIdPutError,
  GetRootGetData,
  GetStatusCheckStatusGetData,
} from './types.gen';

export const client = createClient(createConfig());

/**
 * Read Users
 * TODO
 */
export const readUsersUsersGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReadUsersUsersGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/users/',
  });
};

/**
 * Create User
 * Creates a user
 */
export const createUserUsersPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateUserUsersPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    CreateUserUsersPostResponse,
    CreateUserUsersPostError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/users/',
  });
};

/**
 * Read User Me
 * Allows an authenticated user to get their own user profile for use in the application.
 */
export const readUserMeUsersMeGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReadUserMeUsersMeGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ReadUserMeUsersMeGetResponse,
    unknown,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/users/me',
  });
};

/**
 * Read User
 * TODO
 */
export const readUserUsersUsernameGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReadUserUsersUsernameGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/users/{username}',
  });
};

/**
 * Refresh Token
 * Refresh the token for the current user
 */
export const refreshTokenTokenRefreshGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<RefreshTokenTokenRefreshGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/token/refresh',
  });
};

/**
 * Login Via Token
 * Initiate a login with a token
 */
export const loginViaTokenLoginTokenPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<LoginViaTokenLoginTokenPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    unknown,
    LoginViaTokenLoginTokenPostError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    url: '/login/token',
  });
};

/**
 * Login Via Google
 * Initiate a login with the Google IDP
 */
export const loginViaGoogleLoginGoogleGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<LoginViaGoogleLoginGoogleGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    unknown,
    LoginViaGoogleLoginGoogleGetError,
    ThrowOnError
  >({
    ...options,
    url: '/login/google',
  });
};

/**
 * Auth Via Google
 * Process the result of the Google IDP and, if successful, issues a JWT
 */
export const authViaGoogleAuthGoogleGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AuthViaGoogleAuthGoogleGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
    ...options,
    url: '/auth/google',
  });
};

/**
 * Login Via Microsoft
 * Initiate a login with the Microsoft IDP
 */
export const loginViaMicrosoftLoginMicrosoftGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<LoginViaMicrosoftLoginMicrosoftGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    unknown,
    LoginViaMicrosoftLoginMicrosoftGetError,
    ThrowOnError
  >({
    ...options,
    url: '/login/microsoft',
  });
};

/**
 * Auth Via Microsoft
 * Process the result of the Microsoft IDP and, if successful, issues a JWT
 */
export const authViaMicrosoftAuthMicrosoftGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AuthViaMicrosoftAuthMicrosoftGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
    ...options,
    url: '/auth/microsoft',
  });
};

/**
 * Auth Via Magic Link
 * Completes authentication based on a magic link
 */
export const authViaMagicLinkAuthLinkGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AuthViaMagicLinkAuthLinkGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    unknown,
    AuthViaMagicLinkAuthLinkGetError,
    ThrowOnError
  >({
    ...options,
    url: '/auth/link',
  });
};

/**
 * Login Via Api Key
 * Initiate a login with an API key
 */
export const loginViaApiKeyLoginApiKeyPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<LoginViaApiKeyLoginApiKeyPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    unknown,
    LoginViaApiKeyLoginApiKeyPostError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    url: '/login/api-key',
  });
};

/**
 * Auth Via Auth Code
 * Completes authentication based on an auth code
 */
export const authViaAuthCodeAuthCodeGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AuthViaAuthCodeAuthCodeGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
    ...options,
    url: '/auth/code',
  });
};

/**
 * Logout
 * Process a logout request, which will invalidate the current JWT,"
 * and call the revoke endpoint in the IDP
 */
export const logoutLogoutGet = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutLogoutGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
    ...options,
    url: '/logout',
  });
};

/**
 * Get All Organizations
 * Returns the existing organizations
 */
export const getAllOrganizationsOrganizationsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetAllOrganizationsOrganizationsGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetAllOrganizationsOrganizationsGetResponse,
    unknown,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/organizations',
  });
};

/**
 * Create Organization
 * Creates a new organization using the provided schema
 */
export const createOrganizationOrganizationsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateOrganizationOrganizationsPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    CreateOrganizationOrganizationsPostResponse,
    CreateOrganizationOrganizationsPostError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/organizations',
  });
};

/**
 * Delete Organization
 * Delete an organization.
 */
export const deleteOrganizationOrganizationsOrganizationIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteOrganizationOrganizationsOrganizationIdDeleteData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).delete<
    unknown,
    DeleteOrganizationOrganizationsOrganizationIdDeleteError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/organizations/{organization_id}',
  });
};

/**
 * Get Organization
 * Get an existing organization.
 */
export const getOrganizationOrganizationsOrganizationIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetOrganizationOrganizationsOrganizationIdGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    GetOrganizationOrganizationsOrganizationIdGetResponse,
    GetOrganizationOrganizationsOrganizationIdGetError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/organizations/{organization_id}',
  });
};

/**
 * Update Organization
 * Updates a specified organization using the provided schema
 */
export const updateOrganizationOrganizationsOrganizationIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateOrganizationOrganizationsOrganizationIdPutData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).put<
    unknown,
    UpdateOrganizationOrganizationsOrganizationIdPutError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/organizations/{organization_id}',
  });
};

/**
 * Get All Organization Users
 * Gets all users in the organization
 */
export const getAllOrganizationUsersOrganizationsOrganizationIdUsersGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetAllOrganizationUsersOrganizationsOrganizationIdUsersGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    GetAllOrganizationUsersOrganizationsOrganizationIdUsersGetResponse,
    GetAllOrganizationUsersOrganizationsOrganizationIdUsersGetError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/organizations/{organization_id}/users',
  });
};

/**
 * Add User To Organization
 * Adds a user to the organization
 */
export const addUserToOrganizationOrganizationsOrganizationIdUsersPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AddUserToOrganizationOrganizationsOrganizationIdUsersPostData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).post<
    AddUserToOrganizationOrganizationsOrganizationIdUsersPostResponse,
    AddUserToOrganizationOrganizationsOrganizationIdUsersPostError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/organizations/{organization_id}/users',
  });
};

/**
 * Create Users Batch
 * Creates a batch of users
 */
export const createUsersBatchOrganizationsOrganizationIdUsersBatchPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateUsersBatchOrganizationsOrganizationIdUsersBatchPostData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).post<
    CreateUsersBatchOrganizationsOrganizationIdUsersBatchPostResponse,
    CreateUsersBatchOrganizationsOrganizationIdUsersBatchPostError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/organizations/{organization_id}/users/batch',
  });
};

/**
 * Safe Add User To Organization
 * Adds a user to the organization
 */
export const safeAddUserToOrganizationOrganizationsOrganizationIdUsersSafePost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      SafeAddUserToOrganizationOrganizationsOrganizationIdUsersSafePostData,
      ThrowOnError
    >
  ) => {
    return (options?.client ?? client).post<
      SafeAddUserToOrganizationOrganizationsOrganizationIdUsersSafePostResponse,
      SafeAddUserToOrganizationOrganizationsOrganizationIdUsersSafePostError,
      ThrowOnError
    >({
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
      security: [
        {
          fn: 'apiKey',
          in: 'header',
          name: 'authorization',
        },
      ],
      url: '/organizations/{organization_id}/users/safe',
    });
  };

/**
 * Get User In Organization
 * Get a user in an organization
 */
export const getUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdGet =
  <ThrowOnError extends boolean = false>(
    options: Options<
      GetUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdGetData,
      ThrowOnError
    >
  ) => {
    return (options?.client ?? client).get<
      GetUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdGetResponse,
      GetUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdGetError,
      ThrowOnError
    >({
      ...options,
      security: [
        {
          fn: 'apiKey',
          in: 'header',
          name: 'authorization',
        },
      ],
      url: '/organizations/{organization_id}/users/{organization_user_id}',
    });
  };

/**
 * Patch User In Organization
 * Updates a user in an organization. Set fields to "" to clear them (setting the value to null), leave null to ignore the update of these.
 */
export const patchUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdPatch =
  <ThrowOnError extends boolean = false>(
    options: Options<
      PatchUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdPatchData,
      ThrowOnError
    >
  ) => {
    return (options?.client ?? client).patch<
      unknown,
      PatchUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdPatchError,
      ThrowOnError
    >({
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
      security: [
        {
          fn: 'apiKey',
          in: 'header',
          name: 'authorization',
        },
      ],
      url: '/organizations/{organization_id}/users/{organization_user_id}',
    });
  };

/**
 * Remove User From Organization
 * Removes (disable) a user to the organization
 */
export const removeUserFromOrganizationOrganizationsOrganizationIdUsersUserIdDelete =
  <ThrowOnError extends boolean = false>(
    options: Options<
      RemoveUserFromOrganizationOrganizationsOrganizationIdUsersUserIdDeleteData,
      ThrowOnError
    >
  ) => {
    return (options?.client ?? client).delete<
      unknown,
      RemoveUserFromOrganizationOrganizationsOrganizationIdUsersUserIdDeleteError,
      ThrowOnError
    >({
      ...options,
      security: [
        {
          fn: 'apiKey',
          in: 'header',
          name: 'authorization',
        },
      ],
      url: '/organizations/{organization_id}/users/{user_id}',
    });
  };

/**
 * Get Addresses For User
 * Get all addresses for a user.
 */
export const getAddressesForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesGet =
  <ThrowOnError extends boolean = false>(
    options: Options<
      GetAddressesForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesGetData,
      ThrowOnError
    >
  ) => {
    return (options?.client ?? client).get<
      GetAddressesForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesGetResponse,
      GetAddressesForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesGetError,
      ThrowOnError
    >({
      ...options,
      security: [
        {
          fn: 'apiKey',
          in: 'header',
          name: 'authorization',
        },
      ],
      url: '/organizations/{organization_id}/users/{organization_user_id}/addresses',
    });
  };

/**
 * Create Address For User
 * Create an address for a business.
 */
export const createAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesPost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      CreateAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesPostData,
      ThrowOnError
    >
  ) => {
    return (options?.client ?? client).post<
      CreateAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesPostResponse,
      CreateAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesPostError,
      ThrowOnError
    >({
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
      security: [
        {
          fn: 'apiKey',
          in: 'header',
          name: 'authorization',
        },
      ],
      url: '/organizations/{organization_id}/users/{organization_user_id}/addresses',
    });
  };

/**
 * Delete Address From User
 * Removes an address from a user.
 */
export const deleteAddressFromUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesAddressIdDelete =
  <ThrowOnError extends boolean = false>(
    options: Options<
      DeleteAddressFromUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesAddressIdDeleteData,
      ThrowOnError
    >
  ) => {
    return (options?.client ?? client).delete<
      unknown,
      DeleteAddressFromUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesAddressIdDeleteError,
      ThrowOnError
    >({
      ...options,
      security: [
        {
          fn: 'apiKey',
          in: 'header',
          name: 'authorization',
        },
      ],
      url: '/organizations/{organization_id}/users/{organization_user_id}/addresses/{address_id}',
    });
  };

/**
 * Update Address For User
 * Update an address for a user.
 */
export const updateAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesAddressIdPut =
  <ThrowOnError extends boolean = false>(
    options: Options<
      UpdateAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesAddressIdPutData,
      ThrowOnError
    >
  ) => {
    return (options?.client ?? client).put<
      unknown,
      UpdateAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesAddressIdPutError,
      ThrowOnError
    >({
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
      security: [
        {
          fn: 'apiKey',
          in: 'header',
          name: 'authorization',
        },
      ],
      url: '/organizations/{organization_id}/users/{organization_user_id}/addresses/{address_id}',
    });
  };

/**
 * Get Ui Configuration
 * Returns the organization configuration.
 */
export const getUiConfigurationOrganizationsExternalUiConfigurationGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    GetUiConfigurationOrganizationsExternalUiConfigurationGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    GetUiConfigurationOrganizationsExternalUiConfigurationGetResponse,
    unknown,
    ThrowOnError
  >({
    ...options,
    url: '/organizations/external/ui-configuration',
  });
};

/**
 * Read Organization Configuration
 * Get the configuration of an organization and, if the query parameter
 * 'cache=invalidate' is provider, will invalidate the cache and refresh the configuration
 */
export const readOrganizationConfigurationOrganizationsOrganizationKeyConfigurationGet =
  <ThrowOnError extends boolean = false>(
    options: Options<
      ReadOrganizationConfigurationOrganizationsOrganizationKeyConfigurationGetData,
      ThrowOnError
    >
  ) => {
    return (options?.client ?? client).get<
      ReadOrganizationConfigurationOrganizationsOrganizationKeyConfigurationGetResponse,
      ReadOrganizationConfigurationOrganizationsOrganizationKeyConfigurationGetError,
      ThrowOnError
    >({
      ...options,
      url: '/organizations/{organization_key}/configuration',
    });
  };

/**
 * Get Groups For Organization
 * Returns the groups configured for the organization
 */
export const getGroupsForOrganizationOrganizationsOrganizationIdGroupsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetGroupsForOrganizationOrganizationsOrganizationIdGroupsGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    GetGroupsForOrganizationOrganizationsOrganizationIdGroupsGetResponse,
    GetGroupsForOrganizationOrganizationsOrganizationIdGroupsGetError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/organizations/{organization_id}/groups',
  });
};

/**
 * Create Group
 * Creates a new group using the provided schema
 */
export const createGroupOrganizationsOrganizationIdGroupsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateGroupOrganizationsOrganizationIdGroupsPostData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).post<
    CreateGroupOrganizationsOrganizationIdGroupsPostResponse,
    CreateGroupOrganizationsOrganizationIdGroupsPostError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/organizations/{organization_id}/groups',
  });
};

/**
 * Delete Group
 * Delete a group, if the group is not a system group.
 */
export const deleteGroupOrganizationsOrganizationIdGroupsGroupIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteGroupOrganizationsOrganizationIdGroupsGroupIdDeleteData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).delete<
    unknown,
    DeleteGroupOrganizationsOrganizationIdGroupsGroupIdDeleteError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/organizations/{organization_id}/groups/{group_id}',
  });
};

/**
 * Get Group
 * Get an existing group.
 */
export const getGroupOrganizationsOrganizationIdGroupsGroupIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetGroupOrganizationsOrganizationIdGroupsGroupIdGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    GetGroupOrganizationsOrganizationIdGroupsGroupIdGetResponse,
    GetGroupOrganizationsOrganizationIdGroupsGroupIdGetError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/organizations/{organization_id}/groups/{group_id}',
  });
};

/**
 * Update Group
 * Updates a specified group using the provided schema
 */
export const updateGroupOrganizationsOrganizationIdGroupsGroupIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateGroupOrganizationsOrganizationIdGroupsGroupIdPutData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).put<
    unknown,
    UpdateGroupOrganizationsOrganizationIdGroupsGroupIdPutError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/organizations/{organization_id}/groups/{group_id}',
  });
};

/**
 * Remove User From Group
 * Removes a user grom a group.
 */
export const removeUserFromGroupOrganizationsOrganizationIdGroupsGroupIdUsersOrganizationUserIdDelete =
  <ThrowOnError extends boolean = false>(
    options: Options<
      RemoveUserFromGroupOrganizationsOrganizationIdGroupsGroupIdUsersOrganizationUserIdDeleteData,
      ThrowOnError
    >
  ) => {
    return (options?.client ?? client).delete<
      unknown,
      RemoveUserFromGroupOrganizationsOrganizationIdGroupsGroupIdUsersOrganizationUserIdDeleteError,
      ThrowOnError
    >({
      ...options,
      security: [
        {
          fn: 'apiKey',
          in: 'header',
          name: 'authorization',
        },
      ],
      url: '/organizations/{organization_id}/groups/{group_id}/users/{organization_user_id}',
    });
  };

/**
 * Add User To Group
 * Adds a user to a group.
 */
export const addUserToGroupOrganizationsOrganizationIdGroupsGroupIdUsersOrganizationUserIdPost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      AddUserToGroupOrganizationsOrganizationIdGroupsGroupIdUsersOrganizationUserIdPostData,
      ThrowOnError
    >
  ) => {
    return (options?.client ?? client).post<
      unknown,
      AddUserToGroupOrganizationsOrganizationIdGroupsGroupIdUsersOrganizationUserIdPostError,
      ThrowOnError
    >({
      ...options,
      security: [
        {
          fn: 'apiKey',
          in: 'header',
          name: 'authorization',
        },
      ],
      url: '/organizations/{organization_id}/groups/{group_id}/users/{organization_user_id}',
    });
  };

/**
 * Get Global Feature Flags
 * Returns the global feature flags (flags that apply to all organization)
 */
export const getGlobalFeatureFlagsFeaturesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetGlobalFeatureFlagsFeaturesGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetGlobalFeatureFlagsFeaturesGetResponse,
    unknown,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/features',
  });
};

/**
 * Set Global Feature Flags
 * Sets the global feature flags for the system (flags that apply to all organizations)
 */
export const setGlobalFeatureFlagsFeaturesPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SetGlobalFeatureFlagsFeaturesPutData, ThrowOnError>
) => {
  return (options?.client ?? client).put<
    unknown,
    SetGlobalFeatureFlagsFeaturesPutError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/features',
  });
};

/**
 * Get Organization Feature Flags
 * Returns a tenant's specific feature flags
 */
export const getOrganizationFeatureFlagsFeaturesOrganizationsOrganizationIdGet =
  <ThrowOnError extends boolean = false>(
    options?: Options<
      GetOrganizationFeatureFlagsFeaturesOrganizationsOrganizationIdGetData,
      ThrowOnError
    >
  ) => {
    return (options?.client ?? client).get<
      GetOrganizationFeatureFlagsFeaturesOrganizationsOrganizationIdGetResponse,
      unknown,
      ThrowOnError
    >({
      ...options,
      security: [
        {
          fn: 'apiKey',
          in: 'header',
          name: 'authorization',
        },
      ],
      url: '/features/organizations/{organization_id}',
    });
  };

/**
 * Set Organization Feature Flags
 * Sets a tenant specific feature flags
 */
export const setOrganizationFeatureFlagsFeaturesOrganizationsOrganizationIdPut =
  <ThrowOnError extends boolean = false>(
    options: Options<
      SetOrganizationFeatureFlagsFeaturesOrganizationsOrganizationIdPutData,
      ThrowOnError
    >
  ) => {
    return (options?.client ?? client).put<
      unknown,
      SetOrganizationFeatureFlagsFeaturesOrganizationsOrganizationIdPutError,
      ThrowOnError
    >({
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
      security: [
        {
          fn: 'apiKey',
          in: 'header',
          name: 'authorization',
        },
      ],
      url: '/features/organizations/{organization_id}',
    });
  };

/**
 * Cache Action
 * Load or invalidates the cache for the feature flags
 */
export const cacheActionFeaturesCachePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CacheActionFeaturesCachePostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    unknown,
    CacheActionFeaturesCachePostError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/features/cache',
  });
};

/**
 * Get Share Links By User
 * Returns the existing share links for a user
 */
export const getShareLinksByUserShareUsersOrganizationUserIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetShareLinksByUserShareUsersOrganizationUserIdGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    GetShareLinksByUserShareUsersOrganizationUserIdGetResponse,
    GetShareLinksByUserShareUsersOrganizationUserIdGetError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/share/users/{organization_user_id}',
  });
};

/**
 * Get Share Links By External Id
 * Returns the existing share links for a resource
 */
export const getShareLinksByExternalIdShareResourcesExternalIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetShareLinksByExternalIdShareResourcesExternalIdGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    GetShareLinksByExternalIdShareResourcesExternalIdGetResponse,
    GetShareLinksByExternalIdShareResourcesExternalIdGetError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/share/resources/{external_id}',
  });
};

/**
 * Create Share Link Batch
 * Creates multiple invitations for the given users and resources
 */
export const createShareLinkBatchShareBatchPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateShareLinkBatchShareBatchPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    unknown,
    CreateShareLinkBatchShareBatchPostError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/share/batch',
  });
};

/**
 * Create Share Link
 * Creates an invitation for the given user and resource
 */
export const createShareLinkSharePost = <ThrowOnError extends boolean = false>(
  options: Options<CreateShareLinkSharePostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    unknown,
    CreateShareLinkSharePostError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/share',
  });
};

/**
 * Delete Share Link
 * Deletes an invitation
 */
export const deleteShareLinkShareShareLinkIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteShareLinkShareShareLinkIdDeleteData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    unknown,
    DeleteShareLinkShareShareLinkIdDeleteError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/share/{share_link_id}',
  });
};

/**
 * Update Share Link
 * Modify an invitation (mostly deactivate / reactivate)
 */
export const updateShareLinkShareShareLinkIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateShareLinkShareShareLinkIdPutData, ThrowOnError>
) => {
  return (options?.client ?? client).put<
    unknown,
    UpdateShareLinkShareShareLinkIdPutError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/share/{share_link_id}',
  });
};

/**
 * Delete All Api Keys
 * Deletes all API keys for the current user
 */
export const deleteAllApiKeysApiKeysDelete = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<DeleteAllApiKeysApiKeysDeleteData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<unknown, unknown, ThrowOnError>({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/api-keys',
  });
};

/**
 * Get Api Keys
 * Get all API keys for the current user
 */
export const getApiKeysApiKeysGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiKeysApiKeysGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetApiKeysApiKeysGetResponse,
    unknown,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/api-keys',
  });
};

/**
 * Create Api Key
 * Create a new API key for the current user
 */
export const createApiKeyApiKeysPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateApiKeyApiKeysPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    CreateApiKeyApiKeysPostResponse,
    CreateApiKeyApiKeysPostError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/api-keys',
  });
};

/**
 * Delete Api Key
 * Deletes an API key using its ID
 */
export const deleteApiKeyApiKeysApiKeyIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteApiKeyApiKeysApiKeyIdDeleteData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    unknown,
    DeleteApiKeyApiKeysApiKeyIdDeleteError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/api-keys/{api_key_id}',
  });
};

/**
 * Get Businesses For User
 * Returns the businesses for the organization
 */
export const getBusinessesForUserOrganizationsOrganizationIdBusinessesUsersOrganizationUserIdGet =
  <ThrowOnError extends boolean = false>(
    options: Options<
      GetBusinessesForUserOrganizationsOrganizationIdBusinessesUsersOrganizationUserIdGetData,
      ThrowOnError
    >
  ) => {
    return (options?.client ?? client).get<
      GetBusinessesForUserOrganizationsOrganizationIdBusinessesUsersOrganizationUserIdGetResponse,
      GetBusinessesForUserOrganizationsOrganizationIdBusinessesUsersOrganizationUserIdGetError,
      ThrowOnError
    >({
      ...options,
      security: [
        {
          fn: 'apiKey',
          in: 'header',
          name: 'authorization',
        },
      ],
      url: '/organizations/{organization_id}/businesses/users/{organization_user_id}',
    });
  };

/**
 * Get Businesses For Organization
 * Returns the businesses for the organization
 */
export const getBusinessesForOrganizationOrganizationsOrganizationIdBusinessesGet =
  <ThrowOnError extends boolean = false>(
    options: Options<
      GetBusinessesForOrganizationOrganizationsOrganizationIdBusinessesGetData,
      ThrowOnError
    >
  ) => {
    return (options?.client ?? client).get<
      GetBusinessesForOrganizationOrganizationsOrganizationIdBusinessesGetResponse,
      GetBusinessesForOrganizationOrganizationsOrganizationIdBusinessesGetError,
      ThrowOnError
    >({
      ...options,
      security: [
        {
          fn: 'apiKey',
          in: 'header',
          name: 'authorization',
        },
      ],
      url: '/organizations/{organization_id}/businesses',
    });
  };

/**
 * Create Business
 * Creates a new business using the provided schema
 */
export const createBusinessOrganizationsOrganizationIdBusinessesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateBusinessOrganizationsOrganizationIdBusinessesPostData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).post<
    CreateBusinessOrganizationsOrganizationIdBusinessesPostResponse,
    CreateBusinessOrganizationsOrganizationIdBusinessesPostError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/organizations/{organization_id}/businesses',
  });
};

/**
 * Delete Business
 * Delete a business, if the business (soft delete).
 */
export const deleteBusinessOrganizationsOrganizationIdBusinessesBusinessIdDelete =
  <ThrowOnError extends boolean = false>(
    options: Options<
      DeleteBusinessOrganizationsOrganizationIdBusinessesBusinessIdDeleteData,
      ThrowOnError
    >
  ) => {
    return (options?.client ?? client).delete<
      unknown,
      DeleteBusinessOrganizationsOrganizationIdBusinessesBusinessIdDeleteError,
      ThrowOnError
    >({
      ...options,
      security: [
        {
          fn: 'apiKey',
          in: 'header',
          name: 'authorization',
        },
      ],
      url: '/organizations/{organization_id}/businesses/{business_id}',
    });
  };

/**
 * Get Business
 * Get an existing business.
 */
export const getBusinessOrganizationsOrganizationIdBusinessesBusinessIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetBusinessOrganizationsOrganizationIdBusinessesBusinessIdGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    GetBusinessOrganizationsOrganizationIdBusinessesBusinessIdGetResponse,
    GetBusinessOrganizationsOrganizationIdBusinessesBusinessIdGetError,
    ThrowOnError
  >({
    ...options,
    security: [
      {
        fn: 'apiKey',
        in: 'header',
        name: 'authorization',
      },
    ],
    url: '/organizations/{organization_id}/businesses/{business_id}',
  });
};

/**
 * Update Business
 * Updates a specified business using the provided schema
 */
export const updateBusinessOrganizationsOrganizationIdBusinessesBusinessIdPut =
  <ThrowOnError extends boolean = false>(
    options: Options<
      UpdateBusinessOrganizationsOrganizationIdBusinessesBusinessIdPutData,
      ThrowOnError
    >
  ) => {
    return (options?.client ?? client).put<
      unknown,
      UpdateBusinessOrganizationsOrganizationIdBusinessesBusinessIdPutError,
      ThrowOnError
    >({
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
      security: [
        {
          fn: 'apiKey',
          in: 'header',
          name: 'authorization',
        },
      ],
      url: '/organizations/{organization_id}/businesses/{business_id}',
    });
  };

/**
 * Create Business Batch
 * Creates new businesses in batch using the provided array of schema
 */
export const createBusinessBatchOrganizationsOrganizationIdBusinessesBatchPost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      CreateBusinessBatchOrganizationsOrganizationIdBusinessesBatchPostData,
      ThrowOnError
    >
  ) => {
    return (options?.client ?? client).post<
      CreateBusinessBatchOrganizationsOrganizationIdBusinessesBatchPostResponse,
      CreateBusinessBatchOrganizationsOrganizationIdBusinessesBatchPostError,
      ThrowOnError
    >({
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
      security: [
        {
          fn: 'apiKey',
          in: 'header',
          name: 'authorization',
        },
      ],
      url: '/organizations/{organization_id}/businesses/batch',
    });
  };

/**
 * Get Business Users
 * Adds a user to a business.
 */
export const getBusinessUsersOrganizationsOrganizationIdBusinessesBusinessIdUsersGet =
  <ThrowOnError extends boolean = false>(
    options: Options<
      GetBusinessUsersOrganizationsOrganizationIdBusinessesBusinessIdUsersGetData,
      ThrowOnError
    >
  ) => {
    return (options?.client ?? client).get<
      GetBusinessUsersOrganizationsOrganizationIdBusinessesBusinessIdUsersGetResponse,
      GetBusinessUsersOrganizationsOrganizationIdBusinessesBusinessIdUsersGetError,
      ThrowOnError
    >({
      ...options,
      security: [
        {
          fn: 'apiKey',
          in: 'header',
          name: 'authorization',
        },
      ],
      url: '/organizations/{organization_id}/businesses/{business_id}/users',
    });
  };

/**
 * Remove User From Business
 * Removes a user grom a business.
 */
export const removeUserFromBusinessOrganizationsOrganizationIdBusinessesBusinessIdUsersOrganizationUserIdDelete =
  <ThrowOnError extends boolean = false>(
    options: Options<
      RemoveUserFromBusinessOrganizationsOrganizationIdBusinessesBusinessIdUsersOrganizationUserIdDeleteData,
      ThrowOnError
    >
  ) => {
    return (options?.client ?? client).delete<
      unknown,
      RemoveUserFromBusinessOrganizationsOrganizationIdBusinessesBusinessIdUsersOrganizationUserIdDeleteError,
      ThrowOnError
    >({
      ...options,
      security: [
        {
          fn: 'apiKey',
          in: 'header',
          name: 'authorization',
        },
      ],
      url: '/organizations/{organization_id}/businesses/{business_id}/users/{organization_user_id}',
    });
  };

/**
 * Add User To Business
 * Adds a user to a business.
 */
export const addUserToBusinessOrganizationsOrganizationIdBusinessesBusinessIdUsersOrganizationUserIdPost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      AddUserToBusinessOrganizationsOrganizationIdBusinessesBusinessIdUsersOrganizationUserIdPostData,
      ThrowOnError
    >
  ) => {
    return (options?.client ?? client).post<
      unknown,
      AddUserToBusinessOrganizationsOrganizationIdBusinessesBusinessIdUsersOrganizationUserIdPostError,
      ThrowOnError
    >({
      ...options,
      security: [
        {
          fn: 'apiKey',
          in: 'header',
          name: 'authorization',
        },
      ],
      url: '/organizations/{organization_id}/businesses/{business_id}/users/{organization_user_id}',
    });
  };

/**
 * Get Addresses For Business
 * Get all addresses for a business.
 */
export const getAddressesForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesGet =
  <ThrowOnError extends boolean = false>(
    options: Options<
      GetAddressesForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesGetData,
      ThrowOnError
    >
  ) => {
    return (options?.client ?? client).get<
      GetAddressesForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesGetResponse,
      GetAddressesForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesGetError,
      ThrowOnError
    >({
      ...options,
      security: [
        {
          fn: 'apiKey',
          in: 'header',
          name: 'authorization',
        },
      ],
      url: '/organizations/{organization_id}/businesses/{business_id}/addresses',
    });
  };

/**
 * Create Address For Business
 * Create an address for a business.
 */
export const createAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesPost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      CreateAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesPostData,
      ThrowOnError
    >
  ) => {
    return (options?.client ?? client).post<
      CreateAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesPostResponse,
      CreateAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesPostError,
      ThrowOnError
    >({
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
      security: [
        {
          fn: 'apiKey',
          in: 'header',
          name: 'authorization',
        },
      ],
      url: '/organizations/{organization_id}/businesses/{business_id}/addresses',
    });
  };

/**
 * Delete Address From Business
 * Removes an address from a business.
 */
export const deleteAddressFromBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesAddressIdDelete =
  <ThrowOnError extends boolean = false>(
    options: Options<
      DeleteAddressFromBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesAddressIdDeleteData,
      ThrowOnError
    >
  ) => {
    return (options?.client ?? client).delete<
      unknown,
      DeleteAddressFromBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesAddressIdDeleteError,
      ThrowOnError
    >({
      ...options,
      security: [
        {
          fn: 'apiKey',
          in: 'header',
          name: 'authorization',
        },
      ],
      url: '/organizations/{organization_id}/businesses/{business_id}/addresses/{address_id}',
    });
  };

/**
 * Update Address For Business
 * Update an address for a business.
 */
export const updateAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesAddressIdPut =
  <ThrowOnError extends boolean = false>(
    options: Options<
      UpdateAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesAddressIdPutData,
      ThrowOnError
    >
  ) => {
    return (options?.client ?? client).put<
      unknown,
      UpdateAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesAddressIdPutError,
      ThrowOnError
    >({
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
      security: [
        {
          fn: 'apiKey',
          in: 'header',
          name: 'authorization',
        },
      ],
      url: '/organizations/{organization_id}/businesses/{business_id}/addresses/{address_id}',
    });
  };

/**
 * Get Root
 * Provide the root level route for the service
 *
 * Returns:
 * dict: Name of the API and the version
 */
export const getRootGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetRootGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
    ...options,
    url: '/',
  });
};

/**
 * Get Status Check
 * Get the status of the API and the resources.
 *
 * Returns:
 * dict: Information about the status, the dependency status and the version.
 */
export const getStatusCheckStatusGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetStatusCheckStatusGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
    ...options,
    url: '/status',
  });
};
