// This file is auto-generated by @hey-api/openapi-ts

/**
 * Fields required to add a user to an organization
 */
export type AddUserToOrganizationSchema = {
  organizationId: string;
  userId: string;
  groups?: Array<string> | null;
  firstName?: string | null;
  lastName?: string | null;
  email?: string | null;
  phoneNumber?: string | null;
};

/**
 * Base schema for addresses
 */
export type AddressBaseSchema = {
  organizationId: string;
  entityId: string;
  entityType: EntityTypes;
  street?: string | null;
  city?: string | null;
  state: string;
  country: string;
  zipCode?: string | null;
  extra: string;
};

/**
 * API key id only schema
 */
export type ApiKeyIdOnlySchema = {
  id: string;
  name: string;
  createdAt: number;
};

/**
 * API key schema
 */
export type ApiKeySchema = {
  id: string;
  name: string;
  createdAt: number;
  apiKey: string;
};

/**
 * Authentication token types
 */
export type AuthTokenTypes =
  | 'AUTH_CODE'
  | 'MAGIC_LINK'
  | 'COMBINED'
  | 'SHARE_LINK';

/**
 * Authentication token types
 */
export const AuthTokenTypes = {
  AUTH_CODE: 'AUTH_CODE',
  MAGIC_LINK: 'MAGIC_LINK',
  COMBINED: 'COMBINED',
  SHARE_LINK: 'SHARE_LINK',
} as const;

/**
 * Schema used to return information on groups along with users
 */
export type BasicGroupInformationSchema = {
  id: string;
  name: string;
  system: boolean;
  workgroup?: boolean | null;
};

/**
 * Response for a simple user query, for display, used with digest
 */
export type BasicUserProfile = {
  email?: string | null;
  phoneNumber?: string | null;
  lastActive?: number | null;
  disabled?: boolean | null;
  firstName: string;
  lastName: string;
  avatarUri?: string | null;
  id: string;
};

/**
 * Base request schema for the business requests
 */
export type BusinessBaseSchema = {
  organizationId?: string | null;
  primaryContactId?: string | null;
  primaryAddressId?: string | null;
  name: string;
  email: string;
  businessType: BusinessTypes;
  uniqueBusinessIdentifier: string;
  users?: Array<SafeUserCreate> | null;
};

/**
 * Id returned when a business is successfully created
 */
export type BusinessCreatedSchema = {
  id: string;
  users?: Array<BasicUserProfile> | null;
};

/**
 * Response for a user query, including the count
 */
export type BusinessQueryResultSchema = {
  items: Array<ExistingBusinessSchemaOutput>;
  totalCount: number;
};

/**
 * Types of users
 */
export type BusinessTypes =
  | 'CORPORATION'
  | 'LLC'
  | 'LLP'
  | 'GP'
  | 'LP'
  | 'TRUST';

/**
 * Types of users
 */
export const BusinessTypes = {
  CORPORATION: 'CORPORATION',
  LLC: 'LLC',
  LLP: 'LLP',
  GP: 'GP',
  LP: 'LP',
  TRUST: 'TRUST',
} as const;

/**
 * Create api key schema
 */
export type CreateApiKeySchema = {
  name: string;
};

/**
 * Input for creating a batch of businesses
 */
export type CreateBusinessBatchArgs = {
  businesses?: Array<BusinessBaseSchema>;
  organizationId: string;
};

/**
 * Schema for when creating an organization
 */
export type CreateOrganizationSchema = {
  name: string;
  dnsPrefix: string;
  logoUri: string;
  logoUriSmall: string;
  colors: unknown;
  syncEnabled?: boolean;
  syncKeySecretName?: string | null;
  syncOutboundQueueName?: string | null;
  backofficeJwtTtlMinutes: number;
  clientAppsJwtTtlMinutes: number;
  databaseName: string;
  documentBucket: string;
  cacheEncryptionKey: string;
  root?: boolean | null;
};

/**
 * Schema for creating multiple share links at the same time
 */
export type CreateShareLinkBatch = {
  shareLinks: Array<CreateShareLinkSchema>;
};

/**
 * Schema for initiating a token based auth
 */
export type CreateShareLinkSchema = {
  organizationUserId: string;
  redirectPath: string;
  externalId: string;
  senderName?: string | null;
  requestName?: string | null;
  subjectOverride?: string | null;
  messageOverride?: string | null;
  tasksOverride?: Array<TaskOverride> | null;
};

/**
 * Schema for initiating a token based auth
 */
export type CreateTokenAuthSchema = {
  organizationUserId?: string | null;
  recipient: string;
  organizationKey?: string | null;
  tokenType: AuthTokenTypes;
};

/**
 * Input for creating a batch of users
 */
export type CreateUserBatchArgs = {
  users?: Array<SafeUserCreate>;
  organizationId: string;
};

/**
 * Created address schema
 */
export type CreatedAddressSchema = {
  id: string;
};

/**
 * Type of entity for the address
 */
export type EntityTypes = 'INDIVIDUAL' | 'BUSINESS';

/**
 * Type of entity for the address
 */
export const EntityTypes = {
  INDIVIDUAL: 'INDIVIDUAL',
  BUSINESS: 'BUSINESS',
} as const;

/**
 * Existing address schema
 */
export type ExistingAddressSchema = {
  id: string;
  organizationId: string;
  entityId: string;
  entityType: EntityTypes;
  street?: string | null;
  city?: string | null;
  state: string;
  country: string;
  zipCode?: string | null;
  extra: string;
};

/**
 * Existing business schema
 */
export type ExistingBusinessSchemaInput = {
  id: string;
  organizationId: string;
  primaryContactId?: string | null;
  primaryAddressId?: string | null;
  name: string;
  email: string;
  businessType: BusinessTypes;
  uniqueBusinessIdentifier: string;
  addresses?: Array<ExistingAddressSchema> | null;
  users?: Array<BasicUserProfile> | null;
};

/**
 * Existing business schema
 */
export type ExistingBusinessSchemaOutput = {
  id: string;
  organizationId: string;
  primaryContactId?: string | null;
  primaryAddressId?: string | null;
  name: string;
  email: string;
  businessType: BusinessTypes;
  uniqueBusinessIdentifier: string;
  addresses?: Array<ExistingAddressSchema> | null;
  users?: Array<BasicUserProfile> | null;
};

/**
 * Existing group schema
 */
export type ExistingGroupSchema = {
  organizationId: string;
  name: string;
  email?: string | null;
  permissions: unknown;
  system: boolean;
  workgroup?: boolean | null;
  createdAt?: number | null;
  updatedAt?: number | null;
  id: string;
};

/**
 * Full configuration, for use by the service
 */
export type ExistingOrganizationFullConfigurationSchema = {
  name: string;
  dnsPrefix: string;
  logoUri: string;
  logoUriSmall: string;
  colors: unknown;
  syncEnabled?: boolean;
  syncKeySecretName?: string | null;
  syncOutboundQueueName?: string | null;
  backofficeJwtTtlMinutes: number;
  clientAppsJwtTtlMinutes: number;
  databaseName: string;
  documentBucket: string;
  cacheEncryptionKey: string;
  root?: boolean | null;
  id: string;
  groups?: Array<ExistingGroupSchema> | null;
};

/**
 * Existing organization schema
 */
export type ExistingOrganizationSchema = {
  name: string;
  dnsPrefix: string;
  logoUri: string;
  logoUriSmall: string;
  colors: unknown;
  syncEnabled?: boolean;
  syncKeySecretName?: string | null;
  syncOutboundQueueName?: string | null;
  backofficeJwtTtlMinutes: number;
  clientAppsJwtTtlMinutes: number;
  id: string;
};

/**
 * Schema used to send an action to the cache
 */
export type FeatureFlagCacheActionSchema = {
  action: FeatureFlagCacheActions;
};

/**
 * Actions that can be posted on the cache
 */
export type FeatureFlagCacheActions = 'INVALIDATE' | 'REFRESH';

/**
 * Actions that can be posted on the cache
 */
export const FeatureFlagCacheActions = {
  INVALIDATE: 'INVALIDATE',
  REFRESH: 'REFRESH',
} as const;

/**
 * Base request schema for the a feature flag
 */
export type FeatureFlagSchema = {
  name: string;
  activated: boolean;
};

/**
 * Base request schema for the groups requests
 */
export type GroupBaseSchema = {
  organizationId: string;
  name: string;
  email?: string | null;
  permissions: unknown;
  system: boolean;
  workgroup?: boolean | null;
  createdAt?: number | null;
  updatedAt?: number | null;
};

/**
 * Id returned when a user is successfully created
 */
export type GroupCreatedSchema = {
  id: string;
};

export type HttpValidationError = {
  detail?: Array<ValidationError>;
};

/**
 * Login with API key schema
 */
export type LoginWithApiKeySchema = {
  id: string;
  apiKey: string;
};

/**
 * Types of notification
 */
export type NotificationTypes = 'EMAIL' | 'SMS' | 'IN_APP' | 'PUSH';

/**
 * Types of notification
 */
export const NotificationTypes = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  IN_APP: 'IN_APP',
  PUSH: 'PUSH',
} as const;

/**
 * Id of the created organization
 */
export type OrganizationCreatedSchema = {
  id: string;
};

/**
 * UI Configuration returned with a tenant.
 */
export type OrganizationUiConfiguration = {
  name: string;
  dnsPrefix: string;
  logoUri: string;
  logoUriSmall: string;
  colors: unknown;
};

/**
 * Response for when an organization user is returned
 */
export type OrganizationUserSchema = {
  email?: string | null;
  phoneNumber?: string | null;
  lastActive?: number | null;
  disabled?: boolean | null;
  firstName: string;
  lastName: string;
  avatarUri?: string | null;
  id: string;
  groups?: Array<string> | Array<BasicGroupInformationSchema> | null;
};

/**
 * Request schema for the safe user create
 */
export type SafeUserCreate = {
  email?: string | null;
  phoneNumber?: string | null;
  lastActive?: number | null;
  disabled?: boolean | null;
  firstName: string;
  lastName: string;
  avatarUri?: string | null;
  groups?: Array<string> | null;
};

/**
 * Base share link model
 */
export type ShareLinkBaseSchema = {
  id: string;
  organizationUserId: string;
  recipient: string;
  recipientType: NotificationTypes;
  expiresAt: number;
  redirectPath: string;
  externalId: string;
};

/**
 * Schema for task override
 */
export type TaskOverride = {
  taskType: string;
  taskName: string;
  taskPath: string;
};

/**
 * Fields required to update an organization user
 */
export type UpdateOrganizationUserSchema = {
  userId: string;
  firstName?: string | null;
  lastName?: string | null;
  email?: string | null;
  phoneNumber?: string | null;
};

/**
 * Schema to update a shared link, need to be careful when changing this
 */
export type UpdateShareLinkSchema = {
  id: string;
  disabled: boolean;
  disabledDate?: number | null;
  disabledReason: string;
};

/**
 * Id returned when a user is successfully added to an organization
 */
export type UserAddedToOrganizationSchema = {
  id: string;
};

/**
 * Request schema to be used for creating a new user
 */
export type UserCreate = {
  email?: string | null;
  phoneNumber?: string | null;
  lastActive?: number | null;
  disabled?: boolean | null;
  firstName: string;
  lastName: string;
  avatarUri?: string | null;
};

/**
 * Response mapping for the user created request
 */
export type UserCreatedSchema = {
  id: string;
};

/**
 * Response mapping for the user profile and user data
 */
export type UserProfile = {
  email?: string | null;
  phoneNumber?: string | null;
  lastActive?: number | null;
  disabled?: boolean | null;
  firstName: string;
  lastName: string;
  avatarUri?: string | null;
  id: string;
  activeOrganization?: string | null;
  activeOrganizationUserId?: string | null;
  digest?: string | null;
};

/**
 * Response for a user query, including the count
 */
export type UserQueryResultSchema = {
  items: Array<OrganizationUserSchema>;
  totalCount: number;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type ReadUsersUsersGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/users/';
};

export type ReadUsersUsersGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
};

export type ReadUsersUsersGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type CreateUserUsersPostData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: '/users/';
};

export type CreateUserUsersPostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateUserUsersPostError =
  CreateUserUsersPostErrors[keyof CreateUserUsersPostErrors];

export type CreateUserUsersPostResponses = {
  /**
   * Successful Response
   */
  200: UserCreatedSchema;
};

export type CreateUserUsersPostResponse =
  CreateUserUsersPostResponses[keyof CreateUserUsersPostResponses];

export type ReadUserMeUsersMeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/users/me';
};

export type ReadUserMeUsersMeGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
};

export type ReadUserMeUsersMeGetResponses = {
  /**
   * Successful Response
   */
  200: UserProfile;
};

export type ReadUserMeUsersMeGetResponse =
  ReadUserMeUsersMeGetResponses[keyof ReadUserMeUsersMeGetResponses];

export type ReadUserUsersUsernameGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/users/{username}';
};

export type ReadUserUsersUsernameGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
};

export type ReadUserUsersUsernameGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RefreshTokenTokenRefreshGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/token/refresh';
};

export type RefreshTokenTokenRefreshGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
};

export type RefreshTokenTokenRefreshGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type LoginViaTokenLoginTokenPostData = {
  body: CreateTokenAuthSchema;
  path?: never;
  query?: {
    backoffice?: boolean;
  };
  url: '/login/token';
};

export type LoginViaTokenLoginTokenPostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginViaTokenLoginTokenPostError =
  LoginViaTokenLoginTokenPostErrors[keyof LoginViaTokenLoginTokenPostErrors];

export type LoginViaTokenLoginTokenPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type LoginViaGoogleLoginGoogleGetData = {
  body?: never;
  path?: never;
  query?: {
    backoffice?: boolean;
  };
  url: '/login/google';
};

export type LoginViaGoogleLoginGoogleGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginViaGoogleLoginGoogleGetError =
  LoginViaGoogleLoginGoogleGetErrors[keyof LoginViaGoogleLoginGoogleGetErrors];

export type LoginViaGoogleLoginGoogleGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AuthViaGoogleAuthGoogleGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/google';
};

export type AuthViaGoogleAuthGoogleGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
};

export type AuthViaGoogleAuthGoogleGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type LoginViaMicrosoftLoginMicrosoftGetData = {
  body?: never;
  path?: never;
  query?: {
    backoffice?: boolean;
  };
  url: '/login/microsoft';
};

export type LoginViaMicrosoftLoginMicrosoftGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginViaMicrosoftLoginMicrosoftGetError =
  LoginViaMicrosoftLoginMicrosoftGetErrors[keyof LoginViaMicrosoftLoginMicrosoftGetErrors];

export type LoginViaMicrosoftLoginMicrosoftGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AuthViaMicrosoftAuthMicrosoftGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/microsoft';
};

export type AuthViaMicrosoftAuthMicrosoftGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
};

export type AuthViaMicrosoftAuthMicrosoftGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AuthViaMagicLinkAuthLinkGetData = {
  body?: never;
  path?: never;
  query: {
    token: string;
    redirect?: boolean;
    path?: string | null;
  };
  url: '/auth/link';
};

export type AuthViaMagicLinkAuthLinkGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthViaMagicLinkAuthLinkGetError =
  AuthViaMagicLinkAuthLinkGetErrors[keyof AuthViaMagicLinkAuthLinkGetErrors];

export type AuthViaMagicLinkAuthLinkGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type LoginViaApiKeyLoginApiKeyPostData = {
  body: LoginWithApiKeySchema;
  path?: never;
  query?: never;
  url: '/login/api-key';
};

export type LoginViaApiKeyLoginApiKeyPostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginViaApiKeyLoginApiKeyPostError =
  LoginViaApiKeyLoginApiKeyPostErrors[keyof LoginViaApiKeyLoginApiKeyPostErrors];

export type LoginViaApiKeyLoginApiKeyPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AuthViaAuthCodeAuthCodeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/code';
};

export type AuthViaAuthCodeAuthCodeGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
};

export type AuthViaAuthCodeAuthCodeGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type LogoutLogoutGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/logout';
};

export type LogoutLogoutGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
};

export type LogoutLogoutGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetAllOrganizationsOrganizationsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/organizations';
};

export type GetAllOrganizationsOrganizationsGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
};

export type GetAllOrganizationsOrganizationsGetResponses = {
  /**
   * Successful Response
   */
  200: Array<ExistingOrganizationSchema>;
};

export type GetAllOrganizationsOrganizationsGetResponse =
  GetAllOrganizationsOrganizationsGetResponses[keyof GetAllOrganizationsOrganizationsGetResponses];

export type CreateOrganizationOrganizationsPostData = {
  body: CreateOrganizationSchema;
  path?: never;
  query?: never;
  url: '/organizations';
};

export type CreateOrganizationOrganizationsPostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateOrganizationOrganizationsPostError =
  CreateOrganizationOrganizationsPostErrors[keyof CreateOrganizationOrganizationsPostErrors];

export type CreateOrganizationOrganizationsPostResponses = {
  /**
   * Successful Response
   */
  200: OrganizationCreatedSchema;
};

export type CreateOrganizationOrganizationsPostResponse =
  CreateOrganizationOrganizationsPostResponses[keyof CreateOrganizationOrganizationsPostResponses];

export type DeleteOrganizationOrganizationsOrganizationIdDeleteData = {
  body?: never;
  path: {
    organizationId: string;
  };
  query?: never;
  url: '/organizations/{organization_id}';
};

export type DeleteOrganizationOrganizationsOrganizationIdDeleteErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteOrganizationOrganizationsOrganizationIdDeleteError =
  DeleteOrganizationOrganizationsOrganizationIdDeleteErrors[keyof DeleteOrganizationOrganizationsOrganizationIdDeleteErrors];

export type DeleteOrganizationOrganizationsOrganizationIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetOrganizationOrganizationsOrganizationIdGetData = {
  body?: never;
  path: {
    organizationId: string;
  };
  query?: never;
  url: '/organizations/{organization_id}';
};

export type GetOrganizationOrganizationsOrganizationIdGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetOrganizationOrganizationsOrganizationIdGetError =
  GetOrganizationOrganizationsOrganizationIdGetErrors[keyof GetOrganizationOrganizationsOrganizationIdGetErrors];

export type GetOrganizationOrganizationsOrganizationIdGetResponses = {
  /**
   * Successful Response
   */
  200: ExistingOrganizationSchema;
};

export type GetOrganizationOrganizationsOrganizationIdGetResponse =
  GetOrganizationOrganizationsOrganizationIdGetResponses[keyof GetOrganizationOrganizationsOrganizationIdGetResponses];

export type UpdateOrganizationOrganizationsOrganizationIdPutData = {
  body: ExistingOrganizationSchema;
  path: {
    organizationId: string;
  };
  query?: never;
  url: '/organizations/{organization_id}';
};

export type UpdateOrganizationOrganizationsOrganizationIdPutErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateOrganizationOrganizationsOrganizationIdPutError =
  UpdateOrganizationOrganizationsOrganizationIdPutErrors[keyof UpdateOrganizationOrganizationsOrganizationIdPutErrors];

export type UpdateOrganizationOrganizationsOrganizationIdPutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetAllOrganizationUsersOrganizationsOrganizationIdUsersGetData = {
  body?: never;
  path: {
    organizationId: string;
  };
  query?: {
    groups?: string;
    includeDisabled?: boolean;
    page?: number | null;
    pageSize?: number;
    sort?: string | null;
    sortDirection?: string | null;
    digest?: string | null;
    users?: string | null;
    search?: string | null;
  };
  url: '/organizations/{organization_id}/users';
};

export type GetAllOrganizationUsersOrganizationsOrganizationIdUsersGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetAllOrganizationUsersOrganizationsOrganizationIdUsersGetError =
  GetAllOrganizationUsersOrganizationsOrganizationIdUsersGetErrors[keyof GetAllOrganizationUsersOrganizationsOrganizationIdUsersGetErrors];

export type GetAllOrganizationUsersOrganizationsOrganizationIdUsersGetResponses =
  {
    /**
     * Successful Response
     */
    200:
      | Array<OrganizationUserSchema | BasicUserProfile>
      | UserQueryResultSchema;
  };

export type GetAllOrganizationUsersOrganizationsOrganizationIdUsersGetResponse =
  GetAllOrganizationUsersOrganizationsOrganizationIdUsersGetResponses[keyof GetAllOrganizationUsersOrganizationsOrganizationIdUsersGetResponses];

export type AddUserToOrganizationOrganizationsOrganizationIdUsersPostData = {
  body: AddUserToOrganizationSchema;
  path: {
    organizationId: string;
  };
  query?: {
    returnExistingId?: boolean;
  };
  url: '/organizations/{organization_id}/users';
};

export type AddUserToOrganizationOrganizationsOrganizationIdUsersPostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AddUserToOrganizationOrganizationsOrganizationIdUsersPostError =
  AddUserToOrganizationOrganizationsOrganizationIdUsersPostErrors[keyof AddUserToOrganizationOrganizationsOrganizationIdUsersPostErrors];

export type AddUserToOrganizationOrganizationsOrganizationIdUsersPostResponses =
  {
    /**
     * Successful Response
     */
    200: UserAddedToOrganizationSchema;
  };

export type AddUserToOrganizationOrganizationsOrganizationIdUsersPostResponse =
  AddUserToOrganizationOrganizationsOrganizationIdUsersPostResponses[keyof AddUserToOrganizationOrganizationsOrganizationIdUsersPostResponses];

export type CreateUsersBatchOrganizationsOrganizationIdUsersBatchPostData = {
  body: CreateUserBatchArgs;
  path: {
    organizationId: string;
  };
  query?: never;
  url: '/organizations/{organization_id}/users/batch';
};

export type CreateUsersBatchOrganizationsOrganizationIdUsersBatchPostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateUsersBatchOrganizationsOrganizationIdUsersBatchPostError =
  CreateUsersBatchOrganizationsOrganizationIdUsersBatchPostErrors[keyof CreateUsersBatchOrganizationsOrganizationIdUsersBatchPostErrors];

export type CreateUsersBatchOrganizationsOrganizationIdUsersBatchPostResponses =
  {
    /**
     * Successful Response
     */
    200: Array<UserAddedToOrganizationSchema>;
  };

export type CreateUsersBatchOrganizationsOrganizationIdUsersBatchPostResponse =
  CreateUsersBatchOrganizationsOrganizationIdUsersBatchPostResponses[keyof CreateUsersBatchOrganizationsOrganizationIdUsersBatchPostResponses];

export type SafeAddUserToOrganizationOrganizationsOrganizationIdUsersSafePostData =
  {
    body: SafeUserCreate;
    path: {
      organizationId: string;
    };
    query?: never;
    url: '/organizations/{organization_id}/users/safe';
  };

export type SafeAddUserToOrganizationOrganizationsOrganizationIdUsersSafePostErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type SafeAddUserToOrganizationOrganizationsOrganizationIdUsersSafePostError =
  SafeAddUserToOrganizationOrganizationsOrganizationIdUsersSafePostErrors[keyof SafeAddUserToOrganizationOrganizationsOrganizationIdUsersSafePostErrors];

export type SafeAddUserToOrganizationOrganizationsOrganizationIdUsersSafePostResponses =
  {
    /**
     * Successful Response
     */
    200: UserAddedToOrganizationSchema;
  };

export type SafeAddUserToOrganizationOrganizationsOrganizationIdUsersSafePostResponse =
  SafeAddUserToOrganizationOrganizationsOrganizationIdUsersSafePostResponses[keyof SafeAddUserToOrganizationOrganizationsOrganizationIdUsersSafePostResponses];

export type GetUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdGetData =
  {
    body?: never;
    path: {
      organizationId: string;
      organizationUserId: string;
    };
    query?: never;
    url: '/organizations/{organization_id}/users/{organization_user_id}';
  };

export type GetUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdGetErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type GetUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdGetError =
  GetUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdGetErrors[keyof GetUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdGetErrors];

export type GetUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdGetResponses =
  {
    /**
     * Successful Response
     */
    200: OrganizationUserSchema;
  };

export type GetUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdGetResponse =
  GetUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdGetResponses[keyof GetUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdGetResponses];

export type PatchUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdPatchData =
  {
    body: UpdateOrganizationUserSchema;
    path: {
      organizationId: string;
      organizationUserId: string;
    };
    query?: never;
    url: '/organizations/{organization_id}/users/{organization_user_id}';
  };

export type PatchUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdPatchErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type PatchUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdPatchError =
  PatchUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdPatchErrors[keyof PatchUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdPatchErrors];

export type PatchUserInOrganizationOrganizationsOrganizationIdUsersOrganizationUserIdPatchResponses =
  {
    /**
     * Successful Response
     */
    200: unknown;
  };

export type RemoveUserFromOrganizationOrganizationsOrganizationIdUsersUserIdDeleteData =
  {
    body?: never;
    path: {
      organizationId: string;
      userId: string;
    };
    query?: never;
    url: '/organizations/{organization_id}/users/{user_id}';
  };

export type RemoveUserFromOrganizationOrganizationsOrganizationIdUsersUserIdDeleteErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type RemoveUserFromOrganizationOrganizationsOrganizationIdUsersUserIdDeleteError =
  RemoveUserFromOrganizationOrganizationsOrganizationIdUsersUserIdDeleteErrors[keyof RemoveUserFromOrganizationOrganizationsOrganizationIdUsersUserIdDeleteErrors];

export type RemoveUserFromOrganizationOrganizationsOrganizationIdUsersUserIdDeleteResponses =
  {
    /**
     * Successful Response
     */
    200: unknown;
  };

export type GetAddressesForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesGetData =
  {
    body?: never;
    path: {
      organizationId: string;
      organizationUserId: string;
    };
    query?: never;
    url: '/organizations/{organization_id}/users/{organization_user_id}/addresses';
  };

export type GetAddressesForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesGetErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type GetAddressesForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesGetError =
  GetAddressesForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesGetErrors[keyof GetAddressesForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesGetErrors];

export type GetAddressesForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesGetResponses =
  {
    /**
     * Successful Response
     */
    200: Array<ExistingAddressSchema>;
  };

export type GetAddressesForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesGetResponse =
  GetAddressesForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesGetResponses[keyof GetAddressesForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesGetResponses];

export type CreateAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesPostData =
  {
    body: AddressBaseSchema;
    path: {
      organizationId: string;
      organizationUserId: string;
    };
    query?: never;
    url: '/organizations/{organization_id}/users/{organization_user_id}/addresses';
  };

export type CreateAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesPostErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type CreateAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesPostError =
  CreateAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesPostErrors[keyof CreateAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesPostErrors];

export type CreateAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesPostResponses =
  {
    /**
     * Successful Response
     */
    200: CreatedAddressSchema;
  };

export type CreateAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesPostResponse =
  CreateAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesPostResponses[keyof CreateAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesPostResponses];

export type DeleteAddressFromUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesAddressIdDeleteData =
  {
    body?: never;
    path: {
      organizationId: string;
      organizationUserId: string;
      addressId: string;
    };
    query?: never;
    url: '/organizations/{organization_id}/users/{organization_user_id}/addresses/{address_id}';
  };

export type DeleteAddressFromUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesAddressIdDeleteErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type DeleteAddressFromUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesAddressIdDeleteError =
  DeleteAddressFromUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesAddressIdDeleteErrors[keyof DeleteAddressFromUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesAddressIdDeleteErrors];

export type DeleteAddressFromUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesAddressIdDeleteResponses =
  {
    /**
     * Successful Response
     */
    200: unknown;
  };

export type UpdateAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesAddressIdPutData =
  {
    body: ExistingAddressSchema;
    path: {
      organizationId: string;
      organizationUserId: string;
      addressId: string;
    };
    query?: never;
    url: '/organizations/{organization_id}/users/{organization_user_id}/addresses/{address_id}';
  };

export type UpdateAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesAddressIdPutErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type UpdateAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesAddressIdPutError =
  UpdateAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesAddressIdPutErrors[keyof UpdateAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesAddressIdPutErrors];

export type UpdateAddressForUserOrganizationsOrganizationIdUsersOrganizationUserIdAddressesAddressIdPutResponses =
  {
    /**
     * Successful Response
     */
    200: unknown;
  };

export type GetUiConfigurationOrganizationsExternalUiConfigurationGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/organizations/external/ui-configuration';
};

export type GetUiConfigurationOrganizationsExternalUiConfigurationGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
};

export type GetUiConfigurationOrganizationsExternalUiConfigurationGetResponses =
  {
    /**
     * Successful Response
     */
    200: OrganizationUiConfiguration;
  };

export type GetUiConfigurationOrganizationsExternalUiConfigurationGetResponse =
  GetUiConfigurationOrganizationsExternalUiConfigurationGetResponses[keyof GetUiConfigurationOrganizationsExternalUiConfigurationGetResponses];

export type ReadOrganizationConfigurationOrganizationsOrganizationKeyConfigurationGetData =
  {
    body?: never;
    path: {
      organizationKey: string;
    };
    query?: {
      cache?: string;
    };
    url: '/organizations/{organization_key}/configuration';
  };

export type ReadOrganizationConfigurationOrganizationsOrganizationKeyConfigurationGetErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type ReadOrganizationConfigurationOrganizationsOrganizationKeyConfigurationGetError =
  ReadOrganizationConfigurationOrganizationsOrganizationKeyConfigurationGetErrors[keyof ReadOrganizationConfigurationOrganizationsOrganizationKeyConfigurationGetErrors];

export type ReadOrganizationConfigurationOrganizationsOrganizationKeyConfigurationGetResponses =
  {
    /**
     * Successful Response
     */
    200: ExistingOrganizationFullConfigurationSchema;
  };

export type ReadOrganizationConfigurationOrganizationsOrganizationKeyConfigurationGetResponse =
  ReadOrganizationConfigurationOrganizationsOrganizationKeyConfigurationGetResponses[keyof ReadOrganizationConfigurationOrganizationsOrganizationKeyConfigurationGetResponses];

export type GetGroupsForOrganizationOrganizationsOrganizationIdGroupsGetData = {
  body?: never;
  path: {
    organizationId: string;
  };
  query?: {
    workgroupsOnly?: boolean;
  };
  url: '/organizations/{organization_id}/groups';
};

export type GetGroupsForOrganizationOrganizationsOrganizationIdGroupsGetErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type GetGroupsForOrganizationOrganizationsOrganizationIdGroupsGetError =
  GetGroupsForOrganizationOrganizationsOrganizationIdGroupsGetErrors[keyof GetGroupsForOrganizationOrganizationsOrganizationIdGroupsGetErrors];

export type GetGroupsForOrganizationOrganizationsOrganizationIdGroupsGetResponses =
  {
    /**
     * Successful Response
     */
    200: Array<ExistingGroupSchema>;
  };

export type GetGroupsForOrganizationOrganizationsOrganizationIdGroupsGetResponse =
  GetGroupsForOrganizationOrganizationsOrganizationIdGroupsGetResponses[keyof GetGroupsForOrganizationOrganizationsOrganizationIdGroupsGetResponses];

export type CreateGroupOrganizationsOrganizationIdGroupsPostData = {
  body: GroupBaseSchema;
  path: {
    organizationId: string;
  };
  query?: never;
  url: '/organizations/{organization_id}/groups';
};

export type CreateGroupOrganizationsOrganizationIdGroupsPostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateGroupOrganizationsOrganizationIdGroupsPostError =
  CreateGroupOrganizationsOrganizationIdGroupsPostErrors[keyof CreateGroupOrganizationsOrganizationIdGroupsPostErrors];

export type CreateGroupOrganizationsOrganizationIdGroupsPostResponses = {
  /**
   * Successful Response
   */
  200: GroupCreatedSchema;
};

export type CreateGroupOrganizationsOrganizationIdGroupsPostResponse =
  CreateGroupOrganizationsOrganizationIdGroupsPostResponses[keyof CreateGroupOrganizationsOrganizationIdGroupsPostResponses];

export type DeleteGroupOrganizationsOrganizationIdGroupsGroupIdDeleteData = {
  body?: never;
  path: {
    organizationId: string;
    groupId: string;
  };
  query?: never;
  url: '/organizations/{organization_id}/groups/{group_id}';
};

export type DeleteGroupOrganizationsOrganizationIdGroupsGroupIdDeleteErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteGroupOrganizationsOrganizationIdGroupsGroupIdDeleteError =
  DeleteGroupOrganizationsOrganizationIdGroupsGroupIdDeleteErrors[keyof DeleteGroupOrganizationsOrganizationIdGroupsGroupIdDeleteErrors];

export type DeleteGroupOrganizationsOrganizationIdGroupsGroupIdDeleteResponses =
  {
    /**
     * Successful Response
     */
    200: unknown;
  };

export type GetGroupOrganizationsOrganizationIdGroupsGroupIdGetData = {
  body?: never;
  path: {
    organizationId: string;
    groupId: string;
  };
  query?: never;
  url: '/organizations/{organization_id}/groups/{group_id}';
};

export type GetGroupOrganizationsOrganizationIdGroupsGroupIdGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetGroupOrganizationsOrganizationIdGroupsGroupIdGetError =
  GetGroupOrganizationsOrganizationIdGroupsGroupIdGetErrors[keyof GetGroupOrganizationsOrganizationIdGroupsGroupIdGetErrors];

export type GetGroupOrganizationsOrganizationIdGroupsGroupIdGetResponses = {
  /**
   * Successful Response
   */
  200: ExistingGroupSchema;
};

export type GetGroupOrganizationsOrganizationIdGroupsGroupIdGetResponse =
  GetGroupOrganizationsOrganizationIdGroupsGroupIdGetResponses[keyof GetGroupOrganizationsOrganizationIdGroupsGroupIdGetResponses];

export type UpdateGroupOrganizationsOrganizationIdGroupsGroupIdPutData = {
  body: ExistingGroupSchema;
  path: {
    organizationId: string;
    groupId: string;
  };
  query?: never;
  url: '/organizations/{organization_id}/groups/{group_id}';
};

export type UpdateGroupOrganizationsOrganizationIdGroupsGroupIdPutErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateGroupOrganizationsOrganizationIdGroupsGroupIdPutError =
  UpdateGroupOrganizationsOrganizationIdGroupsGroupIdPutErrors[keyof UpdateGroupOrganizationsOrganizationIdGroupsGroupIdPutErrors];

export type UpdateGroupOrganizationsOrganizationIdGroupsGroupIdPutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RemoveUserFromGroupOrganizationsOrganizationIdGroupsGroupIdUsersOrganizationUserIdDeleteData =
  {
    body?: never;
    path: {
      organizationId: string;
      groupId: string;
      organizationUserId: string;
    };
    query?: never;
    url: '/organizations/{organization_id}/groups/{group_id}/users/{organization_user_id}';
  };

export type RemoveUserFromGroupOrganizationsOrganizationIdGroupsGroupIdUsersOrganizationUserIdDeleteErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type RemoveUserFromGroupOrganizationsOrganizationIdGroupsGroupIdUsersOrganizationUserIdDeleteError =
  RemoveUserFromGroupOrganizationsOrganizationIdGroupsGroupIdUsersOrganizationUserIdDeleteErrors[keyof RemoveUserFromGroupOrganizationsOrganizationIdGroupsGroupIdUsersOrganizationUserIdDeleteErrors];

export type RemoveUserFromGroupOrganizationsOrganizationIdGroupsGroupIdUsersOrganizationUserIdDeleteResponses =
  {
    /**
     * Successful Response
     */
    200: unknown;
  };

export type AddUserToGroupOrganizationsOrganizationIdGroupsGroupIdUsersOrganizationUserIdPostData =
  {
    body?: never;
    path: {
      organizationId: string;
      groupId: string;
      organizationUserId: string;
    };
    query?: never;
    url: '/organizations/{organization_id}/groups/{group_id}/users/{organization_user_id}';
  };

export type AddUserToGroupOrganizationsOrganizationIdGroupsGroupIdUsersOrganizationUserIdPostErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type AddUserToGroupOrganizationsOrganizationIdGroupsGroupIdUsersOrganizationUserIdPostError =
  AddUserToGroupOrganizationsOrganizationIdGroupsGroupIdUsersOrganizationUserIdPostErrors[keyof AddUserToGroupOrganizationsOrganizationIdGroupsGroupIdUsersOrganizationUserIdPostErrors];

export type AddUserToGroupOrganizationsOrganizationIdGroupsGroupIdUsersOrganizationUserIdPostResponses =
  {
    /**
     * Successful Response
     */
    200: unknown;
  };

export type GetGlobalFeatureFlagsFeaturesGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/features';
};

export type GetGlobalFeatureFlagsFeaturesGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
};

export type GetGlobalFeatureFlagsFeaturesGetResponses = {
  /**
   * Successful Response
   */
  200: Array<FeatureFlagSchema>;
};

export type GetGlobalFeatureFlagsFeaturesGetResponse =
  GetGlobalFeatureFlagsFeaturesGetResponses[keyof GetGlobalFeatureFlagsFeaturesGetResponses];

export type SetGlobalFeatureFlagsFeaturesPutData = {
  body: Array<FeatureFlagSchema>;
  path?: never;
  query?: never;
  url: '/features';
};

export type SetGlobalFeatureFlagsFeaturesPutErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SetGlobalFeatureFlagsFeaturesPutError =
  SetGlobalFeatureFlagsFeaturesPutErrors[keyof SetGlobalFeatureFlagsFeaturesPutErrors];

export type SetGlobalFeatureFlagsFeaturesPutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetOrganizationFeatureFlagsFeaturesOrganizationsOrganizationIdGetData =
  {
    body?: never;
    path?: never;
    query?: never;
    url: '/features/organizations/{organization_id}';
  };

export type GetOrganizationFeatureFlagsFeaturesOrganizationsOrganizationIdGetErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
  };

export type GetOrganizationFeatureFlagsFeaturesOrganizationsOrganizationIdGetResponses =
  {
    /**
     * Successful Response
     */
    200: Array<FeatureFlagSchema>;
  };

export type GetOrganizationFeatureFlagsFeaturesOrganizationsOrganizationIdGetResponse =
  GetOrganizationFeatureFlagsFeaturesOrganizationsOrganizationIdGetResponses[keyof GetOrganizationFeatureFlagsFeaturesOrganizationsOrganizationIdGetResponses];

export type SetOrganizationFeatureFlagsFeaturesOrganizationsOrganizationIdPutData =
  {
    body: Array<FeatureFlagSchema>;
    path?: never;
    query?: never;
    url: '/features/organizations/{organization_id}';
  };

export type SetOrganizationFeatureFlagsFeaturesOrganizationsOrganizationIdPutErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type SetOrganizationFeatureFlagsFeaturesOrganizationsOrganizationIdPutError =
  SetOrganizationFeatureFlagsFeaturesOrganizationsOrganizationIdPutErrors[keyof SetOrganizationFeatureFlagsFeaturesOrganizationsOrganizationIdPutErrors];

export type SetOrganizationFeatureFlagsFeaturesOrganizationsOrganizationIdPutResponses =
  {
    /**
     * Successful Response
     */
    200: unknown;
  };

export type CacheActionFeaturesCachePostData = {
  body: FeatureFlagCacheActionSchema;
  path?: never;
  query?: never;
  url: '/features/cache';
};

export type CacheActionFeaturesCachePostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CacheActionFeaturesCachePostError =
  CacheActionFeaturesCachePostErrors[keyof CacheActionFeaturesCachePostErrors];

export type CacheActionFeaturesCachePostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetShareLinksByUserShareUsersOrganizationUserIdGetData = {
  body?: never;
  path: {
    organizationUserId: string;
  };
  query?: never;
  url: '/share/users/{organization_user_id}';
};

export type GetShareLinksByUserShareUsersOrganizationUserIdGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetShareLinksByUserShareUsersOrganizationUserIdGetError =
  GetShareLinksByUserShareUsersOrganizationUserIdGetErrors[keyof GetShareLinksByUserShareUsersOrganizationUserIdGetErrors];

export type GetShareLinksByUserShareUsersOrganizationUserIdGetResponses = {
  /**
   * Successful Response
   */
  200: Array<ShareLinkBaseSchema>;
};

export type GetShareLinksByUserShareUsersOrganizationUserIdGetResponse =
  GetShareLinksByUserShareUsersOrganizationUserIdGetResponses[keyof GetShareLinksByUserShareUsersOrganizationUserIdGetResponses];

export type GetShareLinksByExternalIdShareResourcesExternalIdGetData = {
  body?: never;
  path: {
    externalId: string;
  };
  query?: never;
  url: '/share/resources/{external_id}';
};

export type GetShareLinksByExternalIdShareResourcesExternalIdGetErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetShareLinksByExternalIdShareResourcesExternalIdGetError =
  GetShareLinksByExternalIdShareResourcesExternalIdGetErrors[keyof GetShareLinksByExternalIdShareResourcesExternalIdGetErrors];

export type GetShareLinksByExternalIdShareResourcesExternalIdGetResponses = {
  /**
   * Successful Response
   */
  200: Array<ShareLinkBaseSchema>;
};

export type GetShareLinksByExternalIdShareResourcesExternalIdGetResponse =
  GetShareLinksByExternalIdShareResourcesExternalIdGetResponses[keyof GetShareLinksByExternalIdShareResourcesExternalIdGetResponses];

export type CreateShareLinkBatchShareBatchPostData = {
  body: CreateShareLinkBatch;
  path?: never;
  query?: never;
  url: '/share/batch';
};

export type CreateShareLinkBatchShareBatchPostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateShareLinkBatchShareBatchPostError =
  CreateShareLinkBatchShareBatchPostErrors[keyof CreateShareLinkBatchShareBatchPostErrors];

export type CreateShareLinkBatchShareBatchPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type CreateShareLinkSharePostData = {
  body: CreateShareLinkSchema;
  path?: never;
  query?: never;
  url: '/share';
};

export type CreateShareLinkSharePostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateShareLinkSharePostError =
  CreateShareLinkSharePostErrors[keyof CreateShareLinkSharePostErrors];

export type CreateShareLinkSharePostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteShareLinkShareShareLinkIdDeleteData = {
  body?: never;
  path: {
    shareLinkId: string;
  };
  query?: never;
  url: '/share/{share_link_id}';
};

export type DeleteShareLinkShareShareLinkIdDeleteErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteShareLinkShareShareLinkIdDeleteError =
  DeleteShareLinkShareShareLinkIdDeleteErrors[keyof DeleteShareLinkShareShareLinkIdDeleteErrors];

export type DeleteShareLinkShareShareLinkIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type UpdateShareLinkShareShareLinkIdPutData = {
  body: UpdateShareLinkSchema;
  path: {
    shareLinkId: string;
  };
  query?: never;
  url: '/share/{share_link_id}';
};

export type UpdateShareLinkShareShareLinkIdPutErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateShareLinkShareShareLinkIdPutError =
  UpdateShareLinkShareShareLinkIdPutErrors[keyof UpdateShareLinkShareShareLinkIdPutErrors];

export type UpdateShareLinkShareShareLinkIdPutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteAllApiKeysApiKeysDeleteData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api-keys';
};

export type DeleteAllApiKeysApiKeysDeleteErrors = {
  /**
   * Resource not found
   */
  404: unknown;
};

export type DeleteAllApiKeysApiKeysDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetApiKeysApiKeysGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api-keys';
};

export type GetApiKeysApiKeysGetErrors = {
  /**
   * Resource not found
   */
  404: unknown;
};

export type GetApiKeysApiKeysGetResponses = {
  /**
   * Successful Response
   */
  200: Array<ApiKeyIdOnlySchema>;
};

export type GetApiKeysApiKeysGetResponse =
  GetApiKeysApiKeysGetResponses[keyof GetApiKeysApiKeysGetResponses];

export type CreateApiKeyApiKeysPostData = {
  body: CreateApiKeySchema;
  path?: never;
  query?: never;
  url: '/api-keys';
};

export type CreateApiKeyApiKeysPostErrors = {
  /**
   * Resource not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateApiKeyApiKeysPostError =
  CreateApiKeyApiKeysPostErrors[keyof CreateApiKeyApiKeysPostErrors];

export type CreateApiKeyApiKeysPostResponses = {
  /**
   * Successful Response
   */
  200: ApiKeySchema;
};

export type CreateApiKeyApiKeysPostResponse =
  CreateApiKeyApiKeysPostResponses[keyof CreateApiKeyApiKeysPostResponses];

export type DeleteApiKeyApiKeysApiKeyIdDeleteData = {
  body?: never;
  path: {
    apiKeyId: string;
  };
  query?: never;
  url: '/api-keys/{api_key_id}';
};

export type DeleteApiKeyApiKeysApiKeyIdDeleteErrors = {
  /**
   * Resource not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteApiKeyApiKeysApiKeyIdDeleteError =
  DeleteApiKeyApiKeysApiKeyIdDeleteErrors[keyof DeleteApiKeyApiKeysApiKeyIdDeleteErrors];

export type DeleteApiKeyApiKeysApiKeyIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetBusinessesForUserOrganizationsOrganizationIdBusinessesUsersOrganizationUserIdGetData =
  {
    body?: never;
    path: {
      organizationId: string;
      organizationUserId: string;
    };
    query?: never;
    url: '/organizations/{organization_id}/businesses/users/{organization_user_id}';
  };

export type GetBusinessesForUserOrganizationsOrganizationIdBusinessesUsersOrganizationUserIdGetErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type GetBusinessesForUserOrganizationsOrganizationIdBusinessesUsersOrganizationUserIdGetError =
  GetBusinessesForUserOrganizationsOrganizationIdBusinessesUsersOrganizationUserIdGetErrors[keyof GetBusinessesForUserOrganizationsOrganizationIdBusinessesUsersOrganizationUserIdGetErrors];

export type GetBusinessesForUserOrganizationsOrganizationIdBusinessesUsersOrganizationUserIdGetResponses =
  {
    /**
     * Successful Response
     */
    200: Array<ExistingBusinessSchemaOutput>;
  };

export type GetBusinessesForUserOrganizationsOrganizationIdBusinessesUsersOrganizationUserIdGetResponse =
  GetBusinessesForUserOrganizationsOrganizationIdBusinessesUsersOrganizationUserIdGetResponses[keyof GetBusinessesForUserOrganizationsOrganizationIdBusinessesUsersOrganizationUserIdGetResponses];

export type GetBusinessesForOrganizationOrganizationsOrganizationIdBusinessesGetData =
  {
    body?: never;
    path: {
      organizationId: string;
    };
    query?: {
      page?: number | null;
      pageSize?: number;
      sort?: string | null;
      sortDirection?: string | null;
      search?: string | null;
      ids?: string | null;
    };
    url: '/organizations/{organization_id}/businesses';
  };

export type GetBusinessesForOrganizationOrganizationsOrganizationIdBusinessesGetErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type GetBusinessesForOrganizationOrganizationsOrganizationIdBusinessesGetError =
  GetBusinessesForOrganizationOrganizationsOrganizationIdBusinessesGetErrors[keyof GetBusinessesForOrganizationOrganizationsOrganizationIdBusinessesGetErrors];

export type GetBusinessesForOrganizationOrganizationsOrganizationIdBusinessesGetResponses =
  {
    /**
     * Successful Response
     */
    200: Array<ExistingBusinessSchemaOutput> | BusinessQueryResultSchema;
  };

export type GetBusinessesForOrganizationOrganizationsOrganizationIdBusinessesGetResponse =
  GetBusinessesForOrganizationOrganizationsOrganizationIdBusinessesGetResponses[keyof GetBusinessesForOrganizationOrganizationsOrganizationIdBusinessesGetResponses];

export type CreateBusinessOrganizationsOrganizationIdBusinessesPostData = {
  body: BusinessBaseSchema;
  path: {
    organizationId: string;
  };
  query?: never;
  url: '/organizations/{organization_id}/businesses';
};

export type CreateBusinessOrganizationsOrganizationIdBusinessesPostErrors = {
  /**
   * Not Found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateBusinessOrganizationsOrganizationIdBusinessesPostError =
  CreateBusinessOrganizationsOrganizationIdBusinessesPostErrors[keyof CreateBusinessOrganizationsOrganizationIdBusinessesPostErrors];

export type CreateBusinessOrganizationsOrganizationIdBusinessesPostResponses = {
  /**
   * Successful Response
   */
  200: BusinessCreatedSchema;
};

export type CreateBusinessOrganizationsOrganizationIdBusinessesPostResponse =
  CreateBusinessOrganizationsOrganizationIdBusinessesPostResponses[keyof CreateBusinessOrganizationsOrganizationIdBusinessesPostResponses];

export type DeleteBusinessOrganizationsOrganizationIdBusinessesBusinessIdDeleteData =
  {
    body?: never;
    path: {
      organizationId: string;
      businessId: string;
    };
    query?: never;
    url: '/organizations/{organization_id}/businesses/{business_id}';
  };

export type DeleteBusinessOrganizationsOrganizationIdBusinessesBusinessIdDeleteErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type DeleteBusinessOrganizationsOrganizationIdBusinessesBusinessIdDeleteError =
  DeleteBusinessOrganizationsOrganizationIdBusinessesBusinessIdDeleteErrors[keyof DeleteBusinessOrganizationsOrganizationIdBusinessesBusinessIdDeleteErrors];

export type DeleteBusinessOrganizationsOrganizationIdBusinessesBusinessIdDeleteResponses =
  {
    /**
     * Successful Response
     */
    200: unknown;
  };

export type GetBusinessOrganizationsOrganizationIdBusinessesBusinessIdGetData =
  {
    body?: never;
    path: {
      organizationId: string;
      businessId: string;
    };
    query?: never;
    url: '/organizations/{organization_id}/businesses/{business_id}';
  };

export type GetBusinessOrganizationsOrganizationIdBusinessesBusinessIdGetErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type GetBusinessOrganizationsOrganizationIdBusinessesBusinessIdGetError =
  GetBusinessOrganizationsOrganizationIdBusinessesBusinessIdGetErrors[keyof GetBusinessOrganizationsOrganizationIdBusinessesBusinessIdGetErrors];

export type GetBusinessOrganizationsOrganizationIdBusinessesBusinessIdGetResponses =
  {
    /**
     * Successful Response
     */
    200: ExistingBusinessSchemaOutput;
  };

export type GetBusinessOrganizationsOrganizationIdBusinessesBusinessIdGetResponse =
  GetBusinessOrganizationsOrganizationIdBusinessesBusinessIdGetResponses[keyof GetBusinessOrganizationsOrganizationIdBusinessesBusinessIdGetResponses];

export type UpdateBusinessOrganizationsOrganizationIdBusinessesBusinessIdPutData =
  {
    body: ExistingBusinessSchemaInput;
    path: {
      organizationId: string;
      businessId: string;
    };
    query?: never;
    url: '/organizations/{organization_id}/businesses/{business_id}';
  };

export type UpdateBusinessOrganizationsOrganizationIdBusinessesBusinessIdPutErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type UpdateBusinessOrganizationsOrganizationIdBusinessesBusinessIdPutError =
  UpdateBusinessOrganizationsOrganizationIdBusinessesBusinessIdPutErrors[keyof UpdateBusinessOrganizationsOrganizationIdBusinessesBusinessIdPutErrors];

export type UpdateBusinessOrganizationsOrganizationIdBusinessesBusinessIdPutResponses =
  {
    /**
     * Successful Response
     */
    200: unknown;
  };

export type CreateBusinessBatchOrganizationsOrganizationIdBusinessesBatchPostData =
  {
    body: CreateBusinessBatchArgs;
    path: {
      organizationId: string;
    };
    query?: never;
    url: '/organizations/{organization_id}/businesses/batch';
  };

export type CreateBusinessBatchOrganizationsOrganizationIdBusinessesBatchPostErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type CreateBusinessBatchOrganizationsOrganizationIdBusinessesBatchPostError =
  CreateBusinessBatchOrganizationsOrganizationIdBusinessesBatchPostErrors[keyof CreateBusinessBatchOrganizationsOrganizationIdBusinessesBatchPostErrors];

export type CreateBusinessBatchOrganizationsOrganizationIdBusinessesBatchPostResponses =
  {
    /**
     * Successful Response
     */
    200: Array<BusinessCreatedSchema>;
  };

export type CreateBusinessBatchOrganizationsOrganizationIdBusinessesBatchPostResponse =
  CreateBusinessBatchOrganizationsOrganizationIdBusinessesBatchPostResponses[keyof CreateBusinessBatchOrganizationsOrganizationIdBusinessesBatchPostResponses];

export type GetBusinessUsersOrganizationsOrganizationIdBusinessesBusinessIdUsersGetData =
  {
    body?: never;
    path: {
      organizationId: string;
      businessId: string;
    };
    query?: never;
    url: '/organizations/{organization_id}/businesses/{business_id}/users';
  };

export type GetBusinessUsersOrganizationsOrganizationIdBusinessesBusinessIdUsersGetErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type GetBusinessUsersOrganizationsOrganizationIdBusinessesBusinessIdUsersGetError =
  GetBusinessUsersOrganizationsOrganizationIdBusinessesBusinessIdUsersGetErrors[keyof GetBusinessUsersOrganizationsOrganizationIdBusinessesBusinessIdUsersGetErrors];

export type GetBusinessUsersOrganizationsOrganizationIdBusinessesBusinessIdUsersGetResponses =
  {
    /**
     * Successful Response
     */
    200: Array<BasicUserProfile>;
  };

export type GetBusinessUsersOrganizationsOrganizationIdBusinessesBusinessIdUsersGetResponse =
  GetBusinessUsersOrganizationsOrganizationIdBusinessesBusinessIdUsersGetResponses[keyof GetBusinessUsersOrganizationsOrganizationIdBusinessesBusinessIdUsersGetResponses];

export type RemoveUserFromBusinessOrganizationsOrganizationIdBusinessesBusinessIdUsersOrganizationUserIdDeleteData =
  {
    body?: never;
    path: {
      organizationId: string;
      businessId: string;
      organizationUserId: string;
    };
    query?: never;
    url: '/organizations/{organization_id}/businesses/{business_id}/users/{organization_user_id}';
  };

export type RemoveUserFromBusinessOrganizationsOrganizationIdBusinessesBusinessIdUsersOrganizationUserIdDeleteErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type RemoveUserFromBusinessOrganizationsOrganizationIdBusinessesBusinessIdUsersOrganizationUserIdDeleteError =
  RemoveUserFromBusinessOrganizationsOrganizationIdBusinessesBusinessIdUsersOrganizationUserIdDeleteErrors[keyof RemoveUserFromBusinessOrganizationsOrganizationIdBusinessesBusinessIdUsersOrganizationUserIdDeleteErrors];

export type RemoveUserFromBusinessOrganizationsOrganizationIdBusinessesBusinessIdUsersOrganizationUserIdDeleteResponses =
  {
    /**
     * Successful Response
     */
    200: unknown;
  };

export type AddUserToBusinessOrganizationsOrganizationIdBusinessesBusinessIdUsersOrganizationUserIdPostData =
  {
    body?: never;
    path: {
      organizationId: string;
      businessId: string;
      organizationUserId: string;
    };
    query?: never;
    url: '/organizations/{organization_id}/businesses/{business_id}/users/{organization_user_id}';
  };

export type AddUserToBusinessOrganizationsOrganizationIdBusinessesBusinessIdUsersOrganizationUserIdPostErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type AddUserToBusinessOrganizationsOrganizationIdBusinessesBusinessIdUsersOrganizationUserIdPostError =
  AddUserToBusinessOrganizationsOrganizationIdBusinessesBusinessIdUsersOrganizationUserIdPostErrors[keyof AddUserToBusinessOrganizationsOrganizationIdBusinessesBusinessIdUsersOrganizationUserIdPostErrors];

export type AddUserToBusinessOrganizationsOrganizationIdBusinessesBusinessIdUsersOrganizationUserIdPostResponses =
  {
    /**
     * Successful Response
     */
    200: unknown;
  };

export type GetAddressesForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesGetData =
  {
    body?: never;
    path: {
      organizationId: string;
      businessId: string;
    };
    query?: never;
    url: '/organizations/{organization_id}/businesses/{business_id}/addresses';
  };

export type GetAddressesForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesGetErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type GetAddressesForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesGetError =
  GetAddressesForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesGetErrors[keyof GetAddressesForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesGetErrors];

export type GetAddressesForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesGetResponses =
  {
    /**
     * Successful Response
     */
    200: Array<ExistingAddressSchema>;
  };

export type GetAddressesForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesGetResponse =
  GetAddressesForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesGetResponses[keyof GetAddressesForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesGetResponses];

export type CreateAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesPostData =
  {
    body: AddressBaseSchema;
    path: {
      organizationId: string;
      businessId: string;
    };
    query?: never;
    url: '/organizations/{organization_id}/businesses/{business_id}/addresses';
  };

export type CreateAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesPostErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type CreateAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesPostError =
  CreateAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesPostErrors[keyof CreateAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesPostErrors];

export type CreateAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesPostResponses =
  {
    /**
     * Successful Response
     */
    200: CreatedAddressSchema;
  };

export type CreateAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesPostResponse =
  CreateAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesPostResponses[keyof CreateAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesPostResponses];

export type DeleteAddressFromBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesAddressIdDeleteData =
  {
    body?: never;
    path: {
      organizationId: string;
      businessId: string;
      addressId: string;
    };
    query?: never;
    url: '/organizations/{organization_id}/businesses/{business_id}/addresses/{address_id}';
  };

export type DeleteAddressFromBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesAddressIdDeleteErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type DeleteAddressFromBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesAddressIdDeleteError =
  DeleteAddressFromBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesAddressIdDeleteErrors[keyof DeleteAddressFromBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesAddressIdDeleteErrors];

export type DeleteAddressFromBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesAddressIdDeleteResponses =
  {
    /**
     * Successful Response
     */
    200: unknown;
  };

export type UpdateAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesAddressIdPutData =
  {
    body: ExistingAddressSchema;
    path: {
      organizationId: string;
      businessId: string;
      addressId: string;
    };
    query?: never;
    url: '/organizations/{organization_id}/businesses/{business_id}/addresses/{address_id}';
  };

export type UpdateAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesAddressIdPutErrors =
  {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type UpdateAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesAddressIdPutError =
  UpdateAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesAddressIdPutErrors[keyof UpdateAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesAddressIdPutErrors];

export type UpdateAddressForBusinessOrganizationsOrganizationIdBusinessesBusinessIdAddressesAddressIdPutResponses =
  {
    /**
     * Successful Response
     */
    200: unknown;
  };

export type GetRootGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/';
};

export type GetRootGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetStatusCheckStatusGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/status';
};

export type GetStatusCheckStatusGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};
