// AUTO-GENERATED by scripts/generate-mock-providers.mjs.
// Regenerate after `npm run sync-source` brings in new services.
// Do not hand-edit this file — write per-story service stubs in your
// .stories.ts instead, which override these global stubs for that story.

import { autoStub } from './auto-stub';

import { AdHocNotificationService } from '../services/notifications/adhocnotification.service';
import { AdvertisementService } from '../services/organization/advertisement.service';
import { AnnotationFactoryService } from '../web-components/signature/custom-renderer/annotation-factory.service';
import { APIKeyService } from '../services/identity/api-keys.service';
import { ApiService } from '../services/api/api.service';
import { AsyncTaskService } from '../services/asyncTask/async-task.service';
import { AttachmentsService } from '../services/attachments/attachments.service';
import { BaseInterestRateService } from '../services/data/base-interest-rate.service';
import { CacheService } from '../services/cache/cache.service';
import { ClientDocumentsService } from '../services/client/documents/client-documents.service';
import { ClientLoansMockService } from '../services/client/loans/client-loans.mock.service';
import { ClientLoansService } from '../services/client/loans/client-loans.service';
import { ClientRequestsService } from '../services/client/requests/client-requests.service';
import { CoApplicantsService } from '../services/co-applicants/co-applicants.service';
import { CookieConsentService } from '../services/cookie-consent/cookie-consent.service';
import { CreditCheckService } from '../services/data/credit-check.service';
import { CreditCollateralService } from '../services/credit/services/credit-collateral.service';
import { CreditFeeService } from '../services/credit/services/credit-fee.service';
import { CreditFundingEntityService } from '../services/credit/services/credit-funding-entity.service';
import { CreditInsurancePolicyService } from '../services/credit/services/credit-insurance-policy.service';
import { CreditInterestRateService } from '../services/credit/services/credit-interest-rate.service';
import { CreditLendService } from '../services/credit/services/credit-lend.service';
import { CreditServicerService } from '../services/credit/services/credit-servicer.service';
import { CustomRendererService } from '../web-components/signature/custom-renderer/custom-renderer.service';
import { DataExtractionTemplateService } from '../services/documents/data_extraction_template.service';
import { DataTableService } from '../web-components/data-table/service/data-table.service';
import { DiscussionService } from '../services/discussions/discussion.service';
import { DocumentQueryAiService } from '../services/documents/document-query-ai.service';
import { DocumentService } from '../services/documents/document.service';
import { DocumentTemplateRetailersService } from '../services/documents/document-template-retailers.service';
import { DownloadService } from '../services/download.service';
import { DynamicFormService } from '../services/documents/dynamic-form.service';
import { EnvironmentService } from '../services/environment/environment.service';
import { FieldsBridgeService } from '../web-components/pdf/field-framework/services/fields-bridge.service';
import { FieldsService } from '../services/products/fields/fields.service';
import { FormsEmbedService } from '../services/documents/forms-embed.service';
import { GuideContentService } from '../user-guide/guide-content.service';
import { IAMService } from '../services/identity/iam.service';
import { IdentityVerificationService } from '../services/data/identity-verification.service';
import { IntersectionObserverService } from '../services/ui/intersection-observer.service';
import { InvitationService } from '../services/workflows-api/invitation.service';
import { KeyValueService } from '../services/data/keyValue.service';
import { LendAttachmentService } from '../services/lending/lend-attachment.service';
import { LendingManagementService } from '../services/lending/lendingManagement.service';
import { LendingService } from '../services/lending/lending.service';
import { LicenseService } from '../services/organization/license.service';
import { NotificationService } from '../services/notifications/notification.service';
import { OffersService } from '../services/products/offers.service';
import { OpenReplayService } from '../services/openreplay.service';
import { OrganizationService } from '../services/organization/organization.service';
import { PageLayoutService } from '../services/page-layout.service';
import { PdfViewerService } from '../web-components/documents/pdf-viewer/pdf-viewer.service';
import { PermissionService } from '../services/permission/permission.service';
import { PlatformService } from '../services/platform/platform.service';
import { PrefillDataService } from '../services/data/prefill-data.service';
import { ProductRuleLibraryService } from '../services/products/product-rule-library.service';
import { ProductsService } from '../services/products/products.service';
import { RealtimeMessagingService } from '../services/realtimeMessaging/realtime-messaging.service';
import { RequestAttachmentService } from '../services/workflows-api/request-attachment.service';
import { RequestsService } from '../services/workflows-api/requests.service';
import { RequestSummaryService } from '../web-components/requests/request-application-summary/request-application-summary.service';
import { ScorecardLibraryService } from '../services/products/scorecard-library.service';
import { ServicingService } from '../services/lending/servicing/servicing.service';
import { SignatureService } from '../services/signature/signature.service';
import { SoftwareUpdateService } from '../services/ui/software-update.service';
import { TemplateRetailersService } from '../services/workflows-api/template-retailers.service';
import { TenantService } from '../services/organization/tenant.service';
import { TextAiService } from '../services/text-ai/text-ai.service';
import { UiNotificationService } from '../services/notifications/ui-notification.service';
import { UserActivityService } from '../services/identity/userActivity';
import { Web2ChatService } from '../services/web2chat/web2chat.service';
import { WorkflowProductService } from '../services/products/workflow-product.service';
import { WorkflowService } from '../services/workflows-api/workflow.service';
import { ZoomService } from '../services/ui/zoom.service';

export const GLOBAL_STUB_PROVIDERS = [
  { provide: AdHocNotificationService, useValue: autoStub() as unknown as AdHocNotificationService },
  { provide: AdvertisementService, useValue: autoStub() as unknown as AdvertisementService },
  { provide: AnnotationFactoryService, useValue: autoStub() as unknown as AnnotationFactoryService },
  { provide: APIKeyService, useValue: autoStub() as unknown as APIKeyService },
  { provide: ApiService, useValue: autoStub() as unknown as ApiService },
  { provide: AsyncTaskService, useValue: autoStub() as unknown as AsyncTaskService },
  { provide: AttachmentsService, useValue: autoStub() as unknown as AttachmentsService },
  { provide: BaseInterestRateService, useValue: autoStub() as unknown as BaseInterestRateService },
  { provide: CacheService, useValue: autoStub() as unknown as CacheService },
  { provide: ClientDocumentsService, useValue: autoStub() as unknown as ClientDocumentsService },
  { provide: ClientLoansMockService, useValue: autoStub() as unknown as ClientLoansMockService },
  { provide: ClientLoansService, useValue: autoStub() as unknown as ClientLoansService },
  { provide: ClientRequestsService, useValue: autoStub() as unknown as ClientRequestsService },
  { provide: CoApplicantsService, useValue: autoStub() as unknown as CoApplicantsService },
  { provide: CookieConsentService, useValue: autoStub() as unknown as CookieConsentService },
  { provide: CreditCheckService, useValue: autoStub() as unknown as CreditCheckService },
  { provide: CreditCollateralService, useValue: autoStub() as unknown as CreditCollateralService },
  { provide: CreditFeeService, useValue: autoStub() as unknown as CreditFeeService },
  { provide: CreditFundingEntityService, useValue: autoStub() as unknown as CreditFundingEntityService },
  { provide: CreditInsurancePolicyService, useValue: autoStub() as unknown as CreditInsurancePolicyService },
  { provide: CreditInterestRateService, useValue: autoStub() as unknown as CreditInterestRateService },
  { provide: CreditLendService, useValue: autoStub() as unknown as CreditLendService },
  { provide: CreditServicerService, useValue: autoStub() as unknown as CreditServicerService },
  { provide: CustomRendererService, useValue: autoStub() as unknown as CustomRendererService },
  { provide: DataExtractionTemplateService, useValue: autoStub() as unknown as DataExtractionTemplateService },
  { provide: DataTableService, useValue: autoStub() as unknown as DataTableService<Record<string, unknown>> },
  { provide: DiscussionService, useValue: autoStub() as unknown as DiscussionService },
  { provide: DocumentQueryAiService, useValue: autoStub() as unknown as DocumentQueryAiService },
  { provide: DocumentService, useValue: autoStub() as unknown as DocumentService },
  { provide: DocumentTemplateRetailersService, useValue: autoStub() as unknown as DocumentTemplateRetailersService },
  { provide: DownloadService, useValue: autoStub() as unknown as DownloadService },
  { provide: DynamicFormService, useValue: autoStub() as unknown as DynamicFormService },
  { provide: EnvironmentService, useValue: autoStub() as unknown as EnvironmentService },
  { provide: FieldsBridgeService, useValue: autoStub() as unknown as FieldsBridgeService },
  { provide: FieldsService, useValue: autoStub() as unknown as FieldsService },
  { provide: FormsEmbedService, useValue: autoStub() as unknown as FormsEmbedService },
  { provide: GuideContentService, useValue: autoStub() as unknown as GuideContentService },
  { provide: IAMService, useValue: autoStub() as unknown as IAMService },
  { provide: IdentityVerificationService, useValue: autoStub() as unknown as IdentityVerificationService },
  { provide: IntersectionObserverService, useValue: autoStub() as unknown as IntersectionObserverService },
  { provide: InvitationService, useValue: autoStub() as unknown as InvitationService },
  { provide: KeyValueService, useValue: autoStub() as unknown as KeyValueService },
  { provide: LendAttachmentService, useValue: autoStub() as unknown as LendAttachmentService },
  { provide: LendingManagementService, useValue: autoStub() as unknown as LendingManagementService },
  { provide: LendingService, useValue: autoStub() as unknown as LendingService },
  { provide: LicenseService, useValue: autoStub() as unknown as LicenseService },
  { provide: NotificationService, useValue: autoStub() as unknown as NotificationService },
  { provide: OffersService, useValue: autoStub() as unknown as OffersService },
  { provide: OpenReplayService, useValue: autoStub() as unknown as OpenReplayService },
  { provide: OrganizationService, useValue: autoStub() as unknown as OrganizationService },
  { provide: PageLayoutService, useValue: autoStub() as unknown as PageLayoutService },
  { provide: PdfViewerService, useValue: autoStub() as unknown as PdfViewerService },
  { provide: PermissionService, useValue: autoStub() as unknown as PermissionService },
  { provide: PlatformService, useValue: autoStub() as unknown as PlatformService },
  { provide: PrefillDataService, useValue: autoStub() as unknown as PrefillDataService },
  { provide: ProductRuleLibraryService, useValue: autoStub() as unknown as ProductRuleLibraryService },
  { provide: ProductsService, useValue: autoStub() as unknown as ProductsService },
  { provide: RealtimeMessagingService, useValue: autoStub() as unknown as RealtimeMessagingService },
  { provide: RequestAttachmentService, useValue: autoStub() as unknown as RequestAttachmentService },
  { provide: RequestsService, useValue: autoStub() as unknown as RequestsService },
  { provide: RequestSummaryService, useValue: autoStub() as unknown as RequestSummaryService },
  { provide: ScorecardLibraryService, useValue: autoStub() as unknown as ScorecardLibraryService },
  { provide: ServicingService, useValue: autoStub() as unknown as ServicingService },
  { provide: SignatureService, useValue: autoStub() as unknown as SignatureService },
  { provide: SoftwareUpdateService, useValue: autoStub() as unknown as SoftwareUpdateService },
  { provide: TemplateRetailersService, useValue: autoStub() as unknown as TemplateRetailersService },
  { provide: TenantService, useValue: autoStub() as unknown as TenantService },
  { provide: TextAiService, useValue: autoStub() as unknown as TextAiService },
  { provide: UiNotificationService, useValue: autoStub() as unknown as UiNotificationService },
  { provide: UserActivityService, useValue: autoStub() as unknown as UserActivityService },
  { provide: Web2ChatService, useValue: autoStub() as unknown as Web2ChatService },
  { provide: WorkflowProductService, useValue: autoStub() as unknown as WorkflowProductService },
  { provide: WorkflowService, useValue: autoStub() as unknown as WorkflowService },
  { provide: ZoomService, useValue: autoStub() as unknown as ZoomService },
];
